---
title: "Simulation+Comparison+Pfilter"
author: "Yize Hao"
date: "2024-03-26"
output: html_document
---
#### *WWR* rinit + dt=1/4 + *WWR* rproc + EqEq + old

```{r}
# measurement model 
dmeas <- Csnippet("
                  if (ISNA(cases1)) {
                  lik = (give_log) ? 0 : 1;
                  } else {
                        lik =  dbinom(cases1, H1, 0.07, 1) +
                        dbinom(cases2, H2, 0.07, 1) +
                        dbinom(cases3, H3, 0.07, 1);
                      
                    lik = (give_log) ? lik : exp(lik);
                        
                    }")
rmeas <-  Csnippet("
                    cases1 = rbinom(H1, 0.07);
                    cases2 = rbinom(H2, 0.07);
                    cases3 = rbinom(H3, 0.07);
                  ")



rproc <- Csnippet("
    int I = I1 + I2 + I3;
    int trans_S1[3], trans_S2[3], trans_S3[2], trans_I1[3], trans_I2[3], trans_I3[2], trans_R1[3], trans_R2[3], trans_R3[2];
    
    double prob_S1[3],prob_I1[3],prob_R1[3],prob_S2[3],prob_I2[3],prob_R2[3],prob_S3[2],prob_I3[2],prob_R3[2];
    
    double kappa = (1 + beta11*cos(2*3.141593*t/52 + phi));
    
    // Define rate
    prob_S1[0] = 1-exp(-dt*beta1*kappa*I/N); // 0->1
    prob_S1[1] = 1-exp(-delta1*dt);
    prob_S1[2] = exp(-delta1*dt) + exp(-dt*beta1*kappa*I/N) - 1;
    
    prob_I1[0] = 1-exp(-gamma*dt);
    prob_I1[1] = 1-exp(-delta1*dt);
    prob_I1[2] = exp(-gamma*dt)+exp(-delta1*dt) - 1;
    
    prob_R1[0] = 1 - exp(-omega*dt);  // E_1,t this goes back to S_1,(t+1)
    prob_R1[1] = 1 - exp(-delta1*dt);
    prob_R1[2] = exp(-omega*dt) + exp(-delta1*dt) - 1;
    
    prob_S2[0] = 1-exp(-dt*beta2*kappa*I/N);
    prob_S2[1] = 1-exp(-delta2*dt);
    prob_S2[2] = exp(-delta2*dt) + exp(-dt*beta2*kappa*I/N) - 1;
    
    prob_I2[0] = 1-exp(-dt*gamma);
    prob_I2[1] = 1-exp(-dt*delta2);
    prob_I2[2] = exp(-dt*gamma)+exp(-dt*delta2) - 1;
    
    prob_R2[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R2[1] = 1 - exp(-dt*delta2);
    prob_R2[2] = exp(-dt*omega) + exp(-dt*delta2) - 1;
    
    // For Age Group (3): Die first before transition;
    
    int S3mD, I3mD, R3mD;
    
    S3mD = rbinom(S3, 1-dt*mu); 
    I3mD = rbinom(I3, 1-dt*mu);
    R3mD = rbinom(R3, 1-dt*mu);
    
    prob_S3[0] = 1-exp(-dt*beta3*kappa*I/N);
    prob_S3[1] = exp(-dt*beta3*kappa*I/N);
    
    prob_I3[0] = 1 - exp(-dt*gamma);
    prob_I3[1] = exp(-dt*gamma);
    
    prob_R3[0] = 1 - exp(-dt*omega);
    prob_R3[1] = exp(-dt*omega);
    
    // Transition
    // B: S->I
    // C: I->R
    // F: Aging: (1)->(2)->(3)
    // E: R->S
    // D: Death
    //// Note: Here S_1, S_2... are all old value from (t-1)
    rmultinom(S1, &prob_S1, 3, &trans_S1); // B, F, S-B-F
    rmultinom(I1, &prob_I1, 3, &trans_I1); // C, F, I-C-F
    rmultinom(R1, &prob_R1, 3, &trans_R1); // E, F, R-E-F
    
    rmultinom(S2, &prob_S2, 3, &trans_S2); // B, F, S-B-F
    rmultinom(I2, &prob_I2, 3, &trans_I2); // C, F, I-C-F
    rmultinom(R2, &prob_R2, 3, &trans_R2); // E, F, R-E-F
    
    rmultinom(S3mD, &prob_S3, 2, &trans_S3); // B, (S-D)-B
    rmultinom(I3mD, &prob_I3, 2, &trans_I3); // C, (I-D)-C
    rmultinom(R3mD, &prob_R3, 2, &trans_R3); // E, (R-D)-E
    
    S1 = trans_S1[2] + trans_R1[0] + rpois(4*1025.7); // Include Birth
    I1 = trans_I1[2] + trans_S1[0];
    R1 = trans_R1[2] + trans_I1[0];
    
    S2 = trans_S2[2] + trans_R2[0] + trans_S1[1]; // Include Aging
    I2 = trans_I2[2] + trans_S2[0] + trans_I1[1];
    R2 = trans_R2[2] + trans_I2[0] + trans_R1[1];
    
    S3 = trans_S3[1] + trans_R3[0] + trans_S2[1]; // Include Aging
    I3 = trans_I3[1] + trans_S3[0] + trans_I2[1];
    R3 = trans_R3[1] + trans_I3[0] + trans_R2[1];
    
    //Accumvar
    H1 += trans_S1[0];
    H2 += trans_S2[0];
    H3 += trans_S3[0];
")


# define parameters (without betas)
params_fixed <- c(gamma=1, delta1=0.003636364,delta2=1/(55*52), alpha=1/(78.86912*52), mu=0, N=82372825, omega=1/(1*52))
rinit <- Csnippet("
    S1=3876549;
    I1=30351;
    R1=1315221;
    S2=57139612;
    I2=871;
    R2=302852;
    S3=19573727;
    I3=2550;
    R3=131092;
    H1 = 0;
    H2 = 0;
    H3 = 0;
")

# Set to MLE
params_stocks_stst_mle <- params_fixed

params_stocks_stst_mle["beta1"] <- 12.15
params_stocks_stst_mle["beta2"] <- 0.22
params_stocks_stst_mle["beta3"] <- 0.34
params_stocks_stst_mle["phi"] <- 0.017
params_stocks_stst_mle["beta11"] <- 0.022


avg_1 <- c()
med_1 <- c()
var_1 <- c()
avg_2 <- c()
med_2 <- c()
var_2 <- c()
avg_3 <- c()
med_3 <- c()
var_3 <- c()
for(i in 1:1000){
  set.seed(123+765*i)
  sim1 <- simulate(t0=0,
                 times=c(1:416),
                 dmeasure = dmeas,
                 rmeasure = rmeas,
                 rprocess = discrete_time(rproc, delta.t = 1/4),
                 statenames = c("S1", "I1", "R1", "H1", 
                                "S2", "I2", "R2", "H2",
                                "S3", "I3", "R3", "H3"),
                 obsnames=c("cases1","cases2","cases3"),
                 paramnames = names(params_stocks_stst_mle),
                 accumvars=c("H1", "H2", "H3"),
                 rinit=rinit,
                 params = params_stocks_stst_mle
                 )
  sim_data <- as.data.frame(sim1)
  #mean
  avg_1[i] <- sim_data$cases1 |> mean()
  avg_2[i] <- sim_data$cases2 |> mean()
  avg_3[i] <- sim_data$cases3 |> mean()
  #median
  med_1[i] <- sim_data$cases1 |> median()
  med_2[i] <- sim_data$cases2 |> median()
  med_3[i] <- sim_data$cases3 |> median()
  #variance
  var_1[i] <- sim_data$cases1 |> var()
  var_2[i] <- sim_data$cases2 |> var()
  var_3[i] <- sim_data$cases3 |> var()
}

sim_compare_pomp_EqEq <- data.frame(avg_1,avg_2,avg_3,
                               med_1,med_2,med_3,
                               var_1,var_2,var_3)
write.csv(sim_compare_pomp_EqEq, file = "sim_compare_pomp_EqEq_old.csv")
```

#### Compare - EqEq + old

```{r}
sim_compare_EqEq <- read.csv("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/EqEq/Comparison/sim_compare_WWR_EqEq_old.csv")
sim_compare_pomp_EqEq <- read.csv("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/EqEq/Comparison/sim_compare_pomp_EqEq_old.csv")
```

```{r}
c(t.test(sim_compare_EqEq$avg_1, sim_compare_pomp_EqEq$avg_1)$p.value,
  t.test(sim_compare_EqEq$avg_2, sim_compare_pomp_EqEq$avg_2)$p.value,
  t.test(sim_compare_EqEq$avg_3, sim_compare_pomp_EqEq$avg_3)$p.value,
  t.test(sim_compare_EqEq$med_1, sim_compare_pomp_EqEq$med_1)$p.value,
  t.test(sim_compare_EqEq$med_2, sim_compare_pomp_EqEq$med_2)$p.value,
  t.test(sim_compare_EqEq$med_3, sim_compare_pomp_EqEq$med_3)$p.value,
  t.test(sim_compare_EqEq$var_1, sim_compare_pomp_EqEq$var_1)$p.value,
  t.test(sim_compare_EqEq$var_2, sim_compare_pomp_EqEq$var_2)$p.value,
  t.test(sim_compare_EqEq$var_3, sim_compare_pomp_EqEq$var_3)$p.value)
```

```{r}
x <- data.frame(wwr=sim_compare_EqEq$avg_1,pomp=sim_compare_pomp_EqEq$avg_1)
data<- melt(x)
p_avg_1 <- ggplot(data,aes(x=value, fill=variable)) + geom_density(alpha=0.25)+ labs(x = "Mean Group 1 - EqEq") + ggtitle("p = 0.23718390")

x <- data.frame(wwr=sim_compare_EqEq$avg_2,pomp=sim_compare_pomp_EqEq$avg_2)
data<- melt(x)
p_avg_2 <- ggplot(data,aes(x=value, fill=variable)) + geom_density(alpha=0.25)+ labs(x = "Mean Group 2 - EqEq") + ggtitle("p = 0.80707787")

x <- data.frame(wwr=sim_compare_EqEq$avg_3,pomp=sim_compare_pomp_EqEq$avg_3)
data<- melt(x)
p_avg_3 <- ggplot(data,aes(x=value, fill=variable)) + geom_density(alpha=0.25)+ labs(x = "Mean Group 3 - EqEq") + ggtitle("p = 0.23356039")

x <- data.frame(wwr=sim_compare_EqEq$med_1,pomp=sim_compare_pomp_EqEq$med_1)
data<- melt(x)
p_med_1 <- ggplot(data,aes(x=value, fill=variable)) + geom_density(alpha=0.25)+ labs(x = "Median Group 1 - EqEq") + ggtitle("p = 0.16614202")

x <- data.frame(wwr=sim_compare_EqEq$med_2,pomp=sim_compare_pomp_EqEq$med_2)
data<- melt(x)
p_med_2 <- ggplot(data,aes(x=value, fill=variable)) + 
  geom_density(alpha=0.25) + 
  labs(x = "Median Group 2 - EqEq") + 
  ggtitle("p = 0.53845103")

x <- data.frame(wwr=sim_compare_EqEq$med_3,pomp=sim_compare_pomp_EqEq$med_3)
data<- melt(x)
p_med_3 <- ggplot(data,aes(x=value, fill=variable)) + geom_density(alpha=0.25)+ labs(x = "Median Group 3 - EqEq") + 
  ggtitle("p = 0.90234815")

x <- data.frame(wwr=sim_compare_EqEq$var_1,pomp=sim_compare_pomp_EqEq$var_1)
data<- melt(x)
p_var_1 <- ggplot(data,aes(x=value, fill=variable)) + geom_density(alpha=0.25)+ labs(x = "Varience Group 1 - EqEq") + 
  ggtitle("p = 0.06074556")

x <- data.frame(wwr=sim_compare_EqEq$var_2,pomp=sim_compare_pomp_EqEq$var_2)
data<- melt(x)
p_var_2 <- ggplot(data,aes(x=value, fill=variable)) + geom_density(alpha=0.25)+ labs(x = "Varience Group 2 - EqEq") + 
  ggtitle("p = 0.05417241")

x <- data.frame(wwr=sim_compare_EqEq$var_3,pomp=sim_compare_pomp_EqEq$var_3)
data<- melt(x)
p_var_3 <- ggplot(data,aes(x=value, fill=variable)) + geom_density(alpha=0.25) + labs(x = "Varience Group 3 - EqEq") + 
  ggtitle("p = 0.05508224")

pdf("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/EqEq/Comparison/compare_density_plot_EqEq_old.pdf",width=10,height=10)
plot <- ggarrange(p_avg_1,p_avg_2,p_avg_3,
          p_med_1,p_med_2,p_med_3,
          p_var_1,p_var_2,p_var_3, nrow=3, ncol=3)
annotate_figure(plot, top = text_grob("EqEq model: T-test with 1000 Simulations", color = "black", face = "bold", size = 14))
dev.off()

png("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/EqEq/Comparison/compare_density_plot_EqEq_old.png",width=800,height=800)
plot <- ggarrange(p_avg_1,p_avg_2,p_avg_3,
          p_med_1,p_med_2,p_med_3,
          p_var_1,p_var_2,p_var_3, nrow=3, ncol=3)
annotate_figure(plot, top = text_grob("EqEq model: T-test with 1000 Simulations", color = "black", face = "bold", size = 14))
dev.off()
```

#### Two random Simulation Plots + EqEq

```{r}
# measurement model 
dmeas <- Csnippet("
                  if (ISNA(cases1)) {
                  lik = (give_log) ? 0 : 1;
                  } else {
                        lik =  dbinom(cases1, H1, 0.07, 1) +
                        dbinom(cases2, H2, 0.07, 1) +
                        dbinom(cases3, H3, 0.07, 1);
                      
                    lik = (give_log) ? lik : exp(lik);
                        
                    }")
rmeas <-  Csnippet("
                    cases1 = rbinom(H1, 0.07);
                    cases2 = rbinom(H2, 0.07);
                    cases3 = rbinom(H3, 0.07);
                  ")



rproc <- Csnippet("
    int I = I1 + I2 + I3;
    int trans_S1[3], trans_S2[3], trans_S3[2], trans_I1[3], trans_I2[3], trans_I3[2], trans_R1[3], trans_R2[3], trans_R3[2];
    
    double prob_S1[3],prob_I1[3],prob_R1[3],prob_S2[3],prob_I2[3],prob_R2[3],prob_S3[2],prob_I3[2],prob_R3[2];
    
    double kappa = (1 + beta11*cos(2*3.141593*t/52 + phi));
    
    // Define rate
    prob_S1[0] = 1-exp(-dt*beta1*kappa*I/N); // 0->1
    prob_S1[1] = 1-exp(-delta1*dt);
    prob_S1[2] = exp(-delta1*dt) + exp(-dt*beta1*kappa*I/N) - 1;
    
    prob_I1[0] = 1-exp(-gamma*dt);
    prob_I1[1] = 1-exp(-delta1*dt);
    prob_I1[2] = exp(-gamma*dt)+exp(-delta1*dt) - 1;
    
    prob_R1[0] = 1 - exp(-omega*dt);  // E_1,t this goes back to S_1,(t+1)
    prob_R1[1] = 1 - exp(-delta1*dt);
    prob_R1[2] = exp(-omega*dt) + exp(-delta1*dt) - 1;
    
    prob_S2[0] = 1-exp(-dt*beta2*kappa*I/N);
    prob_S2[1] = 1-exp(-delta2*dt);
    prob_S2[2] = exp(-delta2*dt) + exp(-dt*beta2*kappa*I/N) - 1;
    
    prob_I2[0] = 1-exp(-dt*gamma);
    prob_I2[1] = 1-exp(-dt*delta2);
    prob_I2[2] = exp(-dt*gamma)+exp(-dt*delta2) - 1;
    
    prob_R2[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R2[1] = 1 - exp(-dt*delta2);
    prob_R2[2] = exp(-dt*omega) + exp(-dt*delta2) - 1;
    
    // For Age Group (3): Die first before transition;
    
    int S3mD, I3mD, R3mD;
    
    S3mD = rbinom(S3, 1-dt*mu); 
    I3mD = rbinom(I3, 1-dt*mu);
    R3mD = rbinom(R3, 1-dt*mu);
    
    prob_S3[0] = 1-exp(-dt*beta3*kappa*I/N);
    prob_S3[1] = exp(-dt*beta3*kappa*I/N);
    
    prob_I3[0] = 1 - exp(-dt*gamma);
    prob_I3[1] = exp(-dt*gamma);
    
    prob_R3[0] = 1 - exp(-dt*omega);
    prob_R3[1] = exp(-dt*omega);
    
    // Transition
    // B: S->I
    // C: I->R
    // F: Aging: (1)->(2)->(3)
    // E: R->S
    // D: Death
    //// Note: Here S_1, S_2... are all old value from (t-1)
    rmultinom(S1, &prob_S1, 3, &trans_S1); // B, F, S-B-F
    rmultinom(I1, &prob_I1, 3, &trans_I1); // C, F, I-C-F
    rmultinom(R1, &prob_R1, 3, &trans_R1); // E, F, R-E-F
    
    rmultinom(S2, &prob_S2, 3, &trans_S2); // B, F, S-B-F
    rmultinom(I2, &prob_I2, 3, &trans_I2); // C, F, I-C-F
    rmultinom(R2, &prob_R2, 3, &trans_R2); // E, F, R-E-F
    
    rmultinom(S3mD, &prob_S3, 2, &trans_S3); // B, (S-D)-B
    rmultinom(I3mD, &prob_I3, 2, &trans_I3); // C, (I-D)-C
    rmultinom(R3mD, &prob_R3, 2, &trans_R3); // E, (R-D)-E
    
    S1 = trans_S1[2] + trans_R1[0] + rpois(4*1025.7); // Include Birth
    I1 = trans_I1[2] + trans_S1[0];
    R1 = trans_R1[2] + trans_I1[0];
    
    S2 = trans_S2[2] + trans_R2[0] + trans_S1[1]; // Include Aging
    I2 = trans_I2[2] + trans_S2[0] + trans_I1[1];
    R2 = trans_R2[2] + trans_I2[0] + trans_R1[1];
    
    S3 = trans_S3[1] + trans_R3[0] + trans_S2[1]; // Include Aging
    I3 = trans_I3[1] + trans_S3[0] + trans_I2[1];
    R3 = trans_R3[1] + trans_I3[0] + trans_R2[1];
    
    //Accumvar
    H1 += trans_S1[0];
    H2 += trans_S2[0];
    H3 += trans_S3[0];
")


# define parameters (without betas)
params_fixed <- c(gamma=1, delta1=0.003636364,delta2=1/(55*52), alpha=1/(78.86912*52), mu=0, N=82372825, omega=1/(1*52))
rinit <- Csnippet("
    S1=3876549;
    I1=30351;
    R1=1315221;
    S2=57139612;
    I2=871;
    R2=302852;
    S3=19573727;
    I3=2550;
    R3=131092;
    H1 = 0;
    H2 = 0;
    H3 = 0;
")

# Set to MLE
params_stocks_stst_mle <- params_fixed

params_stocks_stst_mle["beta1"] <- 12.15
params_stocks_stst_mle["beta2"] <- 0.22
params_stocks_stst_mle["beta3"] <- 0.34
params_stocks_stst_mle["phi"] <- 0.017
params_stocks_stst_mle["beta11"] <- 0.022

set.seed(1928475)
### Simulation
sim1 <- simulate(t0=0,
                 times=c(1:416),
                 dmeasure = dmeas,
                 rmeasure = rmeas,
                 rprocess = discrete_time(rproc, delta.t = 1/4),
                 statenames = c("S1", "I1", "R1", "H1", 
                                "S2", "I2", "R2", "H2",
                                "S3", "I3", "R3", "H3"),
                 obsnames=c("cases1","cases2","cases3"),
                 paramnames = names(params_stocks_stst_mle),
                 accumvars=c("H1", "H2", "H3"),
                 rinit=rinit,
                 params = params_stocks_stst_mle
                 )
sim_data <- as.data.frame(sim1)

save(sim_data, file="~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/sim_data_eqeq.Rdata")

p_EqEq_pomp <- ggplot(data=sim_data) + 
  geom_line(aes(x=time, y=cases1),color='green') +
  geom_line(aes(x=time, y=cases2), color='red') +
  geom_line(aes(x=time, y=cases3), color='blue') +
  ylab('Y_sim_pomp')+xlab('date')


pdf("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/EqEq/Comparison/two_random_simplots_EqEq.pdf", height=5,width=10)
plot <- ggarrange(p_EqEq_pomp, p_EqEq_WWR, nrow=1)
annotate_figure(plot, top = text_grob("Two random simulations from EqEq pomp & EqEq WWR", color = "black", face = "bold", size = 20))
dev.off()

png("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/EqEq/Comparison/two_random_simplots_EqEq.png", height=800,width=1500)
plot <- ggarrange(p_EqEq_pomp, p_EqEq_WWR, nrow=1)
annotate_figure(plot, top = text_grob("Two random simulations from EqEq pomp & EqEq WWR", color = "black", face = "bold", size = 20))
dev.off()
```


#### *WWR* rinit + dt=1/4 + *WWR* rproc + EqOv

```{r}
# measurement model 
dmeas <- Csnippet("
                  if (ISNA(cases1)) {
                  lik = (give_log) ? 0 : 1;
                  } else {
                        lik =  dbinom(cases1, H1, q1, 1) +
                        dbinom(cases2, H2, q2, 1) +
                        dbinom(cases3, H3, q3, 1);
                      
                    lik = (give_log) ? lik : exp(lik);
                        
                    }")
rmeas <-  Csnippet("
                    cases1 = rbinom(H1, q1);
                    cases2 = rbinom(H2, q2);
                    cases3 = rbinom(H3, q3);
                  ")



rproc <- Csnippet("
    int I = I1 + I2 + I3;
    int trans_S1[3], trans_S2[3], trans_S3[2], trans_I1[3], trans_I2[3], trans_I3[2], trans_R1[3], trans_R2[3], trans_R3[2];
    
    double prob_S1[3],prob_I1[3],prob_R1[3],prob_S2[3],prob_I2[3],prob_R2[3],prob_S3[2],prob_I3[2],prob_R3[2];
    
    
    double kappa = (1 + beta11*cos(2*3.141593*t/52 + phi));
    
    // Define rate
    prob_S1[0] = 1-exp(-dt*beta1*kappa*I/N); // 0->1
    prob_S1[1] = 1-exp(-delta1*dt);
    prob_S1[2] = exp(-delta1*dt) + exp(-dt*beta1*kappa*I/N) - 1;
    
    prob_I1[0] = 1-exp(-gamma*dt);
    prob_I1[1] = 1-exp(-delta1*dt);
    prob_I1[2] = exp(-gamma*dt)+exp(-delta1*dt) - 1;
    
    prob_R1[0] = 1 - exp(-omega*dt);  // E_1,t this goes back to S_1,(t+1)
    prob_R1[1] = 1 - exp(-delta1*dt);
    prob_R1[2] = exp(-omega*dt) + exp(-delta1*dt) - 1;
    
    prob_S2[0] = 1-exp(-dt*beta2*kappa*I/N);
    prob_S2[1] = 1-exp(-delta2*dt);
    prob_S2[2] = exp(-delta2*dt) + exp(-dt*beta2*kappa*I/N) - 1;
    
    prob_I2[0] = 1-exp(-dt*gamma);
    prob_I2[1] = 1-exp(-dt*delta2);
    prob_I2[2] = exp(-dt*gamma)+exp(-dt*delta2) - 1;
    
    prob_R2[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R2[1] = 1 - exp(-dt*delta2);
    prob_R2[2] = exp(-dt*omega) + exp(-dt*delta2) - 1;
    
    // For Age Group (3): Die first before transition;
    
    int S3mD, I3mD, R3mD;
    
    S3mD = rbinom(S3, 1-dt*mu); 
    I3mD = rbinom(I3, 1-dt*mu);
    R3mD = rbinom(R3, 1-dt*mu);
    
    prob_S3[0] = 1-exp(-dt*beta3*kappa*I/N);
    prob_S3[1] = exp(-dt*beta3*kappa*I/N);
    
    prob_I3[0] = 1 - exp(-dt*gamma);
    prob_I3[1] = exp(-dt*gamma);
    
    prob_R3[0] = 1 - exp(-dt*omega);
    prob_R3[1] = exp(-dt*omega);
    
    // Transition
    // B: S->I
    // C: I->R
    // F: Aging: (1)->(2)->(3)
    // E: R->S
    // D: Death
    //// Note: Here S_1, S_2... are all old value from (t-1)
    rmultinom(S1, &prob_S1, 3, &trans_S1); // B, F, S-B-F
    rmultinom(I1, &prob_I1, 3, &trans_I1); // C, F, I-C-F
    rmultinom(R1, &prob_R1, 3, &trans_R1); // E, F, R-E-F
    
    rmultinom(S2, &prob_S2, 3, &trans_S2); // B, F, S-B-F
    rmultinom(I2, &prob_I2, 3, &trans_I2); // C, F, I-C-F
    rmultinom(R2, &prob_R2, 3, &trans_R2); // E, F, R-E-F
    
    rmultinom(S3mD, &prob_S3, 2, &trans_S3); // B, (S-D)-B
    rmultinom(I3mD, &prob_I3, 2, &trans_I3); // C, (I-D)-C
    rmultinom(R3mD, &prob_R3, 2, &trans_R3); // E, (R-D)-E
    
    S1 = trans_S1[2] + trans_R1[0] + rpois(4*1025.7); // Include Birth
    I1 = trans_I1[2] + trans_S1[0];
    R1 = trans_R1[2] + trans_I1[0];
    
    S2 = trans_S2[2] + trans_R2[0] + trans_S1[1]; // Include Aging
    I2 = trans_I2[2] + trans_S2[0] + trans_I1[1];
    R2 = trans_R2[2] + trans_I2[0] + trans_R1[1];
    
    S3 = trans_S3[1] + trans_R3[0] + trans_S2[1]; // Include Aging
    I3 = trans_I3[1] + trans_S3[0] + trans_I2[1];
    R3 = trans_R3[1] + trans_I3[0] + trans_R2[1];
    
    //Accumvar
    H1 += trans_S1[0];
    H2 += trans_S2[0];
    H3 += trans_S3[0];
    
    q1 = -1; 
    while(q1 < 0 || q1 > 1){
      q1 = rnorm(0.07, sigma_q);
    }
    
    q2 = -1; 
    while(q2 < 0 || q2 > 1){
      q2 = rnorm(0.07, sigma_q);
    }
    
    q3 = -1; 
    while(q3 < 0 || q3 > 1){
      q3 = rnorm(0.07, sigma_q);
    }
")


# define parameters (without betas)
params_fixed <- c(gamma=1, delta1=0.003636364,delta2=1/(55*52), alpha=1/(78.86912*52), mu=0, N=82372825, omega=1/(1*52))
rinit <- Csnippet("
    S1=3876549;
    I1=30351;
    R1=1315221;
    S2=57139612;
    I2=871;
    R2=302852;
    S3=19573727;
    I3=2550;
    R3=131092;
    H1 = 0;
    H2 = 0;
    H3 = 0;
")

# Set to MLE
params_stocks_stst_mle <- params_fixed

params_stocks_stst_mle["beta1"] <- 12.74
params_stocks_stst_mle["beta2"] <- 0.21
params_stocks_stst_mle["beta3"] <- 0.31
params_stocks_stst_mle["phi"] <- 0.14
params_stocks_stst_mle["beta11"] <- 0.19
params_stocks_stst_mle["sigma_q"] <- 0.042

avg_1 <- c()
med_1 <- c()
var_1 <- c()
avg_2 <- c()
med_2 <- c()
var_2 <- c()
avg_3 <- c()
med_3 <- c()
var_3 <- c()
for(i in 1:1000){
  set.seed(123+765*i)
  sim1 <- simulate(t0=0,
                 times=c(1:416),
                 dmeasure = dmeas,
                 rmeasure = rmeas,
                 rprocess = discrete_time(rproc, delta.t = 1/4),
                 statenames = c("S1", "I1", "R1", "H1", 
                                "S2", "I2", "R2", "H2",
                                "S3", "I3", "R3", "H3",
                                "q1", "q2", "q3"),
                 obsnames=c("cases1","cases2","cases3"),
                 paramnames = names(params_stocks_stst_mle),
                 accumvars=c("H1", "H2", "H3"),
                 rinit=rinit,
                 params = params_stocks_stst_mle
                 )
  sim_data <- as.data.frame(sim1)
  #mean
  avg_1[i] <- sim_data$cases1 |> mean()
  avg_2[i] <- sim_data$cases2 |> mean()
  avg_3[i] <- sim_data$cases3 |> mean()
  #median
  med_1[i] <- sim_data$cases1 |> median()
  med_2[i] <- sim_data$cases2 |> median()
  med_3[i] <- sim_data$cases3 |> median()
  #variance
  var_1[i] <- sim_data$cases1 |> var()
  var_2[i] <- sim_data$cases2 |> var()
  var_3[i] <- sim_data$cases3 |> var()
}

sim_compare_pomp <- data.frame(avg_1,avg_2,avg_3,
                               med_1,med_2,med_3,
                               var_1,var_2,var_3)
write.csv(sim_compare_pomp, file = "sim_compare_pomp_EqOv.csv")
```

#### Compare - EqOv

```{r}
sim_compare <- read.csv("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/EqOv/Comparison/sim_compare_WWR_EqOv.csv", header = T)
sim_compare_pomp <- read.csv("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/EqOv/Comparison/sim_compare_pomp_EqOv.csv", header = T)
```

```{r}
(t.pvalue <- round(c(t.test(sim_compare$avg_1, sim_compare_pomp$avg_1)$p.value,
  t.test(sim_compare$avg_2, sim_compare_pomp$avg_2)$p.value,
  t.test(sim_compare$avg_3, sim_compare_pomp$avg_3)$p.value,
  t.test(sim_compare$med_1, sim_compare_pomp$med_1)$p.value,
  t.test(sim_compare$med_2, sim_compare_pomp$med_2)$p.value,
  t.test(sim_compare$med_3, sim_compare_pomp$med_3)$p.value,
  t.test(sim_compare$var_1, sim_compare_pomp$var_1)$p.value,
  t.test(sim_compare$var_2, sim_compare_pomp$var_2)$p.value,
  t.test(sim_compare$var_3, sim_compare_pomp$var_3)$p.value), digits=3))
```

```{r}
labx <- c("Mean Group 1 - EqOv","Mean Group 2 - EqOv","Mean Group 3 - EqOv",
  "Median Group 1 - EqOv","Median Group 2 - EqOv","Median Group 3 - EqOv",
  "Variance Group 1 - EqOv","Variance Group 2 - EqOv","Variance Group 3 - EqOv")
p.comparison <- list()
for(i in 1:9){
  x <- data.frame(wwr=sim_compare[,i+1],pomp=sim_compare_pomp[,i+1])
  data <- melt(x)
  p.comparison[[i]] <- ggplot(data,aes(x=value, fill=variable)) +     
    geom_density(alpha=0.25)+ labs(x = labx[i]) +
    ggtitle(paste("p = ", t.pvalue[i]))
}

pdf("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/EqOv/Comparison//compare_density_plot_EqOv.pdf",width=10,height=10)
plot <- ggarrange(p.comparison[[1]],p.comparison[[2]],p.comparison[[3]],
          p.comparison[[4]],p.comparison[[5]],p.comparison[[6]],
          p.comparison[[7]],p.comparison[[8]],p.comparison[[9]], 
          nrow=3, ncol=3)
annotate_figure(plot, top = text_grob("EqOv model: T-test with 1000 Simulations", color = "black", face = "bold", size = 14))
dev.off()

png("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/EqOv/Comparison//compare_density_plot_EqOv.png",width=800,height=800)
plot <- ggarrange(p.comparison[[1]],p.comparison[[2]],p.comparison[[3]],
          p.comparison[[4]],p.comparison[[5]],p.comparison[[6]],
          p.comparison[[7]],p.comparison[[8]],p.comparison[[9]], 
          nrow=3, ncol=3)
annotate_figure(plot, top = text_grob("EqOv model: T-test with 1000 Simulations", color = "black", face = "bold", size = 14))
dev.off()
```


#### Two random Simulation Plots + EqOv

```{r}
##### Pfilter + EqEq
rm(list = ls())     # clear objects  
graphics.off()      # close graphics windows
# measurement model 
# measurement model 
dmeas <- Csnippet("
                  if (ISNA(cases1)) {
                  lik = (give_log) ? 0 : 1;
                  } else {
                        lik =  dbinom(cases1, H1, q1, 1) +
                        dbinom(cases2, H2, q2, 1) +
                        dbinom(cases3, H3, q3, 1);
                      
                    lik = (give_log) ? lik : exp(lik);
                        
                    }")
rmeas <-  Csnippet("
                    cases1 = rbinom(H1, q1);
                    cases2 = rbinom(H2, q2);
                    cases3 = rbinom(H3, q3);
                  ")



rproc <- Csnippet("
    int I = I1 + I2 + I3;
    int trans_S1[3], trans_S2[3], trans_S3[2], trans_I1[3], trans_I2[3], trans_I3[2], trans_R1[3], trans_R2[3], trans_R3[2];
    
    double prob_S1[3],prob_I1[3],prob_R1[3],prob_S2[3],prob_I2[3],prob_R2[3],prob_S3[2],prob_I3[2],prob_R3[2];
    
    double kappa = (1 + beta11*cos(2*3.141593*t/52 + phi));
    
    // Define rate
    prob_S1[0] = 1-exp(-dt*beta1*kappa*I/N); // 0->1
    prob_S1[1] = 1-exp(-delta1*dt);
    prob_S1[2] = exp(-delta1*dt) + exp(-dt*beta1*kappa*I/N) - 1;
    
    prob_I1[0] = 1-exp(-gamma*dt);
    prob_I1[1] = 1-exp(-delta1*dt);
    prob_I1[2] = exp(-gamma*dt)+exp(-delta1*dt) - 1;
    
    prob_R1[0] = 1 - exp(-omega*dt);  // E_1,t this goes back to S_1,(t+1)
    prob_R1[1] = 1 - exp(-delta1*dt);
    prob_R1[2] = exp(-omega*dt) + exp(-delta1*dt) - 1;
    
    prob_S2[0] = 1-exp(-dt*beta2*kappa*I/N);
    prob_S2[1] = 1-exp(-delta2*dt);
    prob_S2[2] = exp(-delta2*dt) + exp(-dt*beta2*kappa*I/N) - 1;
    
    prob_I2[0] = 1-exp(-dt*gamma);
    prob_I2[1] = 1-exp(-dt*delta2);
    prob_I2[2] = exp(-dt*gamma)+exp(-dt*delta2) - 1;
    
    prob_R2[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R2[1] = 1 - exp(-dt*delta2);
    prob_R2[2] = exp(-dt*omega) + exp(-dt*delta2) - 1;
    
    // For Age Group (3): Die first before transition;
    
    int S3mD, I3mD, R3mD;
    
    S3mD = rbinom(S3, 1-dt*mu); 
    I3mD = rbinom(I3, 1-dt*mu);
    R3mD = rbinom(R3, 1-dt*mu);
    
    prob_S3[0] = 1-exp(-dt*beta3*kappa*I/N);
    prob_S3[1] = exp(-dt*beta3*kappa*I/N);
    
    prob_I3[0] = 1 - exp(-dt*gamma);
    prob_I3[1] = exp(-dt*gamma);
    
    prob_R3[0] = 1 - exp(-dt*omega);
    prob_R3[1] = exp(-dt*omega);
    
    // Transition
    // B: S->I
    // C: I->R
    // F: Aging: (1)->(2)->(3)
    // E: R->S
    // D: Death
    //// Note: Here S_1, S_2... are all old value from (t-1)
    rmultinom(S1, &prob_S1, 3, &trans_S1); // B, F, S-B-F
    rmultinom(I1, &prob_I1, 3, &trans_I1); // C, F, I-C-F
    rmultinom(R1, &prob_R1, 3, &trans_R1); // E, F, R-E-F
    
    rmultinom(S2, &prob_S2, 3, &trans_S2); // B, F, S-B-F
    rmultinom(I2, &prob_I2, 3, &trans_I2); // C, F, I-C-F
    rmultinom(R2, &prob_R2, 3, &trans_R2); // E, F, R-E-F
    
    rmultinom(S3mD, &prob_S3, 2, &trans_S3); // B, (S-D)-B
    rmultinom(I3mD, &prob_I3, 2, &trans_I3); // C, (I-D)-C
    rmultinom(R3mD, &prob_R3, 2, &trans_R3); // E, (R-D)-E
    
    S1 = trans_S1[2] + trans_R1[0] + rpois(4*1025.7); // Include Birth
    I1 = trans_I1[2] + trans_S1[0];
    R1 = trans_R1[2] + trans_I1[0];
    
    S2 = trans_S2[2] + trans_R2[0] + trans_S1[1]; // Include Aging
    I2 = trans_I2[2] + trans_S2[0] + trans_I1[1];
    R2 = trans_R2[2] + trans_I2[0] + trans_R1[1];
    
    S3 = trans_S3[1] + trans_R3[0] + trans_S2[1]; // Include Aging
    I3 = trans_I3[1] + trans_S3[0] + trans_I2[1];
    R3 = trans_R3[1] + trans_I3[0] + trans_R2[1];
    
    //Accumvar
    H1 += trans_S1[0];
    H2 += trans_S2[0];
    H3 += trans_S3[0];
    
    q1 = -1; 
    while(q1 < 0 || q1 > 1){
      q1 = rnorm(0.07, sigma_q);
    }
    
    q2 = -1; 
    while(q2 < 0 || q2 > 1){
      q2 = rnorm(0.07, sigma_q);
    }
    
    q3 = -1; 
    while(q3 < 0 || q3 > 1){
      q3 = rnorm(0.07, sigma_q);
    }
")


# define parameters (without betas)
params_fixed <- c(gamma=1, delta1=0.003636364,delta2=1/(55*52), alpha=1/(78.86912*52), mu=0, N=82372825, omega=1/(1*52))
rinit <- Csnippet("
    S1=3876549;
    I1=30351;
    R1=1315221;
    S2=57139612;
    I2=871;
    R2=302852;
    S3=19573727;
    I3=2550;
    R3=131092;
    H1 = 0;
    H2 = 0;
    H3 = 0;
")

# Set to MLE
params_stocks_stst_mle <- params_fixed

params_stocks_stst_mle["beta1"] <- 12.74
params_stocks_stst_mle["beta2"] <- 0.21
params_stocks_stst_mle["beta3"] <- 0.31
params_stocks_stst_mle["phi"] <- 0.14
params_stocks_stst_mle["beta11"] <- 0.19
params_stocks_stst_mle["sigma_q"] <- 0.042


set.seed(1928475)
### Simulation
sim1 <- simulate(t0=0,
                 times=c(1:416),
                 dmeasure = dmeas,
                 rmeasure = rmeas,
                 rprocess = discrete_time(rproc, delta.t = 1/4),
                 statenames = c("S1", "I1", "R1", "H1", 
                                "S2", "I2", "R2", "H2",
                                "S3", "I3", "R3", "H3",
                                "q1", "q2", "q3"),
                 obsnames=c("cases1","cases2","cases3"),
                 paramnames = names(params_stocks_stst_mle),
                 accumvars=c("H1", "H2", "H3"),
                 rinit=rinit,
                 params = params_stocks_stst_mle
                 )

sim_data <- as.data.frame(sim1)

p_EqOv_pomp <- ggplot(data=sim_data) + 
  geom_line(aes(x=time, y=cases1),color='green') +
  geom_line(aes(x=time, y=cases2), color='red') +
  geom_line(aes(x=time, y=cases3), color='blue') +
  ylab('Y_sim_pomp')+xlab('date')

pdf("two_random_simplots_EqOv.pdf", height=5,width=10)
plot <- ggarrange(p_EqOv_pomp, p_EqOv_WWR, nrow=1)
annotate_figure(plot, top = text_grob("Two random simulations from EqOv pomp & EqOv WWR", color = "black", face = "bold", size = 20))
dev.off()
```


#### *WWR* rinit + dt=1/4 + *WWR* rproc + OvOv

```{r}
# measurement model 
dmeas <- Csnippet("
                  if (ISNA(cases1)) {
                  lik = (give_log) ? 0 : 1;
                  } else {
                        lik =  dbinom(cases1, H1, q1, 1) +
                        dbinom(cases2, H2, q2, 1) +
                        dbinom(cases3, H3, q3, 1);
                      
                    lik = (give_log) ? lik : exp(lik);
                        
                    }")
rmeas <-  Csnippet("
                    cases1 = rbinom(H1, q1);
                    cases2 = rbinom(H2, q2);
                    cases3 = rbinom(H3, q3);
                  ")



rproc <- Csnippet("
    int I = I1 + I2 + I3;
    int trans_S1[3], trans_S2[3], trans_S3[2], trans_I1[3], trans_I2[3], trans_I3[2], trans_R1[3], trans_R2[3], trans_R3[2];
    
    double prob_S1[3],prob_I1[3],prob_R1[3],prob_S2[3],prob_I2[3],prob_R2[3],prob_S3[2],prob_I3[2],prob_R3[2];
    
    double xi = rgamma(sigma_xi, 1/sigma_xi);
    
    double kappa = (1 + beta11*cos(2*3.141593*t/52 + phi)) * xi;
    
    // Define rate
    prob_S1[0] = 1-exp(-dt*beta1*kappa*I/N); // 0->1
    prob_S1[1] = 1-exp(-delta1*dt);
    prob_S1[2] = exp(-delta1*dt) + exp(-dt*beta1*kappa*I/N) - 1;
    
    prob_I1[0] = 1-exp(-gamma*dt);
    prob_I1[1] = 1-exp(-delta1*dt);
    prob_I1[2] = exp(-gamma*dt)+exp(-delta1*dt) - 1;
    
    prob_R1[0] = 1 - exp(-omega*dt);  // E_1,t this goes back to S_1,(t+1)
    prob_R1[1] = 1 - exp(-delta1*dt);
    prob_R1[2] = exp(-omega*dt) + exp(-delta1*dt) - 1;
    
    prob_S2[0] = 1-exp(-dt*beta2*kappa*I/N);
    prob_S2[1] = 1-exp(-delta2*dt);
    prob_S2[2] = exp(-delta2*dt) + exp(-dt*beta2*kappa*I/N) - 1;
    
    prob_I2[0] = 1-exp(-dt*gamma);
    prob_I2[1] = 1-exp(-dt*delta2);
    prob_I2[2] = exp(-dt*gamma)+exp(-dt*delta2) - 1;
    
    prob_R2[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R2[1] = 1 - exp(-dt*delta2);
    prob_R2[2] = exp(-dt*omega) + exp(-dt*delta2) - 1;
    
    // For Age Group (3): Die first before transition;
    
    int S3mD, I3mD, R3mD;
    
    S3mD = rbinom(S3, 1-dt*mu); 
    I3mD = rbinom(I3, 1-dt*mu);
    R3mD = rbinom(R3, 1-dt*mu);
    
    prob_S3[0] = 1-exp(-dt*beta3*kappa*I/N);
    prob_S3[1] = exp(-dt*beta3*kappa*I/N);
    
    prob_I3[0] = 1 - exp(-dt*gamma);
    prob_I3[1] = exp(-dt*gamma);
    
    prob_R3[0] = 1 - exp(-dt*omega);
    prob_R3[1] = exp(-dt*omega);
    
    // Transition
    // B: S->I
    // C: I->R
    // F: Aging: (1)->(2)->(3)
    // E: R->S
    // D: Death
    //// Note: Here S_1, S_2... are all old value from (t-1)
    rmultinom(S1, &prob_S1, 3, &trans_S1); // B, F, S-B-F
    rmultinom(I1, &prob_I1, 3, &trans_I1); // C, F, I-C-F
    rmultinom(R1, &prob_R1, 3, &trans_R1); // E, F, R-E-F
    
    rmultinom(S2, &prob_S2, 3, &trans_S2); // B, F, S-B-F
    rmultinom(I2, &prob_I2, 3, &trans_I2); // C, F, I-C-F
    rmultinom(R2, &prob_R2, 3, &trans_R2); // E, F, R-E-F
    
    rmultinom(S3mD, &prob_S3, 2, &trans_S3); // B, (S-D)-B
    rmultinom(I3mD, &prob_I3, 2, &trans_I3); // C, (I-D)-C
    rmultinom(R3mD, &prob_R3, 2, &trans_R3); // E, (R-D)-E
    
    S1 = trans_S1[2] + trans_R1[0] + rpois(4*1025.7); // Include Birth
    I1 = trans_I1[2] + trans_S1[0];
    R1 = trans_R1[2] + trans_I1[0];
    
    S2 = trans_S2[2] + trans_R2[0] + trans_S1[1]; // Include Aging
    I2 = trans_I2[2] + trans_S2[0] + trans_I1[1];
    R2 = trans_R2[2] + trans_I2[0] + trans_R1[1];
    
    S3 = trans_S3[1] + trans_R3[0] + trans_S2[1]; // Include Aging
    I3 = trans_I3[1] + trans_S3[0] + trans_I2[1];
    R3 = trans_R3[1] + trans_I3[0] + trans_R2[1];
    
    //Accumvar
    H1 += trans_S1[0];
    H2 += trans_S2[0];
    H3 += trans_S3[0];
    
    q1 = -1; 
    while(q1 < 0 || q1 > 1){
      q1 = rnorm(0.07, sigma_q);
    }
    
    q2 = -1; 
    while(q2 < 0 || q2 > 1){
      q2 = rnorm(0.07, sigma_q);
    }
    
    q3 = -1; 
    while(q3 < 0 || q3 > 1){
      q3 = rnorm(0.07, sigma_q);
    }
")


# define parameters (without betas)
params_fixed <- c(gamma=1, delta1=0.003636364,delta2=1/(55*52), alpha=1/(78.86912*52), mu=0, N=82372825, omega=1/(1*52))
rinit <- Csnippet("
    S1=3876549;
    I1=30351;
    R1=1315221;
    S2=57139612;
    I2=871;
    R2=302852;
    S3=19573727;
    I3=2550;
    R3=131092;
    H1 = 0;
    H2 = 0;
    H3 = 0;
")

# Set to MLE
params_stocks_stst_mle <- params_fixed

params_stocks_stst_mle["beta1"] <- 11.48
params_stocks_stst_mle["beta2"] <- 0.25
params_stocks_stst_mle["beta3"] <- 0.35
params_stocks_stst_mle["phi"] <- 0.14
params_stocks_stst_mle["beta11"] <- 0.16
params_stocks_stst_mle["sigma_q"] <- 0.021
params_stocks_stst_mle["sigma_xi"] <- 66.89

avg_1 <- c()
med_1 <- c()
var_1 <- c()
avg_2 <- c()
med_2 <- c()
var_2 <- c()
avg_3 <- c()
med_3 <- c()
var_3 <- c()
for(i in 1:1000){
  set.seed(123+765*i)
  sim1 <- simulate(t0=0,
                 times=c(1:416),
                 dmeasure = dmeas,
                 rmeasure = rmeas,
                 rprocess = discrete_time(rproc, delta.t = 1/4),
                 statenames = c("S1", "I1", "R1", "H1", 
                                "S2", "I2", "R2", "H2",
                                "S3", "I3", "R3", "H3",
                                "q1", "q2", "q3"),
                 obsnames=c("cases1","cases2","cases3"),
                 paramnames = names(params_stocks_stst_mle),
                 accumvars=c("H1", "H2", "H3"),
                 rinit=rinit,
                 params = params_stocks_stst_mle
                 )
  sim_data <- as.data.frame(sim1)
  #mean
  avg_1[i] <- sim_data$cases1 |> mean()
  avg_2[i] <- sim_data$cases2 |> mean()
  avg_3[i] <- sim_data$cases3 |> mean()
  #median
  med_1[i] <- sim_data$cases1 |> median()
  med_2[i] <- sim_data$cases2 |> median()
  med_3[i] <- sim_data$cases3 |> median()
  #variance
  var_1[i] <- sim_data$cases1 |> var()
  var_2[i] <- sim_data$cases2 |> var()
  var_3[i] <- sim_data$cases3 |> var()
}

sim_compare_pomp <- data.frame(avg_1,avg_2,avg_3,
                               med_1,med_2,med_3,
                               var_1,var_2,var_3)
write.csv(sim_compare_pomp, file = "sim_compare_pomp_OvOv.csv")
```

#### Compare - OvOv

```{r}
sim_compare <- read.csv("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/OvOv/Comparison/sim_compare_WWR.csv", header = T)
sim_compare_pomp <- read.csv("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/OvOv/Comparison/sim_compare_pomp.csv", header = T)
```

```{r}
(t.pvalue <- round(c(t.test(sim_compare$avg_1, sim_compare_pomp$avg_1)$p.value,
  t.test(sim_compare$avg_2, sim_compare_pomp$avg_2)$p.value,
  t.test(sim_compare$avg_3, sim_compare_pomp$avg_3)$p.value,
  t.test(sim_compare$med_1, sim_compare_pomp$med_1)$p.value,
  t.test(sim_compare$med_2, sim_compare_pomp$med_2)$p.value,
  t.test(sim_compare$med_3, sim_compare_pomp$med_3)$p.value,
  t.test(sim_compare$var_1, sim_compare_pomp$var_1)$p.value,
  t.test(sim_compare$var_2, sim_compare_pomp$var_2)$p.value,
  t.test(sim_compare$var_3, sim_compare_pomp$var_3)$p.value), digits=3))
```

```{r}
labx <- c("Mean Group 1 - OvOv","Mean Group 2 - OvOv","Mean Group 3 - OvOv",
  "Median Group 1 - OvOv","Median Group 2 - OvOv","Median Group 3 - OvOv",
  "Variance Group 1 - OvOv","Variance Group 2 - OvOv","Variance Group 3 - OvOv")
p.comparison <- list()
for(i in 1:9){
  x <- data.frame(wwr=sim_compare[,i+1],pomp=sim_compare_pomp[,i+1])
  data <- melt(x)
  p.comparison[[i]] <- ggplot(data,aes(x=value, fill=variable)) +     
    geom_density(alpha=0.25)+ labs(x = labx[i]) +
    ggtitle(paste("p = ", t.pvalue[i]))
}

pdf("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/OvOv/Comparison/compare_density_plot_OvOv.pdf",width=10,height=10)
plot <- ggarrange(p.comparison[[1]],p.comparison[[2]],p.comparison[[3]],
          p.comparison[[4]],p.comparison[[5]],p.comparison[[6]],
          p.comparison[[7]],p.comparison[[8]],p.comparison[[9]], 
          nrow=3, ncol=3)
annotate_figure(plot, top = text_grob("OvOv model: T-test with 1000 Simulations", color = "black", face = "bold", size = 14))
dev.off()

png("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/OvOv/Comparison/compare_density_plot_OvOv.png",width=800,height=800)
plot <- ggarrange(p.comparison[[1]],p.comparison[[2]],p.comparison[[3]],
          p.comparison[[4]],p.comparison[[5]],p.comparison[[6]],
          p.comparison[[7]],p.comparison[[8]],p.comparison[[9]], 
          nrow=3, ncol=3)
annotate_figure(plot, top = text_grob("OvOv model: T-test with 1000 Simulations", color = "black", face = "bold", size = 14))
dev.off()
```


#### Two random Simulation Plots + OvOv

```{r}
##### Pfilter + EqEq
rm(list = ls())     # clear objects  
graphics.off()      # close graphics windows
# measurement model 
dmeas <- Csnippet("
                  if (ISNA(cases1)) {
                  lik = (give_log) ? 0 : 1;
                  } else {
                        lik =  dbinom(cases1, H1, q1, 1) +
                        dbinom(cases2, H2, q2, 1) +
                        dbinom(cases3, H3, q3, 1);
                      
                    lik = (give_log) ? lik : exp(lik);
                        
                    }")
rmeas <-  Csnippet("
                    cases1 = rbinom(H1, q1);
                    cases2 = rbinom(H2, q2);
                    cases3 = rbinom(H3, q3);
                  ")



rproc <- Csnippet("
    int I = I1 + I2 + I3;
    int trans_S1[3], trans_S2[3], trans_S3[2], trans_I1[3], trans_I2[3], trans_I3[2], trans_R1[3], trans_R2[3], trans_R3[2];
    
    double prob_S1[3],prob_I1[3],prob_R1[3],prob_S2[3],prob_I2[3],prob_R2[3],prob_S3[2],prob_I3[2],prob_R3[2];
    
    double xi = rgamma(sigma_xi, 1/sigma_xi);
    
    double kappa = (1 + beta11*cos(2*3.141593*t/52 + phi)) * xi;
    
    // Define rate
    prob_S1[0] = 1-exp(-dt*beta1*kappa*I/N); // 0->1
    prob_S1[1] = 1-exp(-delta1*dt);
    prob_S1[2] = exp(-delta1*dt) + exp(-dt*beta1*kappa*I/N) - 1;
    
    prob_I1[0] = 1-exp(-gamma*dt);
    prob_I1[1] = 1-exp(-delta1*dt);
    prob_I1[2] = exp(-gamma*dt)+exp(-delta1*dt) - 1;
    
    prob_R1[0] = 1 - exp(-omega*dt);  // E_1,t this goes back to S_1,(t+1)
    prob_R1[1] = 1 - exp(-delta1*dt);
    prob_R1[2] = exp(-omega*dt) + exp(-delta1*dt) - 1;
    
    prob_S2[0] = 1-exp(-dt*beta2*kappa*I/N);
    prob_S2[1] = 1-exp(-delta2*dt);
    prob_S2[2] = exp(-delta2*dt) + exp(-dt*beta2*kappa*I/N) - 1;
    
    prob_I2[0] = 1-exp(-dt*gamma);
    prob_I2[1] = 1-exp(-dt*delta2);
    prob_I2[2] = exp(-dt*gamma)+exp(-dt*delta2) - 1;
    
    prob_R2[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R2[1] = 1 - exp(-dt*delta2);
    prob_R2[2] = exp(-dt*omega) + exp(-dt*delta2) - 1;
    
    // For Age Group (3): Die first before transition;
    
    int S3mD, I3mD, R3mD;
    
    S3mD = rbinom(S3, 1-dt*mu); 
    I3mD = rbinom(I3, 1-dt*mu);
    R3mD = rbinom(R3, 1-dt*mu);
    
    prob_S3[0] = 1-exp(-dt*beta3*kappa*I/N);
    prob_S3[1] = exp(-dt*beta3*kappa*I/N);
    
    prob_I3[0] = 1 - exp(-dt*gamma);
    prob_I3[1] = exp(-dt*gamma);
    
    prob_R3[0] = 1 - exp(-dt*omega);
    prob_R3[1] = exp(-dt*omega);
    
    // Transition
    // B: S->I
    // C: I->R
    // F: Aging: (1)->(2)->(3)
    // E: R->S
    // D: Death
    //// Note: Here S_1, S_2... are all old value from (t-1)
    rmultinom(S1, &prob_S1, 3, &trans_S1); // B, F, S-B-F
    rmultinom(I1, &prob_I1, 3, &trans_I1); // C, F, I-C-F
    rmultinom(R1, &prob_R1, 3, &trans_R1); // E, F, R-E-F
    
    rmultinom(S2, &prob_S2, 3, &trans_S2); // B, F, S-B-F
    rmultinom(I2, &prob_I2, 3, &trans_I2); // C, F, I-C-F
    rmultinom(R2, &prob_R2, 3, &trans_R2); // E, F, R-E-F
    
    rmultinom(S3mD, &prob_S3, 2, &trans_S3); // B, (S-D)-B
    rmultinom(I3mD, &prob_I3, 2, &trans_I3); // C, (I-D)-C
    rmultinom(R3mD, &prob_R3, 2, &trans_R3); // E, (R-D)-E
    
    S1 = trans_S1[2] + trans_R1[0] + rpois(4*1025.7); // Include Birth
    I1 = trans_I1[2] + trans_S1[0];
    R1 = trans_R1[2] + trans_I1[0];
    
    S2 = trans_S2[2] + trans_R2[0] + trans_S1[1]; // Include Aging
    I2 = trans_I2[2] + trans_S2[0] + trans_I1[1];
    R2 = trans_R2[2] + trans_I2[0] + trans_R1[1];
    
    S3 = trans_S3[1] + trans_R3[0] + trans_S2[1]; // Include Aging
    I3 = trans_I3[1] + trans_S3[0] + trans_I2[1];
    R3 = trans_R3[1] + trans_I3[0] + trans_R2[1];
    
    //Accumvar
    H1 += trans_S1[0];
    H2 += trans_S2[0];
    H3 += trans_S3[0];
    
    q1 = -1; 
    while(q1 < 0 || q1 > 1){
      q1 = rnorm(0.07, sigma_q);
    }
    
    q2 = -1; 
    while(q2 < 0 || q2 > 1){
      q2 = rnorm(0.07, sigma_q);
    }
    
    q3 = -1; 
    while(q3 < 0 || q3 > 1){
      q3 = rnorm(0.07, sigma_q);
    }
")


# define parameters (without betas)
params_fixed <- c(gamma=1, delta1=0.003636364,delta2=1/(55*52), alpha=1/(78.86912*52), mu=0, N=82372825, omega=1/(1*52))
rinit <- Csnippet("
    S1=3876549;
    I1=30351;
    R1=1315221;
    S2=57139612;
    I2=871;
    R2=302852;
    S3=19573727;
    I3=2550;
    R3=131092;
    H1 = 0;
    H2 = 0;
    H3 = 0;
")

# Set to MLE
params_stocks_stst_mle <- params_fixed

params_stocks_stst_mle["beta1"] <- 11.48
params_stocks_stst_mle["beta2"] <- 0.25
params_stocks_stst_mle["beta3"] <- 0.35
params_stocks_stst_mle["phi"] <- 0.14
params_stocks_stst_mle["beta11"] <- 0.16
params_stocks_stst_mle["sigma_q"] <- 0.021
params_stocks_stst_mle["sigma_xi"] <- 66.89


set.seed(1928475)
### Simulation
sim1 <- simulate(t0=0,
                 times=c(1:416),
                 dmeasure = dmeas,
                 rmeasure = rmeas,
                 rprocess = discrete_time(rproc, delta.t = 1/4),
                 statenames = c("S1", "I1", "R1", "H1", 
                                "S2", "I2", "R2", "H2",
                                "S3", "I3", "R3", "H3",
                                "q1", "q2", "q3"),
                 obsnames=c("cases1","cases2","cases3"),
                 paramnames = names(params_stocks_stst_mle),
                 accumvars=c("H1", "H2", "H3"),
                 rinit=rinit,
                 params = params_stocks_stst_mle
                 )

sim_data <- as.data.frame(sim1)

p_OvOv_pomp <- ggplot(data=sim_data) + 
  geom_line(aes(x=time, y=cases1),color='green') +
  geom_line(aes(x=time, y=cases2), color='red') +
  geom_line(aes(x=time, y=cases3), color='blue') +
  ylab('Y_sim_pomp')+xlab('date')

pdf("two_random_simplots_OvOv.pdf", height=5,width=10)
plot <- ggarrange(p_OvOv_pomp, p_OvOv_WWR, nrow=1)
annotate_figure(plot, top = text_grob("Two random simulations from OvOv pomp & OvOv WWR", color = "black", face = "bold", size = 20))
dev.off()
```

##### Pfilter

#### Pfilter + EqEq + old

```{r}
# measurement model 
dmeas <- Csnippet("
                  if (ISNA(cases1)) {
                  lik = (give_log) ? 0 : 1;
                  } else {
                        lik =  dbinom(cases1, H1, 0.07, 1) +
                        dbinom(cases2, H2, 0.07, 1) +
                        dbinom(cases3, H3, 0.07, 1);
                      
                    lik = (give_log) ? lik : exp(lik);
                        
                    }")
rmeas <-  Csnippet("
                    cases1 = rbinom(H1, 0.07);
                    cases2 = rbinom(H2, 0.07);
                    cases3 = rbinom(H3, 0.07);
                  ")



rproc <- Csnippet("
    int I = I1 + I2 + I3;
    int trans_S1[3], trans_S2[3], trans_S3[2], trans_I1[3], trans_I2[3], trans_I3[2], trans_R1[3], trans_R2[3], trans_R3[2];
    
    double prob_S1[3],prob_I1[3],prob_R1[3],prob_S2[3],prob_I2[3],prob_R2[3],prob_S3[2],prob_I3[2],prob_R3[2];
    
    double kappa = (1 + beta11*cos(2*3.141593*t/52 + phi));
    
    // Define rate
    prob_S1[0] = 1-exp(-dt*beta1*kappa*I/N); // 0->1
    prob_S1[1] = 1-exp(-delta1*dt);
    prob_S1[2] = exp(-delta1*dt) + exp(-dt*beta1*kappa*I/N) - 1;
    
    prob_I1[0] = 1-exp(-gamma*dt);
    prob_I1[1] = 1-exp(-delta1*dt);
    prob_I1[2] = exp(-gamma*dt)+exp(-delta1*dt) - 1;
    
    prob_R1[0] = 1 - exp(-omega*dt);  // E_1,t this goes back to S_1,(t+1)
    prob_R1[1] = 1 - exp(-delta1*dt);
    prob_R1[2] = exp(-omega*dt) + exp(-delta1*dt) - 1;
    
    prob_S2[0] = 1-exp(-dt*beta2*kappa*I/N);
    prob_S2[1] = 1-exp(-delta2*dt);
    prob_S2[2] = exp(-delta2*dt) + exp(-dt*beta2*kappa*I/N) - 1;
    
    prob_I2[0] = 1-exp(-dt*gamma);
    prob_I2[1] = 1-exp(-dt*delta2);
    prob_I2[2] = exp(-dt*gamma)+exp(-dt*delta2) - 1;
    
    prob_R2[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R2[1] = 1 - exp(-dt*delta2);
    prob_R2[2] = exp(-dt*omega) + exp(-dt*delta2) - 1;
    
    // For Age Group (3): Die first before transition;
    
    int S3mD, I3mD, R3mD;
    
    S3mD = rbinom(S3, 1-dt*mu); 
    I3mD = rbinom(I3, 1-dt*mu);
    R3mD = rbinom(R3, 1-dt*mu);
    
    prob_S3[0] = 1-exp(-dt*beta3*kappa*I/N);
    prob_S3[1] = exp(-dt*beta3*kappa*I/N);
    
    prob_I3[0] = 1 - exp(-dt*gamma);
    prob_I3[1] = exp(-dt*gamma);
    
    prob_R3[0] = 1 - exp(-dt*omega);
    prob_R3[1] = exp(-dt*omega);
    
    // Transition
    // B: S->I
    // C: I->R
    // F: Aging: (1)->(2)->(3)
    // E: R->S
    // D: Death
    //// Note: Here S_1, S_2... are all old value from (t-1)
    rmultinom(S1, &prob_S1, 3, &trans_S1); // B, F, S-B-F
    rmultinom(I1, &prob_I1, 3, &trans_I1); // C, F, I-C-F
    rmultinom(R1, &prob_R1, 3, &trans_R1); // E, F, R-E-F
    
    rmultinom(S2, &prob_S2, 3, &trans_S2); // B, F, S-B-F
    rmultinom(I2, &prob_I2, 3, &trans_I2); // C, F, I-C-F
    rmultinom(R2, &prob_R2, 3, &trans_R2); // E, F, R-E-F
    
    rmultinom(S3mD, &prob_S3, 2, &trans_S3); // B, (S-D)-B
    rmultinom(I3mD, &prob_I3, 2, &trans_I3); // C, (I-D)-C
    rmultinom(R3mD, &prob_R3, 2, &trans_R3); // E, (R-D)-E
    
    S1 = trans_S1[2] + trans_R1[0] + rpois(4*1025.7); // Include Birth
    I1 = trans_I1[2] + trans_S1[0];
    R1 = trans_R1[2] + trans_I1[0];
    
    S2 = trans_S2[2] + trans_R2[0] + trans_S1[1]; // Include Aging
    I2 = trans_I2[2] + trans_S2[0] + trans_I1[1];
    R2 = trans_R2[2] + trans_I2[0] + trans_R1[1];
    
    S3 = trans_S3[1] + trans_R3[0] + trans_S2[1]; // Include Aging
    I3 = trans_I3[1] + trans_S3[0] + trans_I2[1];
    R3 = trans_R3[1] + trans_I3[0] + trans_R2[1];
    
    //Accumvar
    H1 += trans_S1[0];
    H2 += trans_S2[0];
    H3 += trans_S3[0];
")


# define parameters (without betas)
params_fixed <- c(gamma=1, delta1=0.003636364,delta2=1/(55*52), alpha=1/(78.86912*52), mu=0, N=82372825, omega=1/(1*52))
rinit <- Csnippet("
    S1=3876549;
    I1=30351;
    R1=1315221;
    S2=57139612;
    I2=871;
    R2=302852;
    S3=19573727;
    I3=2550;
    R3=131092;
    H1 = 0;
    H2 = 0;
    H3 = 0;
")

# Set to MLE
params_stocks_stst_mle <- params_fixed

params_stocks_stst_mle["beta1"] <- 12.15
params_stocks_stst_mle["beta2"] <- 0.22
params_stocks_stst_mle["beta3"] <- 0.34
params_stocks_stst_mle["phi"] <- 0.017
params_stocks_stst_mle["beta11"] <- 0.022
```

```{r}
library(doParallel)
library(future)
load("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/real_rotavirus_metadata.Rdata")
dat <- data.frame(time=c(1:416), realdat)

dat |>
  pomp(t0=0,
    time="time",
    rprocess=discrete_time(rproc,delta.t=1/4), ## Obs time every week, but delta.t transition is actually everyday
    rinit=rinit,
    dmeasure=dmeas,
    rmeasure=rmeas,
    accumvars=c("H1","H2","H3"),
    statenames=c("S1","S2","S3",
                 "I1","I2","I3",
                 "R1","R2","R3",
                 "H1","H2","H3"),
    paramnames = names(params_stocks_stst_mle)
  ) -> m1

theta <- params_stocks_stst_mle

plan(multicore)
foreach(i=1:4, .combine=c,
  .options.future=list(seed=998468235L)
) %dopar% {
  pfilter(m1,Np=5000,params=theta)
} -> pfs

logmeanexp(logLik(pfs),se=TRUE)
```


#### Pfilter + OvOv

```{r}
# measurement model 
dmeas <- Csnippet("
                  if (ISNA(cases1)) {
                  lik = (give_log) ? 0 : 1;
                  } else {
                        lik =  dbinom(cases1, H1, q1, 1) +
                        dbinom(cases2, H2, q2, 1) +
                        dbinom(cases3, H3, q3, 1);
                      
                    lik = (give_log) ? lik : exp(lik);
                        
                    }")
rmeas <-  Csnippet("
                    cases1 = rbinom(H1, q1);
                    cases2 = rbinom(H2, q2);
                    cases3 = rbinom(H3, q3);
                  ")



rproc <- Csnippet("
    int I = I1 + I2 + I3;
    int trans_S1[3], trans_S2[3], trans_S3[2], trans_I1[3], trans_I2[3], trans_I3[2], trans_R1[3], trans_R2[3], trans_R3[2];
    
    double prob_S1[3],prob_I1[3],prob_R1[3],prob_S2[3],prob_I2[3],prob_R2[3],prob_S3[2],prob_I3[2],prob_R3[2];
    
    double xi = rgamma(sigma_xi, 1/sigma_xi);
    
    double kappa = (1 + beta11*cos(2*3.141593*t/52 + phi)) * xi;
    
    // Define rate
    prob_S1[0] = 1-exp(-dt*beta1*kappa*I/N); // 0->1
    prob_S1[1] = 1-exp(-delta1*dt);
    prob_S1[2] = exp(-delta1*dt) + exp(-dt*beta1*kappa*I/N) - 1;
    
    prob_I1[0] = 1-exp(-gamma*dt);
    prob_I1[1] = 1-exp(-delta1*dt);
    prob_I1[2] = exp(-gamma*dt)+exp(-delta1*dt) - 1;
    
    prob_R1[0] = 1 - exp(-omega*dt);  // E_1,t this goes back to S_1,(t+1)
    prob_R1[1] = 1 - exp(-delta1*dt);
    prob_R1[2] = exp(-omega*dt) + exp(-delta1*dt) - 1;
    
    prob_S2[0] = 1-exp(-dt*beta2*kappa*I/N);
    prob_S2[1] = 1-exp(-delta2*dt);
    prob_S2[2] = exp(-delta2*dt) + exp(-dt*beta2*kappa*I/N) - 1;
    
    prob_I2[0] = 1-exp(-dt*gamma);
    prob_I2[1] = 1-exp(-dt*delta2);
    prob_I2[2] = exp(-dt*gamma)+exp(-dt*delta2) - 1;
    
    prob_R2[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R2[1] = 1 - exp(-dt*delta2);
    prob_R2[2] = exp(-dt*omega) + exp(-dt*delta2) - 1;
    
    // For Age Group (3): Die first before transition;
    
    int S3mD, I3mD, R3mD;
    
    S3mD = rbinom(S3, 1-dt*mu); 
    I3mD = rbinom(I3, 1-dt*mu);
    R3mD = rbinom(R3, 1-dt*mu);
    
    prob_S3[0] = 1-exp(-dt*beta3*kappa*I/N);
    prob_S3[1] = exp(-dt*beta3*kappa*I/N);
    
    prob_I3[0] = 1 - exp(-dt*gamma);
    prob_I3[1] = exp(-dt*gamma);
    
    prob_R3[0] = 1 - exp(-dt*omega);
    prob_R3[1] = exp(-dt*omega);
    
    // Transition
    // B: S->I
    // C: I->R
    // F: Aging: (1)->(2)->(3)
    // E: R->S
    // D: Death
    //// Note: Here S_1, S_2... are all old value from (t-1)
    rmultinom(S1, &prob_S1, 3, &trans_S1); // B, F, S-B-F
    rmultinom(I1, &prob_I1, 3, &trans_I1); // C, F, I-C-F
    rmultinom(R1, &prob_R1, 3, &trans_R1); // E, F, R-E-F
    
    rmultinom(S2, &prob_S2, 3, &trans_S2); // B, F, S-B-F
    rmultinom(I2, &prob_I2, 3, &trans_I2); // C, F, I-C-F
    rmultinom(R2, &prob_R2, 3, &trans_R2); // E, F, R-E-F
    
    rmultinom(S3mD, &prob_S3, 2, &trans_S3); // B, (S-D)-B
    rmultinom(I3mD, &prob_I3, 2, &trans_I3); // C, (I-D)-C
    rmultinom(R3mD, &prob_R3, 2, &trans_R3); // E, (R-D)-E
    
    S1 = trans_S1[2] + trans_R1[0] + rpois(4*1025.7); // Include Birth
    I1 = trans_I1[2] + trans_S1[0];
    R1 = trans_R1[2] + trans_I1[0];
    
    S2 = trans_S2[2] + trans_R2[0] + trans_S1[1]; // Include Aging
    I2 = trans_I2[2] + trans_S2[0] + trans_I1[1];
    R2 = trans_R2[2] + trans_I2[0] + trans_R1[1];
    
    S3 = trans_S3[1] + trans_R3[0] + trans_S2[1]; // Include Aging
    I3 = trans_I3[1] + trans_S3[0] + trans_I2[1];
    R3 = trans_R3[1] + trans_I3[0] + trans_R2[1];
    
    //Accumvar
    H1 += trans_S1[0];
    H2 += trans_S2[0];
    H3 += trans_S3[0];
    
    q1 = -1; 
    while(q1 < 0 || q1 > 1){
      q1 = rnorm(0.07, sigma_q);
    }
    
    q2 = -1; 
    while(q2 < 0 || q2 > 1){
      q2 = rnorm(0.07, sigma_q);
    }
    
    q3 = -1; 
    while(q3 < 0 || q3 > 1){
      q3 = rnorm(0.07, sigma_q);
    }
")


# define parameters (without betas)
params_fixed <- c(gamma=1, delta1=0.003636364,delta2=1/(55*52), alpha=1/(78.86912*52), mu=0, N=82372825, omega=1/(1*52))
rinit <- Csnippet("
    S1=3876549;
    I1=30351;
    R1=1315221;
    S2=57139612;
    I2=871;
    R2=302852;
    S3=19573727;
    I3=2550;
    R3=131092;
    H1 = 0;
    H2 = 0;
    H3 = 0;
")

# Set to MLE
params_stocks_stst_mle <- params_fixed

params_stocks_stst_mle["beta1"] <- 11.48
params_stocks_stst_mle["beta2"] <- 0.25
params_stocks_stst_mle["beta3"] <- 0.35
params_stocks_stst_mle["phi"] <- 0.14
params_stocks_stst_mle["beta11"] <- 0.16
params_stocks_stst_mle["sigma_q"] <- 0.021
params_stocks_stst_mle["sigma_xi"] <- 66.89
```

```{r}
library(doParallel)
library(future)
load("data/real_rotavirus_metadata.Rdata")
dat <- data.frame(time=c(1:416), realdat)

dat |>
  pomp(t0=0,
    time="time",
    rprocess=discrete_time(rproc,delta.t=1/4), ## Obs time every week, but delta.t transition is actually everyday
    rinit=rinit,
    dmeasure=dmeas,
    rmeasure=rmeas,
    accumvars=c("H1","H2","H3"),
    statenames=c("S1","S2","S3",
                 "I1","I2","I3",
                 "R1","R2","R3",
                 "H1","H2","H3",
                 "q1","q2","q3"),
    paramnames = names(params_stocks_stst_mle)
  ) -> m1

theta <- params_stocks_stst_mle

plan(multicore)
foreach(i=1:4, .combine=c,
  .options.future=list(seed=998468235L)
) %dopar% {
  pfilter(m1,Np=5000,params=theta)
} -> pfs

logmeanexp(logLik(pfs),se=TRUE)
```