---
title: "compare_sim_200_plot"
author: "Yize Hao"
date: "2024-04-07"
output: html_document
---


```{r}
load("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Greatlake_results/pfilter_results/wwr_100_ovov.Rdata")
load("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Greatlake_results/pfilter_results/pfilter_100_ovov.Rdata")

load("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Greatlake_results/pfilter_results/wwr_100+_ovov.Rdata")
load("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Greatlake_results/pfilter_results/another_pfilter_100_ovov.Rdata")
```

```{r}
x_keep_1 <- x[!is.na(y)]
y_keep_1 <- y[!is.na(y)]

x_keep_2 <- x[!is.na(y)]
y_keep_2 <- y[!is.na(y)]
```

```{r}
x <- c(x_keep_1,x_keep_2)
y <- c(y_keep_1,y_keep_2)

plot(x,y,pch=20, cex=0.3)
abline(a=0,b=1, col="red",lwd=1)

sum(y < x)
```


```{r}
load("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/sim_list_100.Rdata")
x <- c()
for(i in 1:100){
 x[i] <- all(sim_list_100[[i]] != 0)
}
ind_1 <- which(x)
sim_keep_1 <- sim_list_100[ind_1]

load("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/sim_list_100+.Rdata")
x <- c()
for(i in 1:100){
 x[i] <- all(sim_list_100[[i]] != 0)
}
ind_2 <- which(x)
sim_keep_2 <- sim_list_100[ind_2]

sim_keep_nonzero_125 <- c(sim_keep_1, sim_keep_2)

save(sim_keep_nonzero_125, file="~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/sim_keep_nonzero_125.Rdata")
```
