#!/bin/bash
# Created by the ARC-TS SLURM job script generator for use on Great Lakes
# Thu Apr 14 2022 10:24:48 GMT-0400 (EDT)

# The name of the job:
#SBATCH --job-name="panelPomp search"

# Send yourself an email when the job:
# aborts abnormally (fails)
#SBATCH --mail-type=FAIL
# ends successfully
#SBATCH --mail-type=END

# Use this email address:
#SBATCH --mail-user=yizehao@umich.edu


# Maximum number of tasks/CPU cores used by the job:
#SBATCH --nodes=1
# ntasks is the important one
#SBATCH --ntasks-per-node=36
#SBATCH --cpus-per-task=1

# Total memory allocated for the job:
## 5GB/cpu is the basic share
#SBATCH --mem-per-cpu=1GB

# The maximum running time of the job in days-hours:mins:sec
#SBATCH --time=0-20:0:00

# The account which this job should run under:
#SBATCH --account="ionides2"

# Partition for the job:
#SBATCH -p standard

# Run the job from the directory where it was launched (default)

# The modules to load:
module load R

# The job command(s):
echo "Running on $SLURM_JOB_NODELIST"
echo "Running in $(pwd)"
 
## Important variables ##
# out_dir must end with /
export out_dir="output/mod_02/newten/round_03/"
file_to_run="generalPanelFit1.R"
mgf_cp_name="MJob.sbat"

### Main commands ###
mkdir -p $out_dir
cp MJob.sbat $out_dir$mgf_cp_name
cp R/$file_to_run $out_dir$file_to_run
R CMD BATCH --no-restore --no-save \
  $out_dir/$file_to_run $out_dir$file_to_run"out"
