---
title: "Rotavirus Model"
author: "Yize Hao"
date: "2023-10-19"
output: html_document
---

```{r}
library(pomp)
```

```{r}
rproc <- Csnippet("
    double N = S_1+E_1+I_1+R_1+S_2+E_2+I_2+R_2+S_3+E_3+I_3+R_3;
    double I = I_1 + I_2 + I_3;
    double dt = 0.25
    double trans_S1[3], trans_S2[3], trans_S3[2], trans_I1[3], trans_I2[3], trans_I3[2], trans_R1[3], trans_R2[3], trans_R3[2];
    
    double prob_S1[3],prob_I1[3],prob_R1[3],prob_S2[3],prob_I2[3],prob_R2[3],prob_S3[2],prob_I3[2],prob_R3[2];
    double alpha = dt*N/(78.86912*52);
    double kappa = (1 + rho*cos(2*3.141593*t/52 + phi))
    double Beta1 = beta1*kappa; //seasonal forcing
    double Beta2 = beta2*kappa; //seasonal forcing
    double Beta3 = beta3*kappa; //seasonal forcing
    
    // Define rate
    prob_S1[0] = 1-exp(-Beta_1*I/N*dt);
    prob_S1[1] = 1-exp(-dt*d_1);
    prob_S1[2] = exp(-dt*d_1) - prob_1[0];
    
    prob_I1[0] = 1-exp(-dt*gamma);
    prob_I1[1] = 1-exp(-dt*d_1);
    prob_I1[2] = exp(-dt*gamma)+exp(-dt*d_1) - 1
    
    prob_R1[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R1[1] = 1 - exp(-dt*d_1);
    prob_R1[2] = exp(-dt*omega) + exp(-dt*d_1) - 1;
    
    prob_S2[0] = 1-exp(-Beta_2*I/N*dt);
    prob_S2[1] = 1-exp(-dt*d_2);
    prob_S2[2] = exp(-dt*d_2) - prob_S2[0];
    
    prob_I2[0] = 1-exp(-dt*gamma);
    prob_I2[1] = 1-exp(-dt*d_2);
    prob_I2[2] = exp(-dt*gamma)+exp(-dt*d_2) - 1
    
    prob_R2[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R2[1] = 1 - exp(-dt*d_1);
    prob_R2[2] = exp(-dt*omega) + exp(-dt*d_1) - 1;
    
    // For Age Group (3): Die first before transition;
    
    S3mD = rbinom(S_3, delta);
    I3mD = rbinom(I_3, delta);
    R3mD = rbinom(R_3, delta);
    
    prob_S3[0] = 1-exp(-Beta_3*I/N*dt);
    prob_S3[1] = 1 - prob_S3[0];
    
    prob_I3[0] = 1 - exp(-dt*gamma);
    prob_I3[1] = exp(-dt*gamma);
    
    prob_R3[0] = 1 - exp(-dt*omega);
    prob_R3[1] = exp(-dt*omega);
    
    // Transition
    // B: S->I
    // C: I->R
    // F: Aging: (1)->(2)->(3)
    // E: R->S
    // D: Death
    //// Note: Here S_1, S_2... are all old value from (t-1)
    rmultinom(S_1, &prob_S1, 3, &trans_S1); // B, F, S-B-F
    rmultinom(I_1, &prob_I1, 3, &trans_I1); // C, F, I-C-F
    rmultinom(R_1, &prob_R1, 3, &trans_R1); // E, F, R-E-F
    
    rmultinom(S_2, &prob_S2, 3, &trans_S2); // B, F, S-B-F
    rmultinom(I_2, &prob_I2, 3, &trans_I2); // C, F, I-C-F
    rmultinom(R_2, &prob_R2, 3, &trans_R2); // E, F, R-E-F
    
    rmultinom(S3mD, &prob_S3, 2, &trans_S3); // B, S-D-B
    rmultinom(I3mD, &prob_I3, 2, &trans_I3); // C, I-D-C
    rmultinom(R3mD, &prob_R3, 2, &trans_R3); // E, R-D-E
    
    S_1 = trans_S1[2] + trans_R1[0] + rpois(alpha*N*dt); // Include Birth
    I_1 = trans_I1[2] + trans_S1[0];
    R_1 = trans_R1[2] + trans_I1[0];
    
    S_2 = trans_S2[2] + trans_R2[0] + trans_S1[1]; // Include Aging
    I_2 = trans_I2[2] + trans_S2[0] + trans_I1[1];
    R_2 = trans_R2[2] + trans_I2[0] + trans_R1[1];
    
    S_3 = trans_S3[1] + trans_R3[0] + trans_S2[1]; // Include Aging
    I_3 = trans_I3[1] + trans_S3[0] + trans_I2[1];
    R_3 = trans_R3[1] + trans_I3[0] + trans_R2[1];
")

## ----rinit-------------------------------------------------
# initializer
init <- function(params, t0, ...) {
  x0 <- c(S1=0,I1=0,R1=0,S2=0,I2=0,R2=0, S3=0,I3=0,R3=0)
  y <- params[c("y1","y2","y3")]
  x0["I_1"] <- y[1]/((params["gamma"]+params["d_1"]))
  x0["I_2"] <- (y[2]+params["d_1"]*x0["I_1"])/((params["d_2"]+params["gamma"]))
  x0["S_1"] <- (params["alpha"]*params["N"]-(params["gamma"]+params["d_1"])*x0["I_1"]+params["omega"]*(params["N"]*params["alpha"]/params["d_1"]-x0["I_1"]))/(params["d_1"]+params["omega"])
  I_bar    <-  x0["I_1"]+x0["I_2"]+x0["I_3"]
  x0["S_2"] <- (params["d_1"]*x0["S_1"]-(params["d_2"]+params["gamma"])*x0["I_2"]+params["d_1"]*x0["I_1"]+params["omega"]*(params["N"]*params["alpha"]/params["d_2"]-x0["I_2"]))/(params["d_2"]+params["omega"])
  
  x0["S_3"] <- (params["d_2"]*x0["S_2"]-(params["gamma"]+params["delta"])*x0["I_3"]+params["d_2"]*x0["I_2"]+params["omega"]*(params["N"]*params["alpha"]/params["delta"]-x0["I_3"]))/(params["omega"]+params["delta"])
  
  x0["R_1"] <- (params["N"]*params["alpha"]/params["d_1"]-x0["S_1"]-x0["I_1"])
  x0["R_2"] <- (params["N"]*params["alpha"]/params["d_2"]-x0["S_2"]-x0["I_2"])
  x0["R_3"] <- (params["N"]*params["alpha"]/params["delta"]-x0["S_3"]-x0["I_3"])
  round(x0) 
}


## ----rmeasure-------------------------------------------------
rmeas <- Csnippet("
  Y_I = rbinom(I, q_I); // this is observed cases
")

dmeas <- Csnippet("
  lik = dbinom(Y_I, I, q_I, 1);
")
```