---
title: "Greatlakes_results"
author: "Yize Hao"
date: "2023-11-04"
output: html_document
---

```{r}
mif_check_01 <- readRDS("~/Study/STATS489/PAL_check/rotavirus/mif_check_01.rds")
lik <- c()
for(i in 1:36){
  lik[i] <- mif_check_01[[i]]@loglik
}
```

```{r}
mif_check_paldata_stocksmodel_02 <- readRDS("~/Study/STATS489/PAL_check/rotavirus/mif_check_paldata_stocksmodel_02.rds")
lik <- c()
for(i in 1:36){
  lik[i] <- mif_check_paldata_stocksmodel_02[[i]]@loglik
}

```

```{r}
mif_check_paldata_stocksmodel_next_01 <- readRDS("~/Study/STATS489/PAL_check/rotavirus/mif_check_paldata_stocksmodel_next_01.rds")
lik <- c()
for(i in 1:36){
  lik[i] <- mif_check_paldata_stocksmodel_next_01[[i]]@loglik
}

panel <- list()
for(i in 1:36){
  panel[[i]] <- panelPomp::panelPomp(
      mif_check_paldata_stocksmodel_next_01[i] |> `names<-`("unit"),
      shared = NULL,
      specific = mif_check_paldata_stocksmodel_next_01[[i]] |> 
        pomp::coef() |> 
        as.matrix() |>
        `colnames<-`(paste0("unit",i))
    )
}
measlespkg::eval_logLik(panel, ncores =2, np_pf = 5,nreps=2)
```

