---
title: "Test Here"
author: "Yize Hao"
date: "2023-09-23"
output: html_document
---

```{r}
library(pomp)
library(ggplot2)
library(doFuture)
```


#### Full model with xi

```{r}
rproc <- Csnippet("
    double rate[3], trans[7];
    double N = S+E+I+R;
    double xi = rgammawn(1,dt);
    // True death is not by expon rate, but binomial probability.
    rate[0] = -xi*beeta*I/N;    // stochastic force of infection
    rate[1] = -rho;         // rho is our original sigma
    rate[2] = -gamma;      // recovery
    
    // die first before transit
    trans[1] = rbinom(S, delta);
    trans[3] = rbinom(E, delta);
    trans[5] = rbinom(I, delta);
    trans[6] = rbinom(R, delta);
    
    trans[0] = rbinom(trans[1], 1-exp(rate[0]));
    trans[2] = rbinom(trans[3], 1-exp(rate[1]));
    trans[4] = rbinom(trans[5], 1-exp(rate[2]));
    
    // with birth case
    S = trans[1] - trans[0] + rpois(0.05*pi_0S*N);
    E = trans[3] + trans[0] - trans[2];
    I = trans[5] + trans[2] - trans[4] + rpois(0.05*pi_0I*N);
    R = trans[6] + trans[4]; 
    
    q_I = -1;
  
    while(q_I<0 || q_I>1){
    q_I = rnorm(mu_q, sigma_q);
    }
")

## ----rinit-------------------------------------------------
rinit <- Csnippet("
  double pi_0[4]={pi_0S,0,pi_0I,0}; // pi_0 should be specified
  int trans_0[4];
  
  rmultinom(n, &pi_0, 4, &trans_0);
  S = trans_0[0];
  E = trans_0[1];
  I = trans_0[2];
  R = trans_0[3];
")


## ----rmeasure-------------------------------------------------
rmeas <- Csnippet("
  Y_I = rbinom(I, q_I); // this is observed cases
<<<<<<< HEAD
")

dmeas <- Csnippet("
  lik = dbinom(Y_I, I, q_I, 1);
")

sim1 <- simulate(t0=0, 
                 times = 1:100, 
                 paramnames = c("beeta", "rho", "gamma", "delta",
                                "pi_0S", "pi_0I", "n",
                                "mu_q","sigma_q"),
                 params = c(beeta=0.8, rho=0.1, gamma=0.2, delta=0.95, 
                            pi_0S=0.99, pi_0I=0.01, 
                            n=10000,
                            mu_q=0.5, sigma_q=0.1),
                 rinit = rinit,
                 rprocess = discrete_time(rproc),
                 rmeasure = rmeas,
                 statenames=c("S","E","I","R","q_I"),
                 obsnames=c("Y_I"))

(sim_data <- as.data.frame(sim1))
=======
")

dmeas <- Csnippet("
  lik = dbinom(Y_I, I, q_I, 1);
")
>>>>>>> refs/remotes/origin/master


ggplot(data=sim_data) + 
 geom_line(aes(x=time, y=S),color='green') +
 geom_line(aes(x=time, y=E), color='orange') +
 geom_line(aes(x=time, y=I), color='red') +
 geom_line(aes(x=time, y=R), color='blue') +
  ylab('X')+xlab('date')

ggplot(data=sim_data) + 
 geom_line(aes(x=time, y=I), color='red') +
  ylab('Y_I')+xlab('date')
```

#### PAL check

```{R}
S_pal <- c(100525, 102086, 103762, 105456, 107013, 108600, 110174, 111667,
       113014, 114496, 115876, 117254, 118500, 119436, 120605, 121626,
       122701, 123779, 124648, 125466, 126258, 126873, 127729, 128447,
       129143, 129725, 130341, 130859, 131321, 131679, 131874, 132228,
       132399, 132544, 132486, 132411, 132118, 131808, 131546, 131166,
       130852, 130242, 129805, 129071, 128351, 127664, 126769, 125827,
       124683, 123670, 122634, 121426, 120445, 119216, 117762, 116361,
       114932, 113570, 112343, 110832, 109162, 107364, 105721, 104133,
       102343, 100643,  98877,  97023,  95260,  93501,  91736,  90048,
        88327,  86659,  85151,  83570,  81896,  80331,  78959,  77568,
        76201,  74857,  73540,  72159,  71034,  69973,  68810,  67663,
        66723,  66007,  65031,  64181,  63397,  62608,  61930,  61150,
        60548,  60065,  59489,  58790,  58254,  57863,  57504,  57244,
        57065,  56790,  56596,  56394,  56163,  56050,  55899,  55686,
        55514,  55308,  55212,  55303,  55243,  55422,  55433,  55467,
        55546,  55799,  56116,  56329,  56308,  56260,  56409,  56524,
        56709,  56991,  57198,  57423,  57533,  57784,  57911,  58149,
        58123,  58443,  58587,  58794,  58950,  59232,  59459,  59713,
        59912,  60210,  60359,  60615,  60850,  60981,  61100,  61181,
        61430,  61531,  61850,  61950,  62134,  62259,  62271,  62396,
        62499,  62716,  62938,  62994,  63206,  63285,  63478,  63535,
        63529,  63706,  63913,  64087,  64186,  64321,  64528,  64612,
        64603,  64729,  64836,  65046,  65040,  65176,  65250,  65345,
        65421,  65471,  65662,  65814,  65943,  66038,  66129,  66201,
        66294,  66458,  66574,  66661,  66682,  66722,  66750,  66790)
S_pomp <- sim_data$S
time <- c(1:200)
ggplot() + 
 geom_line(aes(x=time, y=S_pal), color='purple') +
 geom_line(aes(x=time, y=S_pomp),color='green') +labs(x="time", y="S")

tot_pomp <- sim_data$S+sim_data$E+sim_data$I+sim_data$R
tot_pal <- c(101967, 103872, 105928, 107930, 109811, 111713, 113557, 115331,
       116980, 118769, 120447, 122184, 123758, 125072, 126554, 127963,
       129387, 130877, 132190, 133514, 134786, 135988, 137359, 138676,
       139923, 141146, 142360, 143519, 144711, 145853, 146939, 148106,
       149128, 150176, 151058, 152093, 152966, 153782, 154680, 155603,
       156572, 157398, 158309, 159054, 159781, 160630, 161451, 162208,
       162724, 163445, 164246, 164937, 165753, 166489, 167035, 167648,
       168214, 168887, 169676, 170277, 170790, 171300, 171870, 172458,
       172981, 173371, 173905, 174496, 174862, 175317, 175717, 176111,
       176615, 176954, 177513, 178052, 178559, 178970, 179455, 179946,
       180499, 180991, 181381, 181688, 182159, 182617, 183000, 183343,
       183707, 184055, 184333, 184722, 185145, 185443, 185747, 186013,
       186349, 186649, 186943, 187202, 187452, 187791, 188006, 188355,
       188694, 189021, 189307, 189550, 189759, 189957, 190142, 190329,
       190506, 190726, 190867, 191165, 191278, 191568, 191618, 191778,
       191865, 192265, 192663, 192962, 193094, 193213, 193309, 193481,
       193715, 193883, 193976, 194065, 193992, 194033, 194035, 194200,
       194191, 194277, 194315, 194505, 194547, 194721, 194981, 195053,
       195083, 195303, 195439, 195635, 195820, 195882, 195958, 195905,
       196000, 196162, 196157, 196181, 196222, 196247, 196215, 196252,
       196324, 196412, 196437, 196486, 196633, 196685, 196779, 196842,
       196781, 196827, 197020, 197035, 197066, 197189, 197247, 197326,
       197265, 197352, 197302, 197306, 197337, 197369, 197405, 197390,
       197355, 197400, 197522, 197704, 197892, 198019, 198036, 198109,
       198199, 198312, 198358, 198357, 198386, 198364, 198332, 198453)

ggplot() + 
 geom_line(aes(x=time, y=tot_pomp), color='purple') +
 geom_line(aes(x=time, y=tot_pal),color='green')+labs(x="time",y="Total #")
```


#### Simulated with Lambda and Mu

```{r}
rproc <- Csnippet("
    double rate[3], trans[7];
    double alpha[4]={a_0,a_1,a_2,a_3};
    
    // should have q_t here not in rmeas and as state variable;
  
    double xi = rgammawn(1,dt);
    // True death is not by expon rate, but binomial probability.
    rate[0] = -beeta*I/(S+E+I+R);    // stochastic force of infection
    rate[1] = -rho;         // rho is our original sigma
    rate[2] = -gamma;      // recovery
    
    // die first before transit
    trans[1] = rbinom(S, delta);
    trans[3] = rbinom(E, delta);
    trans[5] = rbinom(I, delta);
    trans[6] = rbinom(R, delta);
    
    trans[0] = rbinom(trans[1], 1-exp(rate[0]));
    trans[2] = rbinom(trans[3], 1-exp(rate[1]));
    trans[4] = rbinom(trans[5], 1-exp(rate[2]));
    
    // with birth case
    S = trans[1] - trans[0] + rpois(a_0);
    E = trans[3] + trans[0] - trans[2] + rpois(a_1);
    I = trans[5] + trans[2] - trans[4] + rpois(a_2);
    R = trans[6] + trans[4] + rpois(a_3); 
    
    //////////////////////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////////////////////////
    // if redundant states are declared then it can't be copied to rmeas
    // rmeas
    int obs[4], arr_S[4], arr_E[4], arr_I[4], arr_R[4];
    int Y[4];
    double kappa[4]={k_0,k_1,k_2,k_3};
  
  //Detect then misreport;
    obs[0] = rbinom(S, q_S);
    obs[1] = rbinom(E, q_E);
    obs[2] = rbinom(I, q_I); // this is observed cases
    obs[3] = rbinom(R, q_R);
  
  //misreporting matrix:
    double prob_S[4] = {g00,g01,g02,g03};
    double prob_E[4] = {g10,g11,g12,g13};
    double prob_I[4] = {g20,g21,g22,g23};
    double prob_R[4] = {g30,g31,g32,g33};
  
  //Observed Y:
    rmultinom(obs[0], &prob_S, 4, &arr_S);
    rmultinom(obs[1], &prob_E, 4, &arr_E);
    rmultinom(obs[2], &prob_I, 4, &arr_I);
    rmultinom(obs[3], &prob_R, 4, &arr_R);
  
    for(int i=0; i<4; i++){
      Y[i] = arr_S[i]+arr_E[i]+arr_I[i]+arr_R[i];
    }
  
    Y_S = Y[0]+rpois(k_0);
    Y_E = Y[1]+rpois(k_1);
    Y_I = Y[2]+rpois(k_2);
    Y_R = Y[3]+rpois(k_3);
    
    // Introducing lambda and mu
    
    double rate_l[3];
    
    rate_l[0] = -beeta*l_bar_I/(l_bar_S+ l_bar_E+ l_bar_I+ l_bar_R);  
    rate_l[1] = -rho;         
    rate_l[2] = -gamma; 
    
    l_S = l_bar_S*delta * exp(rate_l[0]) + a_0; // mean of poisson is the rate
    l_E = l_bar_S*delta * (1-exp(rate_l[0])) + l_bar_E*delta * exp(rate_l[1]) + a_1;
    l_I = l_bar_E*delta * (1-exp(rate_l[1])) + l_bar_I*delta * exp(rate_l[2]) + a_2;
    l_R = l_bar_I*delta * (1-exp(rate_l[2])) + l_bar_R*delta * 1 + a_3;
    
    double ys_eys = Y_S/(q_S*l_S*g00+q_E*l_E*g10+q_I*l_I*g20+q_R*l_R*g30+k_0);
    double ye_eye = Y_E/(q_S*l_S*g01+q_E*l_E*g11+q_I*l_I*g21+q_R*l_R*g31+k_1);
    double yi_eyi = Y_I/(q_S*l_S*g02+q_E*l_E*g12+q_I*l_I*g22+q_R*l_R*g32+k_2);
    double yr_eyr = Y_R/(q_S*l_S*g03+q_E*l_E*g13+q_I*l_I*g23+q_R*l_R*g33+k_3);
    
    l_bar_S = (1-q_S+(ys_eys*q_S*g00+ye_eye*q_S*g01+yi_eyi*q_S*g02+yr_eyr*q_S*g03))*l_S;
    l_bar_E = (1-q_E+(ys_eys*q_E*g10+ye_eye*q_E*g11+yi_eyi*q_E*g12+yr_eyr*q_E*g13))*l_E;
    l_bar_I = (1-q_I+(ys_eys*q_I*g20+ye_eye*q_I*g21+yi_eyi*q_I*g22+yr_eyr*q_I*g23))*l_I;
    l_bar_R = (1-q_R+(ys_eys*q_R*g30+ye_eye*q_R*g31+yi_eyi*q_R*g32+yr_eyr*q_R*g33))*l_R;
    
    mu_S = q_S*l_S*g00+q_E*l_E*g10+q_I*l_I*g20+q_R*l_R*g30 + k_0;
    mu_E = q_S*l_S*g01+q_E*l_E*g11+q_I*l_I*g21+q_R*l_R*g31 + k_1;
    mu_I = q_S*l_S*g02+q_E*l_E*g12+q_I*l_I*g22+q_R*l_R*g32 + k_2;
    mu_R = q_S*l_S*g03+q_E*l_E*g13+q_I*l_I*g23+q_R*l_R*g33 + k_3;
")

## ----rinit-------------------------------------------------
rinit <- Csnippet("
    double pi_0[4]={pi_0S,0,pi_0I,0}; // pi_0 should be specified
    int trans_0[4];
    
    double lambda_0[4] = {n*pi_0S,0,n*pi_0I,0};
  
    l_S=lambda_0[0];
    l_E=lambda_0[1];
    l_I=lambda_0[2];
    l_R=lambda_0[3];
  
    l_bar_S=lambda_0[0];
    l_bar_E=lambda_0[1];
    l_bar_I=lambda_0[2];
    l_bar_R=lambda_0[3];
    
    rmultinom(n, &pi_0, 4, &trans_0);
    S = trans_0[0];
    E = trans_0[1];
    I = trans_0[2];
    R = trans_0[3];
")


## ----rmeasure-------------------------------------------------
rmeas <- Csnippet("
  Y_0 = Y_S;
  Y_1 = Y_E;
  Y_2 = Y_I;
  Y_3 = Y_R;
  
  mu_0 = mu_S;
  mu_1 = mu_E;
  mu_2 = mu_S;
  mu_3 = mu_R;
")


## ----dmeasure-------------------------------------------------
dmeas <- Csnippet("
  double ys_f,ye_f,yi_f,yr_f;
  
  for(int i = 1; i <= Y_0; ++i) {
            ys_f *= i;
  }
  
  for(int i = 1; i <= Y_1; ++i) {
            ye_f *= i;
  }
        
  for(int i = 1; i <= Y_2; ++i) {
            yi_f *= i;
  }
        
  for(int i = 1; i <= Y_3; ++i) {
            yr_f *= i;
  }
        
  lik = -(mu_0+mu_1+mu_2+mu_3) + (Y_0*log(mu_0)+Y_1*log(mu_1)+Y_2*log(mu_2)+Y_3*log(mu_3))- (log(ys_f)+log(ye_f)+log(yi_f)+log(yr_f));
")


sim1 <- simulate(t0=0, 
                 times = 1:200, 
                 paramnames = c("beeta", "rho", "gamma", "delta",
                                "pi_0S", "pi_0I", "n",
                                "a_0","a_1","a_2","a_3",
                                "k_0","k_1","k_2","k_3",
                                "g00","g01","g02","g03",
                                "g10","g11","g12","g13",
                                "g20","g21","g22","g23",
                                "g30","g31","g32","g33",
                                "q_S","q_E","q_I","q_R"),
                 params = c(beeta=0.5, rho=0.05, gamma=0.1, delta=0.98, 
                            pi_0S=0.99, pi_0I=0.01, 
                            n=100000,
                            a_0=4000,   a_1=0,    a_2=0,      a_3=0,
                            k_0=1000,   k_1=1000, k_2=1000,   k_3=1000,
                            g00=0.95,   g01=0.0,  g02=0.05,   g03=0.0,
                            g10=0.3,    g11=0,    g12=0.7,    g13=0.0,
                            g20=0.15,   g21=0.0,  g22=0.85,   g23=0.0,
                            g30=0.0,    g31=0.0,  g32=0.0,    g33=1.0,
                            q_S=0.1,    q_E=0.1,  q_I=0.3,    q_R=0.2),
                 rinit = rinit,
                 rprocess = discrete_time(rproc),
                 rmeasure = rmeas,
                 dmeasure = dmeas,
                 statenames=c("S","E","I","R",
                              "Y_S","Y_E","Y_I","Y_R",
                              "l_S","l_E","l_I","l_R",
                              "l_bar_S","l_bar_E","l_bar_I","l_bar_R",
                              "mu_S","mu_E","mu_I","mu_R"),
                 obsnames=c("Y_0","Y_1","Y_2","Y_3",
                            "mu_0","mu_1","mu_2","mu_3"))

(sim_data <- as.data.frame(sim1))

ggplot(data=sim_data) + 
 geom_line(aes(x=time, y=S),color='green') +
 geom_line(aes(x=time, y=E), color='orange') +
 geom_line(aes(x=time, y=I), color='red') +
 geom_line(aes(x=time, y=R), color='blue') +
  ylab('X')+xlab('date')

ggplot(data=sim_data) + 
 geom_line(aes(x=time, y=Y_0),color='green') +
 geom_line(aes(x=time, y=Y_1), color='orange') +
 geom_line(aes(x=time, y=Y_2), color='red') +
 geom_line(aes(x=time, y=Y_3), color='blue') +
  ylab('Y')+xlab('date')

ggplot(data=sim_data) + 
 geom_line(aes(x=time, y=l_S),color='green') +
 geom_line(aes(x=time, y=l_E), color='orange') +
 geom_line(aes(x=time, y=l_I), color='red') +
 geom_line(aes(x=time, y=l_R), color='blue') +
  ylab('Lambda')+xlab('date')

ggplot(data=sim_data) + 
 geom_line(aes(x=time, y=mu_S),color='green') +
 geom_line(aes(x=time, y=mu_E), color='orange') +
 geom_line(aes(x=time, y=mu_I), color='red') +
 geom_line(aes(x=time, y=mu_R), color='blue') +
  ylab('Mu')+xlab('date')
```


#### SEIR Model

```{r}
rproc <- Csnippet("
    double rate[3], trans[7];
    double N = S+E+I+R;
    double xi = rgammawn(1,dt);
    // True death is not by expon rate, but binomial probability.
    rate[0] = -xi*beeta*I/N;    // stochastic force of infection
    rate[1] = -rho;         // rho is our original sigma
    rate[2] = -gamma;      // recovery
    
    // die first before transit
    trans[1] = rbinom(S, delta);
    trans[3] = rbinom(E, delta);
    trans[5] = rbinom(I, delta);
    trans[6] = rbinom(R, delta);
    
    trans[0] = rbinom(trans[1], 1-exp(rate[0]));
    trans[2] = rbinom(trans[3], 1-exp(rate[1]));
    trans[4] = rbinom(trans[5], 1-exp(rate[2]));
    
    // with birth case
    S = trans[1] - trans[0] + rpois(0.05*pi_0S*N);
    E = trans[3] + trans[0] - trans[2];
    I = trans[5] + trans[2] - trans[4] + rpois(0.05*pi_0I*N);
    R = trans[6] + trans[4]; 
    
    q_I = -1;
  
    while(q_I<0 || q_I>1){
    q_I = rnorm(mu_q, sigma_q);
    }
")

## ----rinit-------------------------------------------------
rinit <- Csnippet("
  double pi_0[4]={pi_0S,0,pi_0I,0}; // pi_0 should be specified
  double trans_0[4];

  rmultinom(n, &pi_0, 4, &trans_0);
  S = trans_0[0];
  E = trans_0[1];
  I = trans_0[2];
  R = trans_0[3];
")


## ----rmeasure-------------------------------------------------
rmeas <- Csnippet("
  Y_I = rbinom(I, q_I); // this is observed cases
")

dmeas <- Csnippet("
  lik = dbinom(Y_I, I, q_I, 1);
")

sim1 <- simulate(t0=0, 
                 times = 1:100, 
                 paramnames = c("beeta", "rho", "gamma", "delta",
                                "pi_0S", "pi_0I", "n",
                                "mu_q","sigma_q"),
                 params = c(beeta=0.8, rho=0.1, gamma=0.2, delta=0.95, 
                            pi_0S=0.99, pi_0I=0.01, 
                            n=10000,
                            mu_q=0.5, sigma_q=0.1),
                 rinit = rinit,
                 rprocess = discrete_time(rproc),
                 rmeasure = rmeas,
                 statenames=c("S","E","I","R","q_I"),
                 obsnames=c("Y_I"))

(sim_data <- as.data.frame(sim1))

ggplot(data=sim_data) + 
 geom_line(aes(x=time, y=S),color='green') +
 geom_line(aes(x=time, y=E), color='orange') +
 geom_line(aes(x=time, y=I), color='red') +
 geom_line(aes(x=time, y=R), color='blue') +
  ylab('Values')+xlab('date')

ggplot(data=sim_data) + 
 geom_line(aes(x=time, y=Y_I), color='red') +
  ylab('Values')+xlab('date')
```

#### Compare Models: t-test

##### check total Y pal

```{r}
a <- c()
for(i in 1:1000){
  sim1 <- simulate(t0=0, 
                 times = 1:100, 
                 paramnames = c("beeta", "rho", "gamma", "delta",
                                "pi_0S", "pi_0I", "n",
                                "mu_q","sigma_q"),
                 params = c(beeta=0.8, rho=0.1, gamma=0.2, delta=0.95, 
                            pi_0S=0.99, pi_0I=0.01, 
                            n=10000,
                            mu_q=0.5, sigma_q=0.1),
                 rinit = rinit,
                 rprocess = discrete_time(rproc),
                 rmeasure = rmeas,
                 statenames=c("S","E","I","R","q_I"),
                 obsnames=c("Y_I"))

    (sim_data <- as.data.frame(sim1))
      a <- c(a, sum(sim_data$Y_I))
}

pf_sum <- a
```

```{r}
pal_sum <- c(33961., 28331., 23611., 34606., 29494., 28611., 23147., 33657.,
       35940., 28015., 29870., 28417., 28568., 31361., 32347., 32042.,
       31444., 25819., 21111., 30779., 36315., 30975., 25223., 30047.,
       35239., 30359., 33750., 31725., 25440., 30479., 30633., 36106.,
       32295., 32240., 29736., 32705., 35168., 30283., 31799., 38119.,
       32345., 34139., 29007., 27233., 32953., 33930., 29326., 32263.,
       33058., 31292., 32644., 31343., 29841., 25927., 36294., 35072.,
       31187., 28428., 27593., 28111., 27109., 34825., 26471., 31872.,
       30619., 33241., 28749., 29241., 27898., 23450., 37522., 23918.,
       26722., 34484., 28677., 31156., 29314., 33501., 26901., 26426.,
       25858., 32971., 34373., 35698., 32301., 29087., 29685., 24658.,
       26282., 28261., 30676., 33091., 33273., 28380., 26699., 26957.,
       29900., 27983., 26766., 24430., 36448., 33998., 33833., 26968.,
       37337., 27784., 28439., 31593., 36301., 38642., 29896., 35977.,
       30816., 25142., 32904., 35839., 31450., 36546., 35831., 25796.,
       38884., 25055., 28526., 32895., 31663., 27041., 30981., 31557.,
       30289., 32191., 38626., 33909., 33515., 28342., 29692., 26536.,
       22398., 32328., 34150., 32455., 31465., 27958., 29857., 27106.,
       21633., 32219., 34860., 33650., 31108., 32807., 29678., 22421.,
       29632., 28455., 24915., 25487., 29381., 34207., 26526., 32505.,
       27170., 34267., 36114., 33884., 27086., 28464., 29205., 26688.,
       29453., 32281., 35017., 27577., 31411., 27700., 33240., 27967.,
       35645., 30681., 32843., 31876., 31871., 36480., 26504., 23170.,
       30801., 33697., 34570., 31264., 30726., 33751., 38315., 28060.,
       27997., 36461., 30401., 27096., 25586., 34799., 26985., 28947.,
       28276., 28008., 30892., 37407., 32863., 25793., 27232., 32572.,
       26726., 27322., 36612., 25524., 32852., 30969., 31198., 34024.,
       37173., 29207., 32676., 21734., 33787., 21894., 28408., 33558.,
       34520., 35163., 32218., 36026., 26654., 36221., 30502., 31916.,
       28878., 30484., 29778., 33727., 29048., 23317., 25364., 37376.,
       30276., 31662., 32470., 30439., 30648., 33439., 28600., 28090.,
       29965., 31254., 31285., 30323., 32748., 25688., 26722., 34225.,
       30457., 34392., 25400., 35615., 29869., 31515., 31449., 29540.,
       32816., 21322., 34683., 31173., 30606., 25175., 37347., 32357.,
       35034., 30450., 32944., 31388., 28253., 31208., 24916., 28480.,
       29009., 27022., 33868., 30221., 36752., 27199., 29919., 23233.,
       29289., 32996., 39698., 35660., 31670., 35574., 29475., 29607.,
       27259., 34052., 25563., 31981., 26654., 27894., 34419., 33514.,
       31524., 30944., 27522., 35499., 27099., 31396., 31825., 32122.,
       29135., 31696., 36985., 28336., 36716., 32727., 34336., 33287.,
       31265., 32145., 30062., 30311., 31887., 29563., 34729., 26709.,
       32872., 37066., 29626., 26917., 37977., 31556., 30340., 33725.,
       39334., 24404., 27525., 29889., 31785., 30815., 27773., 32009.,
       30365., 31001., 22177., 30920., 16092., 31380., 36457., 32570.,
       35994., 23894., 31796., 30748., 31566., 32433., 28584., 30897.,
       26584., 35823., 25505., 27433., 32839., 35196., 34452., 35244.,
       33129., 31401., 29616., 34531., 31204., 28838., 30761., 26877.,
       31868., 25713., 26038., 33378., 39070., 27091., 30560., 27784.,
       30520., 34154., 31354., 28505., 33045., 28573., 33540., 31886.,
       35685., 32843., 29053., 35055., 32638., 30351., 29486., 35078.,
       31194., 25487., 34494., 27730., 30728., 21199., 35424., 34309.,
       24062., 20159., 23197., 30616., 33842., 30207., 29439., 31039.,
       26299., 31193., 23801., 31697., 32803., 35066., 24994., 29179.,
       33636., 33159., 24013., 34879., 22086., 28875., 37337., 27821.,
       32561., 25424., 30866., 35490., 27436., 33424., 34910., 33784.,
       24645., 29908., 32028., 37906., 30933., 33138., 35452., 31524.,
       32008., 35575., 31223., 37139., 34306., 30584., 31329., 26765.,
       34665., 28120., 30055., 27827., 35072., 22024., 31763., 26219.,
       37058., 29725., 32060., 30953., 28604., 28440., 36899., 17866.,
       26633., 33894., 33741., 32407., 32014., 31859., 31293., 28862.,
       22758., 29389., 25214., 36653., 28453., 35314., 29098., 26479.,
       29931., 22073., 24773., 30189., 22872., 24804., 36338., 27611.,
       33035., 28146., 33277., 34646., 32731., 33713., 30795., 32802.,
       29814., 27372., 35501., 27792., 26279., 31816., 37629., 40071.,
       20396., 30327., 28210., 23010., 34359., 37124., 32196., 36207.,
       28456., 30968., 26478., 31237., 21149., 30190., 29770., 35066.,
       31381., 33766., 28548., 30846., 34920., 25091., 32324., 24473.,
       30352., 35130., 31984., 32930., 24840., 31309., 30673., 30551.,
       35737., 28671., 28307., 39582., 36281., 35311., 29170., 33313.,
       27966., 30504., 34272., 33734., 28907., 30825., 27720., 36439.,
       28092., 29422., 31369., 33338., 29620., 33319., 31706., 30613.,
       35809., 34662., 27007., 35009., 34801., 33839., 31764., 32610.,
       29915., 25467., 33506., 29681., 35673., 23029., 37122., 33774.,
       23012., 33732., 31094., 31877., 28732., 30436., 23335., 35219.,
       34626., 30848., 28609., 30610., 29106., 32588., 27527., 30114.,
       31789., 31365., 34154., 32802., 33837., 37075., 24452., 31436.,
       27843., 35996., 29475., 35112., 34860., 33436., 26445., 33265.,
       34934., 31902., 29515., 26357., 27101., 30092., 26154., 36139.,
       27969., 33004., 34858., 35636., 36954., 30342., 32878., 30761.,
       34917., 28895., 32548., 34054., 31431., 37550., 31611., 33142.,
       31566., 21467., 35633., 37028., 25659., 26679., 32138., 32464.,
       36713., 35054., 27812., 29015., 30472., 31164., 37045., 27917.,
       31795., 37498., 28107., 31594., 36760., 37664., 38453., 27749.,
       38854., 31245., 32826., 29981., 37278., 30100., 31860., 30982.,
       28051., 30133., 31546., 32865., 30096., 32370., 29074., 25137.,
       30139., 33767., 32729., 32646., 26566., 35468., 31295., 30129.,
       32815., 32694., 23124., 31225., 26555., 33085., 35004., 31181.,
       33483., 32100., 36398., 34132., 29766., 32116., 31036., 29864.,
       31951., 32454., 32919., 34162., 29591., 36198., 32614., 27635.,
       30729., 24491., 26707., 27333., 32765., 33546., 35513., 32094.,
       22395., 31557., 28652., 27990., 27309., 34808., 25895., 32217.,
       35296., 31504., 29737., 27902., 28161., 28442., 29653., 29479.,
       32053., 30339., 36401., 24406., 28579., 30456., 28380., 27671.,
       20748., 26222., 34365., 30196., 31944., 30311., 32762., 32949.,
       25966., 35688., 33631., 29895., 29844., 33265., 29573., 36779.,
       23858., 24174., 36500., 29237., 29627., 25039., 31375., 24958.,
       31370., 36031., 32522., 29814., 25478., 32977., 33963., 31050.,
       30408., 29660., 32732., 30203., 34589., 38415., 32959., 30991.,
       25375., 32121., 23584., 30255., 36441., 32151., 30288., 31362.,
       31228., 32211., 26145., 25175., 34784., 32211., 32409., 26893.,
       31778., 32259., 28505., 30903., 32087., 22631., 27909., 31951.,
       28131., 27771., 30865., 30294., 30990., 27246., 32193., 31131.,
       26695., 29638., 30295., 28862., 27890., 30534., 31317., 25593.,
       37341., 34471., 27325., 32622., 28286., 34493., 38282., 32604.,
       35262., 33189., 32354., 32972., 34638., 36058., 30658., 32986.,
       23051., 25592., 32479., 28893., 30881., 29501., 34701., 31249.,
       26898., 29005., 30877., 33954., 25054., 29564., 31713., 22791.,
       36202., 33282., 25358., 34424., 30695., 26594., 31494., 34094.,
       44529., 29452., 33964., 29541., 29938., 38316., 31850., 24415.,
       36969., 34682., 35028., 25338., 31901., 30394., 27744., 23517.,
       29281., 31320., 25021., 24970., 24732., 27717., 28779., 33952.,
       32581., 32859., 27370., 30081., 32433., 31031., 31505., 30762.,
       32026., 35640., 32471., 30119., 38389., 30756., 29368., 38421.,
       30063., 28564., 30790., 22747., 28174., 29147., 25166., 24206.,
       32269., 37324., 33125., 31033., 27064., 33627., 31609., 25924.,
       20899., 25986., 35614., 34202., 28408., 35203., 31914., 28239.,
       24686., 35494., 37624., 34499., 25092., 33268., 32848., 27274.,
       28422., 25377., 34945., 28543., 30238., 32048., 29992., 23358.,
       29983., 31179., 27548., 37042., 29803., 31561., 27960., 30286.,
       36161., 24996., 39143., 29374., 33544., 35387., 38024., 33882.,
       27045., 23010., 25225., 31936., 25563., 31348., 29383., 32239.,
       32267., 27283., 29214., 33464., 32620., 24378., 35014., 26223.,
       37971., 24940., 32627., 28381., 29974., 31190., 31180., 39395.,
       24911., 34667., 33164., 27935., 29236., 29941., 24199., 35604.,
       29130., 34965., 26829., 26878., 40988., 33481., 34290., 31772)
      
```

```{r}
t.test(pal_sum, pf_sum)

category = c(rep("PAL", 1000), rep("PF", 1000)) |> as.factor()
df <- data.frame(value = c(pal_sum, pf_sum), category = category)
ggplot(df, aes(x=value, color=category, fill=category)) +
geom_density(alpha=0.3)
```



#### median

```{r}
pf_median <- c()
for(i in 1:1000){
  sim1 <- simulate(t0=0, 
                 times = 1:100, 
                 paramnames = c("beeta", "rho", "gamma", "delta",
                                "pi_0S", "pi_0I", "n",
                                "mu_q","sigma_q"),
                 params = c(beeta=0.8, rho=0.1, gamma=0.2, delta=0.95, 
                            pi_0S=0.99, pi_0I=0.01, 
                            n=10000,
                            mu_q=0.5, sigma_q=0.1),
                 rinit = rinit,
                 rprocess = discrete_time(rproc),
                 rmeasure = rmeas,
                 statenames=c("S","E","I","R","q_I"),
                 obsnames=c("Y_I"))

    (sim_data <- as.data.frame(sim1))
      pf_median <- c(pf_median, median(sim_data$Y_I))
}

```

```{r}
pal_median <- c(365. , 368.5, 333. , 315. , 400.5, 312. , 275.5, 246.5, 296. ,
       295.5, 415.5, 362.5, 323. , 250.5, 195. , 353.5, 307. , 260. ,
       252.5, 299.5, 332. , 314. , 396.5, 397. , 259.5, 266.5, 215.5,
       285. , 269.5, 216.5, 338.5, 322. , 391.5, 322. , 345.5, 281. ,
       293.5, 375.5, 421.5, 298. , 391.5, 372. , 356. , 226. , 268. ,
       279. , 307. , 357.5, 280.5, 297.5, 402.5, 349.5, 382.5, 270. ,
       292. , 342.5, 377. , 316. , 279. , 300. , 305. , 218.5, 367.5,
       335.5, 322.5, 324.5, 239. , 305.5, 278.5, 327. , 318. , 348.5,
       364.5, 325.5, 333. , 287.5, 314.5, 290.5, 383. , 343.5, 357.5,
       283. , 389.5, 313.5, 240.5, 337.5, 358.5, 375. , 304.5, 314.5,
       377.5, 389. , 330.5, 326. , 275. , 297.5, 325.5, 384. , 242.5,
       356.5, 373.5, 141. , 346. , 445.5, 357.5, 270.5, 312. , 332.5,
       348.5, 303.5, 231. , 320.5, 318.5, 322.5, 345.5, 360. , 359.5,
       346.5, 385. , 340. , 349.5, 203. , 368. , 267. , 399. , 301.5,
       377. , 400.5, 347. , 282.5, 428. , 365.5, 378.5, 397. , 365.5,
       324.5, 275.5, 274.5, 389. , 344.5, 297. , 244. , 294.5, 312. ,
       335. , 352.5, 355.5, 322.5, 198. , 357. , 262.5, 349. , 304. ,
       325. , 349.5, 386. , 209.5, 386. , 290.5, 318. , 306. , 422.5,
       235.5, 383. , 329. , 359.5, 230.5, 328.5, 305.5, 273. , 318. ,
       322. , 304.5, 249. , 333.5, 165.5, 235. , 230.5, 317.5, 360.5,
       345.5, 326.5, 332.5, 278.5, 296. , 252. , 347.5, 355.5, 293.5,
       391.5, 331. , 332. , 382.5, 306.5, 276.5, 315.5, 228. , 290. ,
       376. , 392. , 337. , 293.5, 401. , 387. , 219. , 305.5, 371. ,
       230. , 426.5, 330. , 313.5, 338. , 375. , 254. , 368. , 337. ,
       288. , 360.5, 325. , 243.5, 336. , 339. , 344. , 425.5, 199.5,
       324.5, 405. , 346. , 428. , 370. , 337.5, 312. , 234. , 353.5,
       313.5, 307.5, 356.5, 321.5, 392. , 343.5, 353.5, 359.5, 313.5,
       340. , 254.5, 243. , 278. , 365.5, 317.5, 256.5, 287. , 302. ,
       364.5, 316. , 238.5, 288. , 260. , 216. , 332. , 321. , 301. ,
       286.5, 280. , 261.5, 335.5, 334.5, 286.5, 340.5, 277.5, 267. ,
       360.5, 350.5, 262. , 369. , 356.5, 382. , 338. , 292.5, 337.5,
       333.5, 361. , 344.5, 333.5, 339. , 278. , 340. , 395.5, 295. ,
       350.5, 384.5, 376.5, 308.5, 290.5, 301.5, 351.5, 325.5, 322. ,
       332. , 393.5, 322. , 336. , 333.5, 354. , 379. , 361.5, 326. ,
       329.5, 368. , 334.5, 391.5, 288.5, 353. , 340.5, 394. , 288.5,
       339.5, 294. , 366.5, 313. , 302. , 285.5, 397. , 302. , 365.5,
       242. , 260. , 252. , 314. , 361. , 341.5, 276. , 294. , 352. ,
       337. , 287. , 318.5, 318.5, 318.5, 346. , 324.5, 326. , 261.5,
       345.5, 238.5, 450.5, 177. , 324. , 319.5, 214.5, 269.5, 135. ,
       356.5, 337. , 357.5, 399.5, 393.5, 234.5, 331.5, 307.5, 309. ,
       349. , 321. , 316. , 356.5, 313. , 311. , 408. , 366.5, 342.5,
       348. , 245. , 331. , 305. , 358.5, 299. , 375.5, 301. , 345. ,
       350.5, 281.5, 314. , 384. , 341.5, 287. , 237. , 359.5, 287. ,
       268. , 383.5, 349. , 319.5, 319. , 257.5, 328. , 272.5, 366. ,
       293. , 300. , 352. , 357. , 314. , 295. , 328.5, 271.5, 300.5,
       250. , 292.5, 440.5, 370. , 260.5, 269. , 403. , 346.5, 334. ,
       336.5, 349.5, 309. , 330. , 330. , 316.5, 388. , 343.5, 295. ,
       350. , 150.5, 322.5, 345. , 275.5, 285.5, 227.5, 296. , 374. ,
       308. , 215. , 365. , 283. , 280.5, 258. , 313. , 344. , 287. ,
       372. , 180. , 351.5, 354.5, 319. , 308.5, 303.5, 216.5, 316. ,
       322. , 345.5, 365. , 239. , 315. , 259. , 380.5, 371. , 386.5,
       263. , 258.5, 341. , 410. , 355.5, 305.5, 340. , 376. , 356.5,
       325.5, 331.5, 359. , 289. , 237.5, 235. , 246.5, 352.5, 365. ,
       303. , 286. , 381. , 379.5, 242.5, 275.5, 345. , 264. , 380. ,
       356. , 273.5, 307.5, 347. , 283.5, 351. , 267. , 358.5, 293. ,
       349.5, 346. , 354.5, 340. , 318. , 198.5, 320.5, 257.5, 332. ,
       313.5, 399.5, 245.5, 320.5, 348.5, 302.5, 302. , 365.5, 253.5,
       372.5, 240. , 334. , 305.5, 369. , 326.5, 346.5, 273.5, 314. ,
       348.5, 299. , 349.5, 229.5, 264. , 407. , 318. , 340. , 238.5,
       326.5, 219.5, 382. , 322.5, 307. , 309. , 314. , 333.5, 257. ,
       304.5, 340. , 286.5, 341.5, 325. , 307. , 297.5, 212.5, 294. ,
       264. , 336.5, 370.5, 279.5, 386. , 196.5, 399.5, 410.5, 293. ,
       293. , 263. , 372. , 325. , 287. , 319. , 342. , 250.5, 401.5,
       319. , 353. , 310.5, 349. , 338. , 353. , 291. , 339.5, 358.5,
       308.5, 342.5, 375. , 320.5, 336.5, 381.5, 171. , 271. , 270. ,
       300.5, 167. , 361.5, 275.5, 401.5, 288.5, 264.5, 326.5, 347. ,
       388. , 280.5, 381.5, 233.5, 274.5, 377. , 256.5, 352.5, 341. ,
       320. , 333. , 313. , 370.5, 335.5, 380.5, 331. , 331.5, 216. ,
       277.5, 302. , 347.5, 302. , 374. , 283. , 324. , 245.5, 333.5,
       419.5, 289. , 272.5, 361.5, 234. , 297.5, 307.5, 274.5, 258.5,
       408.5, 284.5, 378. , 352.5, 290.5, 353. , 380.5, 393.5, 371.5,
       383.5, 333. , 295. , 386.5, 312. , 283.5, 307.5, 365. , 362.5,
       350.5, 294.5, 305. , 260. , 285. , 360.5, 379. , 344.5, 268. ,
       443. , 309.5, 319.5, 350. , 378.5, 431. , 351.5, 305. , 353. ,
       197. , 255.5, 374.5, 319.5, 348. , 281. , 345. , 248. , 334.5,
       314.5, 337. , 372. , 300.5, 281.5, 305.5, 372. , 420. , 135.5,
       313.5, 321.5, 270. , 391.5, 308. , 379. , 314. , 329. , 311. ,
       427.5, 338.5, 341. , 314.5, 251. , 314. , 391.5, 374. , 242.5,
       280.5, 306.5, 390. , 367. , 334.5, 225. , 338.5, 263. , 379.5,
       361.5, 251. , 342.5, 352. , 297.5, 354. , 366. , 298.5, 394.5,
       323. , 281.5, 402. , 364.5, 280.5, 390.5, 301.5, 302. , 310.5,
       191.5, 348.5, 281. , 401.5, 237.5, 337. , 359. , 360.5, 249.5,
       350.5, 346.5, 307. , 356.5, 417.5, 317.5, 272. , 328. , 284. ,
       307. , 374.5, 314. , 349.5, 328. , 298.5, 294. , 300.5, 315.5,
       277. , 305.5, 340. , 313.5, 337.5, 270.5, 350.5, 414.5, 367.5,
       381. , 320. , 377.5, 250.5, 280.5, 340.5, 312.5, 319.5, 283. ,
       319.5, 344.5, 329. , 355.5, 381.5, 296. , 278.5, 298. , 360. ,
       254. , 230. , 265.5, 285. , 310.5, 296. , 253. , 325. , 326.5,
       359. , 260. , 281. , 291. , 377.5, 304.5, 257.5, 328. , 295.5,
       384.5, 198.5, 337. , 341. , 236.5, 251. , 302. , 291. , 245.5,
       281.5, 328.5, 307. , 402. , 299.5, 335. , 285. , 289. , 326.5,
       401. , 300. , 237.5, 338. , 363.5, 401.5, 295.5, 368. , 266. ,
       336.5, 375.5, 368. , 256. , 300.5, 402.5, 410.5, 300. , 227.5,
       341.5, 284.5, 223. , 366.5, 324.5, 239. , 382.5, 388. , 363. ,
       394. , 348.5, 245. , 376.5, 312. , 325.5, 343.5, 157. , 311.5,
       351. , 295.5, 336.5, 306. , 320. , 411.5, 305.5, 350.5, 274. ,
       362. , 317. , 315. , 322. , 366. , 298. , 310. , 309.5, 309.5,
       330. , 349.5, 340. , 385.5, 365.5, 371.5, 341. , 368.5, 356. ,
       257. , 244. , 280. , 357.5, 374. , 247. , 299. , 346.5, 304.5,
       340.5, 328.5, 342.5, 339. , 307.5, 331. , 341. , 296. , 266.5,
       293. , 282.5, 292. , 279.5, 331.5, 329.5, 361. , 326. , 403. ,
       364. , 293.5, 391.5, 382. , 311.5, 288. , 356.5, 354. , 347.5,
       363.5, 251.5, 199. , 337. , 350.5, 304.5, 343. , 239. , 363.5,
       341.5, 253. , 318.5, 333.5, 367.5, 381.5, 280. , 259. , 302.5,
       357.5, 321. , 363. , 381.5, 285. , 347.5, 286.5, 264. , 217. ,
       299. , 303.5, 187.5, 222. , 329. , 403. , 244.5, 345.5, 341.5,
       296. , 259.5, 314. , 397.5, 349.5, 304.5, 261.5, 363.5, 387.5,
       361. , 328. , 314.5, 325. , 194.5, 231.5, 208. , 323. , 311.5,
       309. , 296. , 248. , 324. , 333. , 358.5, 312.5, 347. , 186.5,
       391. , 254.5, 237. , 286.5, 363. , 281.5, 310. , 275. , 184.5,
       351.5, 271.5, 270. , 364.5, 278. , 254.5, 233.5, 314.5, 347. ,
       320.)
```

```{r}
t.test(pal_median, pf_median)

category = c(rep("PAL", 1000), rep("PF", 1000)) |> as.factor()
df <- data.frame(value = c(pal_median, pf_median), category = category)
ggplot(df, aes(x=value, color=category, fill=category)) +
geom_density(alpha=0.3)
```


#### mean

```{r}
pf_mean <- c()
for(i in 1:1000){
  sim1 <- simulate(t0=0, 
                 times = 1:100, 
                 paramnames = c("beeta", "rho", "gamma", "delta",
                                "pi_0S", "pi_0I", "n",
                                "mu_q","sigma_q"),
                 params = c(beeta=0.8, rho=0.1, gamma=0.2, delta=0.95, 
                            pi_0S=0.99, pi_0I=0.01, 
                            n=10000,
                            mu_q=0.5, sigma_q=0.1),
                 rinit = rinit,
                 rprocess = discrete_time(rproc),
                 rmeasure = rmeas,
                 statenames=c("S","E","I","R","q_I"),
                 obsnames=c("Y_I"))

    (sim_data <- as.data.frame(sim1))
      pf_mean <- c(pf_mean, mean(sim_data$Y_I))
}

```

```{r}
pal_mean <- c(316.81, 304.31, 244.16, 328.38, 312.46, 274.51, 276.15, 263.98,
       329.9 , 256.78, 214.94, 314.02, 260.99, 295.3 , 243.38, 268.9 ,
       346.86, 301.61, 233.22, 369.73, 286.4 , 379.56, 292.86, 251.41,
       349.61, 311.7 , 339.05, 338.93, 260.29, 241.24, 339.25, 317.82,
       313.42, 328.54, 297.11, 341.03, 310.37, 290.04, 233.36, 298.29,
       318.54, 299.72, 264.74, 350.75, 300.18, 234.52, 379.98, 256.37,
       267.77, 328.04, 301.53, 269.5 , 287.48, 289.72, 300.76, 313.25,
       303.67, 354.53, 318.43, 245.23, 354.16, 287.95, 366.75, 314.02,
       322.18, 350.65, 333.6 , 364.06, 295.73, 337.29, 299.62, 281.25,
       299.97, 194.34, 336.07, 244.9 , 241.12, 328.35, 316.81, 342.81,
       307.6 , 275.14, 312.34, 302.77, 356.18, 329.66, 273.11, 256.88,
       325.9 , 389.51, 322.3 , 283.22, 322.21, 294.37, 339.54, 347.47,
       234.16, 319.87, 312.82, 313.09, 288.34, 271.73, 252.35, 328.9 ,
       354.35, 325.54, 251.52, 270.21, 281.27, 350.  , 306.98, 322.15,
       345.45, 306.19, 249.07, 349.36, 286.84, 254.66, 273.  , 243.77,
       255.05, 268.5 , 360.89, 319.25, 322.86, 342.91, 321.25, 273.52,
       276.54, 293.56, 353.09, 292.89, 287.91, 267.33, 267.4 , 326.76,
       279.6 , 328.31, 316.38, 204.35, 289.  , 366.77, 297.05, 304.55,
       310.83, 358.02, 302.54, 347.09, 292.14, 343.86, 344.15, 286.16,
       308.93, 364.99, 298.34, 311.06, 357.12, 256.47, 325.24, 370.09,
       294.56, 254.42, 310.12, 349.9 , 335.86, 333.96, 359.36, 315.84,
       257.75, 324.62, 220.95, 343.01, 306.67, 321.4 , 279.77, 325.31,
       319.4 , 280.52, 328.67, 371.72, 350.98, 316.56, 274.82, 320.64,
       374.3 , 326.48, 294.67, 305.92, 353.66, 335.  , 318.95, 332.48,
       354.84, 291.09, 315.6 , 291.63, 243.42, 342.42, 297.76, 196.1 ,
       300.87, 324.  , 350.16, 311.86, 257.84, 294.21, 264.46, 350.47,
       277.15, 331.85, 311.17, 296.9 , 307.15, 317.09, 358.4 , 346.15,
       342.85, 294.36, 284.61, 373.  , 282.5 , 361.2 , 296.36, 276.97,
       302.8 , 311.33, 334.77, 312.21, 331.56, 287.51, 333.69, 311.44,
       270.01, 337.39, 359.37, 294.47, 263.23, 321.61, 303.4 , 293.49,
       348.78, 344.65, 319.54, 322.4 , 242.33, 254.87, 288.58, 264.53,
       271.7 , 332.84, 322.4 , 289.6 , 351.94, 289.23, 291.68, 361.45,
       316.17, 249.92, 304.46, 331.68, 286.88, 308.3 , 311.07, 274.16,
       247.61, 319.61, 194.04, 295.35, 206.15, 303.64, 311.23, 286.77,
       316.64, 303.23, 303.57, 345.55, 342.83, 286.57, 270.89, 350.42,
       298.84, 297.04, 302.79, 190.75, 280.46, 235.36, 295.88, 327.99,
       332.92, 358.87, 290.85, 286.57, 335.  , 333.21, 308.44, 327.82,
       266.69, 323.73, 324.17, 300.83, 322.87, 340.34, 328.14, 307.15,
       287.12, 359.21, 302.28, 313.45, 268.53, 259.05, 324.59, 324.19,
       253.28, 252.9 , 299.08, 257.55, 345.35, 276.84, 273.59, 237.91,
       304.48, 259.41, 286.76, 223.22, 291.03, 322.02, 343.31, 300.55,
       322.51, 375.2 , 422.14, 316.12, 333.2 , 217.09, 349.92, 383.54,
       307.21, 347.93, 306.89, 342.74, 331.45, 359.93, 284.07, 234.19,
       337.95, 371.53, 247.55, 277.14, 256.35, 268.51, 263.52, 385.33,
       320.17, 332.45, 316.39, 292.11, 383.32, 293.62, 334.13, 338.6 ,
       302.04, 298.63, 347.16, 280.76, 241.92, 253.44, 318.95, 335.44,
       343.14, 326.13, 265.69, 281.6 , 295.49, 287.95, 311.96, 301.57,
       322.66, 310.11, 320.45, 378.71, 340.08, 297.42, 299.28, 391.7 ,
       274.39, 263.38, 348.88, 257.46, 301.28, 276.48, 346.68, 390.51,
       279.  , 292.11, 220.6 , 256.25, 292.03, 314.25, 264.35, 291.61,
       352.87, 337.57, 162.03, 261.44, 291.18, 385.03, 242.43, 280.11,
       308.73, 307.83, 351.28, 276.27, 301.57, 293.97, 296.17, 303.87,
       274.37, 347.45, 350.81, 327.19, 337.18, 267.56, 302.98, 318.44,
       255.16, 298.88, 317.21, 279.71, 364.48, 311.83, 311.94, 280.02,
       312.78, 235.66, 323.14, 259.79, 269.57, 322.4 , 299.37, 292.37,
       271.83, 311.  , 282.36, 283.42, 330.49, 326.52, 290.6 , 314.36,
       299.36, 206.  , 323.37, 369.  , 287.27, 353.44, 298.12, 373.47,
       312.6 , 301.11, 273.32, 347.07, 337.78, 300.45, 367.89, 311.17,
       361.4 , 361.41, 281.95, 346.67, 333.24, 303.37, 328.43, 328.85,
       311.62, 281.76, 257.18, 255.77, 306.45, 334.17, 340.15, 269.81,
       328.3 , 352.11, 313.92, 343.33, 302.73, 258.89, 309.14, 297.62,
       282.65, 309.98, 377.01, 263.11, 393.85, 363.15, 324.07, 347.95,
       321.97, 325.37, 357.61, 323.91, 333.8 , 275.47, 291.94, 311.18,
       251.63, 278.03, 320.29, 356.25, 400.97, 251.24, 320.86, 288.34,
       326.49, 281.81, 285.92, 290.24, 330.23, 230.2 , 305.98, 292.5 ,
       263.99, 357.88, 302.59, 284.83, 284.78, 322.49, 264.14, 220.4 ,
       289.88, 346.81, 258.27, 265.33, 241.33, 327.35, 336.68, 368.95,
       324.38, 342.62, 288.53, 288.68, 307.52, 341.03, 337.95, 284.58,
       284.43, 262.44, 297.84, 233.49, 242.57, 325.52, 279.92, 280.15,
       280.23, 204.19, 261.55, 280.3 , 394.27, 277.26, 282.24, 326.23,
       309.02, 336.43, 360.25, 305.2 , 292.13, 345.31, 311.91, 393.66,
       259.36, 308.83, 237.03, 315.72, 292.21, 224.66, 343.03, 328.16,
       330.17, 260.73, 275.8 , 304.  , 366.03, 257.18, 297.86, 263.84,
       303.84, 259.51, 323.21, 252.32, 345.41, 326.47, 338.33, 291.07,
       313.79, 307.73, 276.96, 274.4 , 351.39, 302.16, 299.07, 325.58,
       247.09, 297.03, 347.9 , 291.39, 344.48, 330.47, 306.45, 298.06,
       247.77, 324.06, 382.1 , 316.04, 316.85, 303.98, 377.98, 337.05,
       310.45, 336.04, 316.69, 333.44, 296.62, 360.44, 282.44, 354.51,
       240.85, 275.78, 245.94, 321.26, 312.16, 275.83, 295.56, 238.45,
       298.29, 282.01, 311.3 , 280.18, 304.94, 384.57, 291.13, 281.37,
       316.42, 354.15, 292.13, 344.47, 331.45, 285.  , 291.07, 228.77,
       309.65, 299.58, 260.89, 226.13, 329.16, 308.28, 297.46, 378.54,
       338.81, 364.84, 211.4 , 323.94, 370.84, 334.01, 310.14, 306.34,
       277.27, 321.24, 320.27, 300.62, 313.51, 342.13, 260.97, 146.95,
       311.64, 248.47, 332.04, 335.89, 334.61, 296.6 , 282.87, 310.09,
       340.78, 327.08, 262.07, 382.36, 296.4 , 324.14, 247.07, 334.08,
       358.1 , 286.97, 275.57, 328.45, 330.44, 306.72, 355.21, 278.01,
       318.89, 321.72, 300.58, 372.34, 325.67, 309.66, 282.01, 349.79,
       347.46, 290.15, 240.02, 344.63, 309.89, 279.02, 305.71, 291.53,
       296.61, 369.7 , 270.73, 280.65, 359.3 , 326.57, 270.33, 355.3 ,
       291.02, 264.7 , 152.66, 280.11, 311.14, 312.84, 279.55, 325.25,
       251.81, 274.29, 295.47, 395.9 , 289.96, 310.3 , 265.99, 282.03,
       304.62, 329.37, 302.08, 328.28, 299.07, 371.48, 249.63, 268.82,
       237.04, 277.35, 253.69, 164.  , 316.02, 277.27, 367.05, 360.59,
       339.58, 238.69, 276.39, 361.92, 324.22, 271.78, 338.51, 240.1 ,
       242.9 , 301.87, 337.99, 272.56, 280.98, 301.1 , 308.4 , 245.28,
       323.22, 245.59, 414.43, 300.93, 294.37, 344.81, 342.98, 288.63,
       312.82, 240.63, 361.54, 271.26, 246.8 , 279.84, 443.41, 334.18,
       288.99, 324.56, 296.49, 323.11, 278.82, 320.56, 283.71, 316.06,
       314.12, 308.58, 343.41, 364.78, 263.9 , 335.63, 314.76, 301.14,
       343.56, 275.34, 322.47, 311.65, 242.07, 377.48, 350.01, 221.41,
       321.17, 279.17, 332.65, 247.43, 327.97, 333.23, 310.51, 267.81,
       259.85, 300.38, 358.43, 299.93, 344.48, 314.82, 313.9 , 298.17,
       241.27, 323.69, 301.72, 328.05, 303.68, 351.87, 250.13, 312.89,
       326.19, 247.62, 197.52, 333.22, 306.35, 321.71, 282.29, 357.21,
       328.07, 289.89, 298.49, 312.73, 286.01, 265.3 , 316.96, 268.25,
       231.35, 305.77, 359.26, 323.89, 351.63, 218.76, 306.51, 330.95,
       331.75, 284.37, 315.71, 247.29, 305.86, 261.25, 329.85, 317.18,
       374.01, 301.28, 218.66, 361.12, 298.51, 241.27, 293.06, 232.  ,
       336.19, 342.47, 352.24, 320.25, 275.59, 394.48, 351.98, 273.32,
       276.42, 252.77, 362.31, 260.27, 207.17, 306.81, 294.75, 276.15,
       320.35, 335.84, 300.14, 298.47, 291.22, 320.13, 276.38, 330.56,
       411.59, 347.77, 195.93, 345.48, 252.09, 403.79, 336.94, 266.79,
       345.36, 321.91, 303.95, 285.4 , 308.89, 278.17, 240.91, 278.85,
       313.8 , 282.06, 188.97, 307.99, 323.31, 288.95, 364.83, 273.49,
       322.07, 325.51, 306.  , 349.32, 254.74, 334.73, 321.74, 213.72,
       264.52, 355.31, 270.24, 317.56, 281.64, 322.25, 248.67, 348.95,
       314.76, 286.27, 330.46, 385.08, 309.72, 290.36, 263.83, 367.14,
       280.23, 291.44, 336.15, 323.06, 290.91, 364.52, 291.85, 342.31,
       272.68, 297.67, 341.25, 344.88, 317.14, 377.53, 368.43, 303.55,
       321.71, 319.05, 302.85, 341.18, 195.72, 339.66, 306.35, 290.37,
       350.33, 222.15, 359.57, 357.86, 351.94, 284.85, 281.02, 326.99,
       303.16, 261.07, 352.7 , 323.57, 298.84, 404.2 , 304.34, 306.73,
       312.35, 323.3 , 290.49, 331.78, 290.25, 322.52, 286.81, 333.88,
       317.06, 339.81, 265.98, 224.88, 169.59, 276.84, 267.21, 325.57)
```

```{r}
t.test(pal_mean, pf_mean)

category = c(rep("PAL", 1000), rep("PF", 1000)) |> as.factor()
df <- data.frame(value = c(pal_mean, pf_mean), category = category)
ggplot(df, aes(x=value, color=category, fill=category)) +
geom_density(alpha=0.3)
```


#### Variance

```{r}
a <- c()
for(i in 1:1000){
  sim1 <- simulate(t0=0, 
                 times = 1:100, 
                 paramnames = c("beeta", "rho", "gamma", "delta",
                                "pi_0S", "pi_0I", "n",
                                "mu_q","sigma_q"),
                 params = c(beeta=0.8, rho=0.1, gamma=0.2, delta=0.95, 
                            pi_0S=0.99, pi_0I=0.01, 
                            n=10000,
                            mu_q=0.5, sigma_q=0.1),
                 rinit = rinit,
                 rprocess = discrete_time(rproc),
                 rmeasure = rmeas,
                 statenames=c("S","E","I","R","q_I"),
                 obsnames=c("Y_I"))

    (sim_data <- as.data.frame(sim1))
      a <- c(a, var(sim_data$Y_I))
}

```

```{r}
pf_var <- a
```

```{r}
pal_var <- c(24056.016 , 20148.268 , 37727.29  , 25584.404 , 28135.14  ,
       40430.72  , 32200.205 , 32884.566 , 45528.02  , 45487.332 ,
       30537.27  , 42440.57  , 45888.61  , 31758.816 , 25948.162 ,
       21554.533 , 31269.95  , 28215.367 , 12633.161 , 60731.117 ,
       24899.695 , 18616.736 , 32824.797 , 12583.683 , 38782.39  ,
       21709.969 , 39625.3   , 41799.527 , 16186.694 , 32313.264 ,
       33421.266 , 38593.312 , 52505.184 , 41998.492 , 49609.14  ,
       12454.637 , 37704.074 , 20434.65  , 30892.2   , 12524.229 ,
       38613.098 , 22932.188 , 31933.125 , 24360.29  , 22275.19  ,
       33583.613 , 29730.082 , 40899.992 , 25819.738 ,  8585.299 ,
       29964.695 , 21936.004 , 37190.203 , 23298.879 , 34776.133 ,
       33817.12  , 27690.87  , 21004.576 , 23440.205 , 31082.715 ,
       26676.162 , 38874.137 , 25333.154 , 35370.176 , 23792.086 ,
       27422.574 , 29557.22  , 44630.68  , 24427.826 ,  3901.6501,
       32172.734 , 11728.544 , 28994.564 , 20047.438 , 23504.395 ,
       22839.07  , 34945.043 , 25666.102 , 16883.174 , 37350.016 ,
       12872.286 , 44291.316 , 30443.004 , 18808.783 , 24616.174 ,
       11410.736 , 18872.533 , 28631.965 , 31468.295 , 34004.4   ,
       15314.935 , 39115.19  , 25478.172 , 31609.45  , 27304.936 ,
       45855.562 , 25703.678 , 28981.941 , 28664.717 , 36278.715 ,
       30740.432 , 14009.16  , 16392.02  , 21231.129 , 33008.38  ,
       19886.217 , 29338.752 , 40852.92  , 10616.156 , 33478.168 ,
       39914.008 , 27861.969 , 46766.867 , 48764.977 , 30678.127 ,
       37794.605 , 27625.979 , 35187.59  , 32209.238 , 35478.047 ,
       20068.957 , 45497.26  , 47634.555 , 19608.248 , 29568.455 ,
       18901.094 , 22589.514 , 26998.062 , 27654.014 , 31056.252 ,
       34580.324 , 41778.094 , 28418.916 , 18115.352 , 34837.785 ,
       48880.02  , 27323.08  , 33401.72  , 36915.668 ,  9893.504 ,
       30695.947 , 26616.283 , 23790.709 , 12263.503 , 12852.506 ,
       26963.436 ,  9952.689 ,  9107.624 , 34928.406 , 28894.01  ,
       22215.031 , 30036.838 , 30526.352 , 36361.926 , 41894.85  ,
       21601.904 , 23685.098 , 24072.037 , 45225.312 , 25588.592 ,
       29268.22  , 26002.03  , 44339.484 , 21386.795 , 16042.027 ,
       32144.85  , 20320.377 , 31984.098 , 19553.482 , 16478.139 ,
       14958.755 , 33150.926 , 11297.879 , 25391.59  , 26726.908 ,
       21778.26  , 29760.436 , 34093.16  , 38605.9   , 10336.991 ,
       18445.08  , 25579.389 , 27314.57  , 16534.969 , 32170.785 ,
       47534.1   , 45094.06  , 34625.92  , 45380.32  , 19686.156 ,
       43485.766 , 27939.07  , 27743.92  , 26969.21  , 27516.832 ,
       39330.195 , 20973.514 , 17341.309 , 33491.746 , 17652.947 ,
       17711.893 , 31884.17  , 18685.03  , 44979.44  , 28083.523 ,
       37026.598 , 31123.098 , 16554.924 , 12129.173 , 26180.111 ,
       16112.051 , 23655.799 , 19402.074 , 44254.5   , 14952.486 ,
       20831.146 , 14797.503 , 32452.94  , 46252.11  , 24999.38  ,
       12532.898 , 22224.453 , 11623.283 , 30919.941 , 25446.027 ,
       22436.613 , 24573.54  , 24738.502 , 34187.066 , 26706.852 ,
       27844.357 , 47973.01  , 35367.574 , 44066.05  , 65865.64  ,
       20485.322 , 31196.64  , 18634.717 , 22766.03  , 28344.736 ,
       33708.773 , 30502.885 , 26732.455 , 13562.656 , 31052.807 ,
       25495.291 , 27554.613 , 25265.293 , 25101.092 , 20644.111 ,
       40437.92  , 35208.773 , 30875.816 , 43033.598 , 23539.975 ,
       19002.484 , 15450.796 , 35051.055 , 44084.793 , 28713.684 ,
       11625.389 , 39670.516 , 20404.31  , 24586.982 , 53152.22  ,
       39528.887 ,  8079.2817, 17639.92  , 19633.1   , 34495.867 ,
       29855.    , 37855.88  , 25431.254 , 31528.162 , 32270.191 ,
       33447.746 , 20372.984 , 14217.119 , 26468.781 , 10534.692 ,
       35393.81  , 38479.55  , 15425.105 , 22740.574 , 16487.92  ,
       17240.77  ,  5078.7754, 47528.402 , 20499.207 , 22680.793 ,
       22039.562 , 29492.633 , 21620.182 , 26838.541 , 30990.902 ,
       34844.742 , 11038.906 , 40089.93  , 27127.861 , 23408.912 ,
       30277.988 , 24565.602 , 57159.008 , 26323.691 , 17226.146 ,
        8023.719 , 21201.059 , 18308.078 , 33800.54  , 22128.822 ,
       23347.236 , 30433.562 , 32061.744 , 58121.656 , 29767.48  ,
       35978.508 , 33250.113 , 22556.578 , 40948.35  , 25832.56  ,
       37235.656 , 20970.66  , 22380.785 , 16189.432 , 34000.555 ,
       31764.8   , 14795.099 , 45049.188 , 20498.89  , 34958.883 ,
       22291.78  , 35948.637 , 28184.223 , 35868.977 , 57157.7   ,
       37609.523 , 27544.615 , 35539.71  , 40341.08  , 35051.42  ,
       17861.924 , 16301.436 , 21648.105 , 32896.83  , 21042.25  ,
       16279.596 , 17077.967 , 36464.23  , 15761.141 , 26481.764 ,
       17186.494 , 60301.87  , 26639.305 , 36863.727 , 39612.684 ,
       34306.758 , 38506.76  , 26322.986 , 36037.723 , 32104.645 ,
       33194.91  , 18404.229 , 13586.66  , 21559.12  , 25221.26  ,
       17811.98  , 34135.16  , 16708.28  ,  4447.038 , 28720.586 ,
       41513.42  , 31224.1   , 27456.838 , 28803.95  , 27178.92  ,
       25897.486 , 36520.82  , 37554.93  , 24608.72  , 29857.07  ,
       23079.807 , 20359.28  , 35922.09  , 18870.05  , 27490.656 ,
       24667.988 , 26419.623 , 27704.914 , 24987.64  ,  8000.272 ,
       24350.805 , 41277.97  , 29399.441 , 36421.85  , 24958.215 ,
       18669.889 , 20710.502 , 29926.252 , 36482.9   , 19073.865 ,
       29699.281 , 14048.712 , 28818.68  , 41159.97  , 20068.074 ,
       23611.846 , 15424.626 , 31877.389 , 18901.104 , 43839.547 ,
       26820.492 , 15855.7   , 22618.88  , 21263.613 , 31760.41  ,
       19517.646 , 41748.53  , 25011.777 , 37781.02  , 41651.996 ,
       14884.324 , 16790.39  , 29667.951 , 24481.125 , 12149.419 ,
       17964.13  , 22364.799 , 26734.354 , 36496.54  , 33132.168 ,
       26231.74  , 26732.283 , 36409.355 , 24685.086 , 22254.154 ,
       16909.604 , 35779.7   , 32890.945 , 45610.23  , 24920.523 ,
       27975.549 , 31556.654 , 40719.59  , 39301.547 , 24527.33  ,
       27398.396 , 34402.11  , 13795.822 , 19789.953 , 34127.406 ,
       14312.53  , 29132.846 , 36068.79  , 19701.861 , 27054.607 ,
       30300.42  , 28585.137 , 17061.371 , 29320.809 , 41651.45  ,
       29967.818 , 34128.758 ,  9874.817 , 28176.504 , 35161.19  ,
       25952.629 , 27147.977 , 21534.27  , 21830.586 , 28557.564 ,
       33146.49  , 21739.988 , 26116.678 , 53571.56  , 19217.094 ,
        7758.7   , 30008.166 , 23924.521 , 46737.316 , 30628.852 ,
       13774.914 , 33249.89  , 21271.67  , 23036.203 , 14778.81  ,
       32725.553 , 35283.137 , 27718.055 , 15790.257 , 41531.65  ,
       27399.229 , 39337.05  , 43445.42  , 23196.111 , 28804.98  ,
       29060.756 , 46575.152 , 15615.279 , 41819.25  , 26592.635 ,
       31441.455 , 47981.383 , 25892.215 , 39534.027 , 25693.05  ,
       19726.854 , 28422.363 , 24380.008 , 18236.338 , 44158.496 ,
       23900.89  ,  7305.3735, 32907.613 , 13272.48  , 37883.02  ,
       26956.535 ,  7445.828 , 13545.367 , 19467.658 , 22964.3   ,
       13018.176 , 18528.13  , 37883.496 , 14403.103 , 27660.686 ,
       21896.693 , 18425.05  , 29708.572 , 36309.703 , 30678.297 ,
       28668.494 , 24591.744 , 29123.857 , 33845.566 , 21940.64  ,
       39997.7   , 19019.88  , 20170.027 , 26486.305 , 22740.896 ,
       23324.482 , 25251.36  , 33682.883 , 20189.38  , 41733.36  ,
       31760.486 , 36546.332 , 39647.8   , 40336.965 , 31542.768 ,
       34983.32  , 35649.26  , 47552.434 , 17682.252 , 31155.969 ,
       23785.795 , 32336.201 , 24829.08  , 23974.422 , 23103.379 ,
       16901.035 , 23934.32  , 31263.668 , 34506.066 , 14632.111 ,
       30105.014 , 10256.321 , 27531.854 , 33617.684 , 19883.064 ,
       18010.412 , 33993.79  , 25197.674 , 33414.53  , 35434.02  ,
       32035.896 , 23012.99  , 28572.635 , 22295.992 , 11434.611 ,
       18086.408 , 38591.098 , 28353.975 , 16098.129 , 15622.14  ,
       38385.434 , 23073.424 , 25025.482 , 14131.59  , 36240.14  ,
       15542.979 , 29770.566 , 24095.22  , 10077.255 , 17045.506 ,
       11333.808 , 24761.78  , 31368.09  , 23348.033 , 31282.49  ,
       28299.014 , 11171.92  , 36597.645 , 32101.363 , 32748.229 ,
       27035.688 , 26226.252 , 15312.853 , 27513.078 , 30759.182 ,
       16400.23  , 35450.293 , 28814.422 , 30514.05  , 34771.086 ,
       28436.324 , 19430.834 , 18244.34  , 30025.66  , 45494.234 ,
       15483.46  , 37549.18  , 31126.898 , 31424.066 , 26814.486 ,
       34044.12  , 26550.207 , 22133.31  , 33161.28  , 39962.457 ,
       29292.244 , 25572.82  , 24458.482 , 18235.    , 22105.133 ,
       35784.574 , 26004.688 , 23672.092 , 21887.47  , 10549.725 ,
       13847.578 , 18910.693 , 30529.723 , 16902.527 , 17312.787 ,
       16517.305 , 37723.87  , 18858.13  , 29652.879 , 43780.336 ,
       34673.29  , 19479.805 , 33696.254 , 26783.484 , 23935.46  ,
       35741.277 , 33590.168 , 26797.684 , 24117.951 , 15053.982 ,
       32034.205 , 29835.28  , 28212.014 , 24271.676 , 30205.186 ,
       26538.943 , 32733.957 , 38091.266 , 22504.2   , 14879.904 ,
       33338.773 , 30222.576 , 49846.016 , 17192.035 , 29303.418 ,
       35956.953 , 29028.105 , 36145.344 , 30842.809 , 22968.523 ,
       22458.877 , 33672.574 , 24325.707 , 30218.53  , 24532.139 ,
       37001.625 , 21010.492 , 38200.86  , 13384.692 , 18591.156 ,
       34158.523 , 46194.734 ,  8623.831 , 26352.838 , 24082.098 ,
       28521.777 , 31812.559 , 32148.883 , 36475.1   , 10608.59  ,
       12596.298 , 12843.63  , 21341.559 , 34134.55  , 16756.068 ,
       27593.717 , 32621.857 , 46737.426 , 27494.32  , 22288.393 ,
       33736.793 , 28482.059 , 31309.197 , 13696.411 , 42420.9   ,
       42599.59  , 40593.793 , 21743.45  , 23006.22  , 13641.381 ,
       27414.967 , 34395.84  , 14019.9375, 34649.523 , 26692.758 ,
       10156.715 , 29202.414 , 23301.79  , 34295.637 , 20774.77  ,
       35116.31  , 25947.816 , 27192.72  , 25891.506 , 22934.402 ,
       14161.375 , 12003.761 , 19955.625 ,  9719.061 , 34216.91  ,
       21346.07  , 28930.342 , 19808.303 , 38061.605 , 24097.756 ,
       16222.513 , 37173.156 , 11259.685 , 29468.26  , 27118.305 ,
       27906.436 , 30928.605 , 41917.406 , 34578.016 , 38313.457 ,
       35228.484 , 43884.168 , 44811.38  , 30976.08  , 44485.77  ,
       23757.65  , 29275.414 , 33147.89  , 50920.25  , 21881.367 ,
       45119.43  , 30400.955 , 45152.79  , 14790.397 , 15643.687 ,
       39944.562 , 19889.46  , 15090.182 , 34643.22  , 18068.844 ,
       13161.952 , 38852.35  , 36684.902 , 15537.987 , 39122.055 ,
       52472.09  , 36863.406 , 18116.291 , 25930.441 , 22051.766 ,
       27884.191 , 37273.945 , 37754.535 , 15534.065 , 43294.797 ,
       24267.623 , 11120.841 , 42060.617 , 30153.479 , 20157.514 ,
       17325.148 , 38501.95  , 18876.91  , 21797.48  , 24895.938 ,
       21432.988 , 22422.25  , 24847.385 , 20670.293 , 20951.36  ,
       45653.125 , 20253.072 , 36083.95  , 28429.402 , 23549.74  ,
       25795.723 , 31909.354 , 40607.293 , 36459.184 , 16624.994 ,
       12362.615 , 34150.938 , 22501.244 , 30134.695 , 28730.25  ,
        7270.636 , 35502.023 , 42322.04  , 31482.232 , 19394.066 ,
       24326.855 , 36264.05  , 25935.734 , 26856.24  , 14844.051 ,
       24288.002 , 41815.758 , 22047.266 , 27752.777 , 27246.316 ,
       40650.93  , 27188.768 , 32491.416 , 43449.76  , 29102.967 ,
       15949.453 , 23040.38  , 36746.613 , 32615.902 , 33140.91  ,
       33316.52  , 41386.875 , 28612.49  , 19046.11  , 33434.84  ,
       35863.24  , 22627.2   , 34673.99  , 20373.957 , 21441.02  ,
       29903.87  , 34449.26  , 20176.438 , 25252.99  , 35189.637 ,
       24337.848 , 27011.455 , 31460.605 , 28686.113 , 47304.74  ,
       52972.004 , 30311.525 , 25032.2   , 14655.638 , 14946.565 ,
       34003.797 , 33282.848 , 42079.85  , 13999.624 , 18014.838 ,
       27420.412 , 28102.877 , 25314.922 , 46167.527 , 38162.312 ,
       33822.895 , 28912.52  , 42263.44  , 38694.477 , 27911.443 ,
       10738.922 , 18914.504 , 51214.902 , 12668.5625, 32176.486 ,
       25848.104 , 16721.428 , 35250.977 , 29683.57  , 41190.664 ,
       23716.303 , 13849.602 , 30669.428 , 16235.139 , 20141.016 ,
       25795.4   , 26015.031 , 43104.44  , 22535.436 , 34351.016 ,
       22754.09  , 41596.21  , 34304.645 , 36363.906 , 31704.52  ,
       16267.213 , 35128.387 , 21000.924 , 38688.117 , 21688.32  ,
       20050.932 , 21420.553 , 22306.826 , 32353.832 , 26415.912 ,
       22141.098 , 26396.066 ,  7482.539 , 35483.46  , 46623.06  ,
       36075.09  , 45609.66  , 30792.096 , 20424.627 , 42853.625 ,
       28228.475 , 12363.048 , 32897.727 , 30972.02  , 35781.598 ,
       35246.266 , 16525.031 , 31612.76  , 40791.754 , 39397.242 ,
       36186.758 ,  9102.95  , 35650.676 , 35064.9   , 44154.613 ,
       27328.922 , 41842.617 , 33208.73  , 25671.445 , 17942.9   ,
        8775.109 , 33714.035 , 28887.58  , 29956.656 , 36305.625 ,
       22272.66  , 19905.062 , 27425.355 , 24961.145 , 22292.766 ,
       33648.047 , 26634.389 , 34591.668 , 22611.873 , 37543.32  ,
       25807.504 , 32919.254 , 33147.38  , 30582.314 , 29914.06  ,
       26329.043 , 31994.906 , 21066.531 , 19689.73  , 16871.852 ,
       40128.965 , 43576.543 , 21148.39  , 34573.92  , 20182.352 ,
       17017.188 , 30392.87  , 19681.467 , 31684.877 , 33873.617 ,
       17782.41  , 28390.293 , 32032.328 , 31137.535 , 30114.037 ,
       32416.918 , 35516.547 , 14454.039 , 27557.092 , 25073.715 ,
       24976.816 , 38140.277 , 33947.125 , 27218.227 , 30488.451)
```

```{r}
t.test(pal_var, pf_var)

category = c(rep("PAL", 1000), rep("PF", 1000)) |> as.factor()
df <- data.frame(value = c(pal_var, pf_var), category = category)
ggplot(df, aes(x=value, color=category, fill=category)) +
geom_density(alpha=0.3)
```


### Compare Likelihood:

```{r}
rproc <- Csnippet("
    double rate[3], trans[7];
    double N = S+E+I+R;
    double xi = rgammawn(1,dt);
    // True death is not by expon rate, but binomial probability.
    rate[0] = -xi*beeta*I/N;    // stochastic force of infection
    rate[1] = -rho;         // rho is our original sigma
    rate[2] = -gamma;      // recovery
    
    // die first before transit
    trans[1] = rbinom(S, delta);
    trans[3] = rbinom(E, delta);
    trans[5] = rbinom(I, delta);
    trans[6] = rbinom(R, delta);
    
    trans[0] = rbinom(trans[1], 1-exp(rate[0]));
    trans[2] = rbinom(trans[3], 1-exp(rate[1]));
    trans[4] = rbinom(trans[5], 1-exp(rate[2]));
    
    // with birth case
    S = trans[1] - trans[0] + rpois(0.05*pi_0S*N);
    E = trans[3] + trans[0] - trans[2];
    I = trans[5] + trans[2] - trans[4] + rpois(0.05*pi_0I*N);
    R = trans[6] + trans[4]; 
    
    q_I = -1;
  
    while(q_I<0 || q_I>1){
    q_I = rnorm(mu_q, sigma_q);
    }
")

## ----rinit-------------------------------------------------
rinit <- Csnippet("
  double pi_0[4]={pi_0S,0,pi_0I,0}; // pi_0 should be specified
  int trans_0[4];

  rmultinom(n, &pi_0, 4, &trans_0);
  S = trans_0[0];
  E = trans_0[1];
  I = trans_0[2];
  R = trans_0[3];
")


## ----rmeasure-------------------------------------------------
rmeas <- Csnippet("
  Y_I = rbinom(I, q_I); // this is observed cases
")

dmeas <- Csnippet("
  lik = dbinom(Y_I, I, q_I, 1);
")
```

```{r}
Y_pal <- c(45.,  18.,  28.,  30.,  23.,  25.,  39.,  25.,  27.,  44.,  31.,
        26.,  33.,  44.,  52.,  77.,  87.,  89.,  64.,  75.,  89., 118.,
        77.,  74.,  72., 144., 113., 101., 119., 118., 146., 129., 135.,
       175., 208., 167., 233., 261., 189., 238., 216., 192., 238., 187.,
       199., 136., 202., 151., 291., 150., 268., 296., 395., 306., 295.,
       305., 377., 382., 518., 346., 478., 537., 458., 504., 333., 475.,
       530., 181., 337., 412., 352., 327., 319., 277., 280., 284., 357.,
       302., 266., 345., 364., 483., 360., 308., 293., 375., 298., 406.,
       154., 252., 327., 352., 184., 505., 351., 308., 333., 267., 378.,
       304.)
```

```{r}
dat <- data.frame(time = c(1:100), Y_I = Y_pal)
 
dat |>
  pomp(t0=0,
    time="time",
    rprocess=discrete_time(rproc),
    rinit=rinit,
    dmeasure=dmeas,
    rmeasure=rmeas,
    statenames=c("S","E","I","R","q_I"),
    paramnames=c("beeta", "rho", "gamma", "delta",
                                "pi_0S", "pi_0I", "n",
                                "mu_q","sigma_q")
  ) -> m1

theta <- c(beeta=0.8, rho=0.1, gamma=0.2, delta=0.95, 
                            pi_0S=0.99, pi_0I=0.01, 
                            n=10000,
                            mu_q=0.5, sigma_q=0.1)

lik_pf <- c()

for(i in 1:5){
  plan(multicore)
  foreach(i=1:4, .combine=c,
    .options.future=list(seed=998468235L+3382*i)
  ) %dopar% {
    pfilter(m1,Np=10000,params=theta)
  } -> pfs
  ## ----pfilter1b-----------------------------------------------
  lik_pf[i] <- logmeanexp(logLik(pfs),se=F)
}

lik_pf
```