---
title: "Untitled"
author: "Yize Hao"
date: "2024-04-20"
output: html_document
---

```{r}
load("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/OvOv/mif2/pfilter together/filtered_list_36.Rdata")
load("~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/OvOv/Filtering/condlik/real_rotavirus_metadata.Rdata")
```


#### plot 36 replicates together with observation

```{r}
time <- c(1:416)

plot(time, realdat[time,1], type = "l", col="green", pch="", lty=1)
lines(time, realdat[time,2], type = "l", col="red", pch="", lty=1)
lines(time, realdat[time,3], type = "l", col="blue", pch="", lty=1)

for(i in 1:36){
  lines(time, 0.07*filtered_list[[i]][time,1], col="#003300",lty=1)
  lines(time, 0.07*filtered_list[[i]][time,2], col="#990033",lty=1)
  lines(time, 0.07*filtered_list[[i]][time,3], col="#000099",lty=1)
}

# points(seq(from = 1, to = 416 ,by=10), rep(-150, times=42), col="black", pch="*")
# lines(time, rep(-150, times=416), col="black", lty=1)
# legend("bottomright",               # position of the legend
#        legend = c("SMC", "PAL"),  # labels
#        col = c("blue", "red"),    # colors
#        pch = c(19,17), cex=0.5)   
```



```{r}
upper <- matrix(nrow=416,ncol=3)
lower <- matrix(nrow=416,ncol=3)
avg <- matrix(nrow=416,ncol=3)
for(i in 2:417){
  x <- matrix(nrow=36,ncol=3)
  for(j in 1:36){
    x[j, ] <- filtered_list[[j]][i, ]
  }
  for(k in 1:3){
  avg[i-1, k] <- mean(x[,k])
  upper[i-1, k] <- quantile(x[,k], 0.975)
  lower[i-1, k] <- quantile(x[,k], 0.025)
  }
}

my_time <- c(1:50)
avg <- data.frame(cases1 = avg[my_time,1],
                  cases2 = avg[my_time,2],
                  cases3 = avg[my_time,3])
upper <- data.frame(cases1 = upper[my_time,1],
                    cases2 = upper[my_time,2],
                    cases3 = upper[my_time,3])
lower <- data.frame(cases1 = lower[my_time,1],
                    cases2 = lower[my_time,2],
                    cases3 = lower[my_time,3])

melt_avg <- melt(avg, value.name = "Mean", id=c())
melt_upper <- melt(upper, value.name = "Upper-quantile", id=c())
melt_lower <- melt(lower, value.name = "Lower-quantile", id=c())

my_data <- data.frame(time = rep(my_time, 3),
                      Group=melt_avg$variable, 
                      Mean=0.07*melt_avg$Mean,
                      Upper_quantile = 0.07*melt_upper$`Upper-quantile`,
                      Lower_quantile = 0.07*melt_lower$`Lower-quantile`,
                      cases_report = c(realdat[my_time, 1], realdat[my_time,2],realdat[my_time,3]))


ggplot(data=my_data, aes(x=time, y=Mean, colour=Group)) +  geom_line(alpha=0.3) +
  geom_line(aes(x=time, y=cases_report)) + 
  geom_ribbon(aes(ymin=Lower_quantile, ymax=Upper_quantile), linetype=2, alpha=0.1) 
```

#### Outlier plot

```{r}
my_time <- c(1:20)

upper <- matrix(nrow=416,ncol=3)
lower <- matrix(nrow=416,ncol=3)
avg <- matrix(nrow=416,ncol=3)
for(i in 2:417){
  x <- matrix(nrow=36,ncol=3)
  for(j in 1:36){
    x[j, ] <- filtered_list[[j]][i, ]
  }
  for(k in 1:3){
  avg[i-1, k] <- mean(x[,k])
  upper[i-1, k] <- quantile(x[,k], 0.975)
  lower[i-1, k] <- quantile(x[,k], 0.025)
  }
}

avg <- data.frame(cases1 = avg[my_time,1],
                  cases2 = avg[my_time,2],
                  cases3 = avg[my_time,3])
upper <- data.frame(cases1 = upper[my_time,1],
                    cases2 = upper[my_time,2],
                    cases3 = upper[my_time,3])
lower <- data.frame(cases1 = lower[my_time,1],
                    cases2 = lower[my_time,2],
                    cases3 = lower[my_time,3])

melt_avg <- melt(avg, value.name = "Mean", id=c())
melt_upper <- melt(upper, value.name = "Upper-quantile", id=c())
melt_lower <- melt(lower, value.name = "Lower-quantile", id=c())

my_data <- data.frame(time = rep(my_time, 3),
                      Group=melt_avg$variable, 
                      Cases=0.07*melt_avg$Mean,
                      Upper_quantile = (0.02899003)*melt_upper$`Upper-quantile`,
                      Lower_quantile = (0.1111631)*melt_lower$`Lower-quantile`,
                      cases_report = c(realdat[my_time, 1], realdat[my_time,2],realdat[my_time,3]))


p1 <- ggplot(data=my_data, aes(x=time, y=Cases, colour=Group))  +
  geom_line(aes(x=time, y=cases_report)) + 
  geom_ribbon(aes(ymin=Lower_quantile, ymax=Upper_quantile), linetype=2, alpha=0.1) 


my_time <- c(75:85)

upper <- matrix(nrow=416,ncol=3)
lower <- matrix(nrow=416,ncol=3)
avg <- matrix(nrow=416,ncol=3)
for(i in 2:417){
  x <- matrix(nrow=36,ncol=3)
  for(j in 1:36){
    x[j, ] <- filtered_list[[j]][i, ]
  }
  for(k in 1:3){
  avg[i-1, k] <- mean(x[,k])
  upper[i-1, k] <- quantile(x[,k], 0.975)
  lower[i-1, k] <- quantile(x[,k], 0.025)
  }
}

avg <- data.frame(cases1 = avg[my_time,1],
                  cases2 = avg[my_time,2],
                  cases3 = avg[my_time,3])
upper <- data.frame(cases1 = upper[my_time,1],
                    cases2 = upper[my_time,2],
                    cases3 = upper[my_time,3])
lower <- data.frame(cases1 = lower[my_time,1],
                    cases2 = lower[my_time,2],
                    cases3 = lower[my_time,3])

melt_avg <- melt(avg, value.name = "Mean", id=c())
melt_upper <- melt(upper, value.name = "Upper-quantile", id=c())
melt_lower <- melt(lower, value.name = "Lower-quantile", id=c())

my_data <- data.frame(time = rep(my_time, 3),
                      Group=melt_avg$variable, 
                      Cases=0.07*melt_avg$Mean,
                      Upper_quantile = (0.02899003)*melt_upper$`Upper-quantile`,
                      Lower_quantile = (0.1111631)*melt_lower$`Lower-quantile`,
                      cases_report = c(realdat[my_time, 1], realdat[my_time,2],realdat[my_time,3]))


p2 <- ggplot(data=my_data, aes(x=time, y=Cases, colour=Group))  +
  geom_line(aes(x=time, y=cases_report)) + 
  geom_ribbon(aes(ymin=Lower_quantile, ymax=Upper_quantile), linetype=2, alpha=0.1) 

my_time <- c(190:200)

upper <- matrix(nrow=416,ncol=3)
lower <- matrix(nrow=416,ncol=3)
avg <- matrix(nrow=416,ncol=3)
for(i in 2:417){
  x <- matrix(nrow=36,ncol=3)
  for(j in 1:36){
    x[j, ] <- filtered_list[[j]][i, ]
  }
  for(k in 1:3){
  avg[i-1, k] <- mean(x[,k])
  upper[i-1, k] <- quantile(x[,k], 0.975)
  lower[i-1, k] <- quantile(x[,k], 0.025)
  }
}

avg <- data.frame(cases1 = avg[my_time,1],
                  cases2 = avg[my_time,2],
                  cases3 = avg[my_time,3])
upper <- data.frame(cases1 = upper[my_time,1],
                    cases2 = upper[my_time,2],
                    cases3 = upper[my_time,3])
lower <- data.frame(cases1 = lower[my_time,1],
                    cases2 = lower[my_time,2],
                    cases3 = lower[my_time,3])

melt_avg <- melt(avg, value.name = "Mean", id=c())
melt_upper <- melt(upper, value.name = "Upper-quantile", id=c())
melt_lower <- melt(lower, value.name = "Lower-quantile", id=c())

my_data <- data.frame(time = rep(my_time, 3),
                      Group=melt_avg$variable, 
                      Cases=0.07*melt_avg$Mean,
                      Upper_quantile = (0.02899003)*melt_upper$`Upper-quantile`,
                      Lower_quantile = (0.1111631)*melt_lower$`Lower-quantile`,
                      cases_report = c(realdat[my_time, 1], realdat[my_time,2],realdat[my_time,3]))


p3 <- ggplot(data=my_data, aes(x=time, y=Cases, colour=Group))  +
  geom_line(aes(x=time, y=cases_report)) + 
  geom_ribbon(aes(ymin=Lower_quantile, ymax=Upper_quantile), linetype=2, alpha=0.1) 

my_time <- c(320:340)

upper <- matrix(nrow=416,ncol=3)
lower <- matrix(nrow=416,ncol=3)
avg <- matrix(nrow=416,ncol=3)
for(i in 2:417){
  x <- matrix(nrow=36,ncol=3)
  for(j in 1:36){
    x[j, ] <- filtered_list[[j]][i, ]
  }
  for(k in 1:3){
  avg[i-1, k] <- mean(x[,k])
  upper[i-1, k] <- quantile(x[,k], 0.975)
  lower[i-1, k] <- quantile(x[,k], 0.025)
  }
}

avg <- data.frame(cases1 = avg[my_time,1],
                  cases2 = avg[my_time,2],
                  cases3 = avg[my_time,3])
upper <- data.frame(cases1 = upper[my_time,1],
                    cases2 = upper[my_time,2],
                    cases3 = upper[my_time,3])
lower <- data.frame(cases1 = lower[my_time,1],
                    cases2 = lower[my_time,2],
                    cases3 = lower[my_time,3])

melt_avg <- melt(avg, value.name = "Mean", id=c())
melt_upper <- melt(upper, value.name = "Upper-quantile", id=c())
melt_lower <- melt(lower, value.name = "Lower-quantile", id=c())

my_data <- data.frame(time = rep(my_time, 3),
                      Group=melt_avg$variable, 
                      Cases=0.07*melt_avg$Mean,
                      Upper_quantile = (0.02899003)*melt_upper$`Upper-quantile`,
                      Lower_quantile = (0.1111631)*melt_lower$`Lower-quantile`,
                      cases_report = c(realdat[my_time, 1], realdat[my_time,2],realdat[my_time,3]))


p4 <- ggplot(data=my_data, aes(x=time, y=Cases, colour=Group))  +
  geom_line(aes(x=time, y=cases_report)) + 
  geom_ribbon(aes(ymin=Lower_quantile, ymax=Upper_quantile), linetype=2, alpha=0.1) 

png(file="~/Study/STATS 489/PAL-check/rotavirus/results/Simulation_Study/Simulation+Comparison/OvOv/mif2/zoomed_in_outlier_plot.png", height = 800, width=800)
ggarrange(p1,p2,p3,p4,nrow=2,ncol=2)
dev.off()
```
