---
title: "Rotavirus Model"
author: "Yize Hao"
date: "2023-10-19"
output: html_document
---

```{r}
rm(list = ls())     # clear objects  
graphics.off()      # close graphics windows
library(pomp)
library(doFuture)
library(ggplot2)
```

#### Model

```{r}
rproc <- Csnippet("
    double gamma = 1.0;
    double d_1=1/(5.0*52.0);           // d1 = 0.003846154
    double d_2=1/(55.0*52.0);          // d2 = 0.0003496503
    double N = 82372825;
    double alpha = 1/(78.86912*52.0);  // alpha = 0.0002438314
    double delta = 1 - 1/(18.86912*52.0);  // delta = 0.9989808
    double omega = 1/(1.0*52.0);         // omega = 0.01923077
    
    int I = I_1 + I_2 + I_3;
    int trans_S1[3], trans_S2[3], trans_S3[2], trans_I1[3], trans_I2[3], trans_I3[2], trans_R1[3], trans_R2[3], trans_R3[2];
    
    double prob_S1[3],prob_I1[3],prob_R1[3],prob_S2[3],prob_I2[3],prob_R2[3],prob_S3[2],prob_I3[2],prob_R3[2];
    
    double kappa = (1 + rho*cos(2*3.141593*t/52 + phi));
    double Beta_1 = beta1*kappa; //seasonal forcing
    double Beta_2 = beta2*kappa; //seasonal forcing
    double Beta_3 = beta3*kappa; //seasonal forcing
    
    // Define rate
    prob_S1[0] = 1-exp(-Beta_1*I/N*dt);
    prob_S1[1] = 1-exp(-dt*d_1);
    prob_S1[2] = exp(-dt*d_1) + exp(-Beta_1*I/N*dt) - 1;
    
    prob_I1[0] = 1-exp(-dt*gamma);
    prob_I1[1] = 1-exp(-dt*d_1);
    prob_I1[2] = exp(-dt*gamma)+exp(-dt*d_1) - 1;
    
    prob_R1[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R1[1] = 1 - exp(-dt*d_1);
    prob_R1[2] = exp(-dt*omega) + exp(-dt*d_1) - 1;
    
    prob_S2[0] = 1-exp(-Beta_2*I/N*dt);
    prob_S2[1] = 1-exp(-dt*d_2);
    prob_S2[2] = exp(-dt*d_2) + exp(-Beta_2*I/N*dt) - 1;
    
    prob_I2[0] = 1-exp(-dt*gamma);
    prob_I2[1] = 1-exp(-dt*d_2);
    prob_I2[2] = exp(-dt*gamma)+exp(-dt*d_2) - 1;
    
    prob_R2[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R2[1] = 1 - exp(-dt*d_1);
    prob_R2[2] = exp(-dt*omega) + exp(-dt*d_1) - 1;
    
    // For Age Group (3): Die first before transition;
    
    double S3mD = rbinom(S_3, delta);
    double I3mD = rbinom(I_3, delta);
    double R3mD = rbinom(R_3, delta);
    
    prob_S3[0] = 1-exp(-Beta_3*I/N*dt);
    prob_S3[1] = exp(-Beta_3*I/N*dt);
    
    prob_I3[0] = 1 - exp(-dt*gamma);
    prob_I3[1] = exp(-dt*gamma);
    
    prob_R3[0] = 1 - exp(-dt*omega);
    prob_R3[1] = exp(-dt*omega);
    
    // Transition
    // B: S->I
    // C: I->R
    // F: Aging: (1)->(2)->(3)
    // E: R->S
    // D: Death
    //// Note: Here S_1, S_2... are all old value from (t-1)
    rmultinom(S_1, &prob_S1, 3, &trans_S1); // B, F, S-B-F
    rmultinom(I_1, &prob_I1, 3, &trans_I1); // C, F, I-C-F
    rmultinom(R_1, &prob_R1, 3, &trans_R1); // E, F, R-E-F
    
    rmultinom(S_2, &prob_S2, 3, &trans_S2); // B, F, S-B-F
    rmultinom(I_2, &prob_I2, 3, &trans_I2); // C, F, I-C-F
    rmultinom(R_2, &prob_R2, 3, &trans_R2); // E, F, R-E-F
    
    rmultinom(S3mD, &prob_S3, 2, &trans_S3); // B, (S-D)-B
    rmultinom(I3mD, &prob_I3, 2, &trans_I3); // C, (I-D)-C
    rmultinom(R3mD, &prob_R3, 2, &trans_R3); // E, (R-D)-E
    
    S_1 = trans_S1[2] + trans_R1[0] + rpois(alpha*N*dt); // Include Birth
    I_1 = trans_I1[2] + trans_S1[0];
    R_1 = trans_R1[2] + trans_I1[0];
    
    S_2 = trans_S2[2] + trans_R2[0] + trans_S1[1]; // Include Aging
    I_2 = trans_I2[2] + trans_S2[0] + trans_I1[1];
    R_2 = trans_R2[2] + trans_I2[0] + trans_R1[1];
    
    S_3 = trans_S3[1] + trans_R3[0] + trans_S2[1]; // Include Aging
    I_3 = trans_I3[1] + trans_S3[0] + trans_I2[1];
    R_3 = trans_R3[1] + trans_I3[0] + trans_R2[1];
    
    //Accumvar
    H_1 += trans_S1[0];
    H_2 += trans_S2[0];
    H_3 += trans_S3[0];
")

## ----rinit-------------------------------------------------
rinit <- Csnippet("
    I_1=452;
    I_2=68;
    I_3=41;
    S_1=5.20208e+06;
    S_2=5.74359e+07;
    S_3=1.97052e+07;
    R_1=19586;
    R_2=7320;
    R_3=2151;
    H_1 = 0;
    H_2 = 0;
    H_3 = 0;
")


## ----rmeasure-------------------------------------------------
rmeas <- Csnippet("
  if(t<209){
    cases1 = rbinom(H_1, 0.06652121); // this is observed cases
    cases2 = rbinom(H_2, 0.06652121);
    cases3 = rbinom(H_3, 0.06652121);
  }
  else{
    cases1 = rbinom(H_1, 0.09283434); // this is observed cases
    cases2 = rbinom(H_2, 0.09283434);
    cases3 = rbinom(H_3, 0.09283434);
  }
")

dmeas <- Csnippet("
  if(t < 209){
    lik = dbinom(cases1, H_1, 0.06652121, 1) + dbinom(cases2, H_2, 0.06652121, 1) + dbinom(cases3, H_3, 0.06652121, 1);
  }
  else{
    lik = dbinom(cases1, H_1, 0.09283434, 1) + dbinom(cases2, H_2, 0.09283434, 1) + dbinom(cases3, H_3, 0.09283434, 1);
  }
")
```


#### Full Momdel with Simulator

#### Full Momdel with Calculated rinit & rmeas Plots

```{r}
# process model is Markovian SIRS with 3 age classes
sir.step <- Csnippet("
                     double rate[19];
                     double dN[19];
                     double Beta1;
                     double Beta2;
                     double Beta3;
                     double I;
                     double dW;
                     
                     // compute the environmental stochasticity
                     dW = rgammawn(sigma,dt);
                     I= I1+I2+I3;
                     Beta1 = beta1*(1 + beta11 * cos(M_2PI/52*t + phi));
                     Beta2 = beta2*(1 + beta11 * cos(M_2PI/52*t + phi));
                     Beta3 = beta3*(1 + beta11 * cos(M_2PI/52*t + phi));
                     rate[0] = alpha*N;         // Birth
                     rate[1] = Beta1*I/N*dW/dt; // S1 Trans: dW is gamma white noise, i.e. st in X.
                     rate[2] = delta1;          // S1 Aging
                     rate[3] = Beta2*I/N*dW/dt; // S2 Trans
                     rate[4] = delta2;          // S2 Aging
                     rate[5] = Beta3*I/N*dW/dt; // S3 Trans
                     rate[6] = mu;              // S3 Death
                     rate[7] = gamma;           // I1 Trans
                     rate[8] = delta1;          // I2 Aging
                     rate[9] = gamma;           // I2 Trnas
                     rate[10] = delta2;         // I2 Aging
                     rate[11] = gamma;          // I3 Trans
                     rate[12] = mu;             // I3 Death
                     rate[13] = delta1;         // R1 Aging
                     rate[14] = omega;          // R1 Trans
                     rate[15] = delta2;         // R2 Aging
                     rate[16] = omega;          // R2 Trans
                     rate[17] = mu;             // R3 Death
                     rate[18] = omega;          // R3 Trans
                     dN[0] = rpois(rate[0]*dt); // alpha*N*dt
                     reulermultinom(2, S1, &rate[1], dt, &dN[1]);
                     reulermultinom(2, S2, &rate[3], dt, &dN[3]);
                     reulermultinom(2, S3, &rate[5], dt, &dN[5]);
                     reulermultinom(2, I1, &rate[7], dt, &dN[7]);
                     reulermultinom(2, I2, &rate[9], dt, &dN[9]);
                     reulermultinom(2, I3, &rate[11], dt, &dN[11]);
                     reulermultinom(2, R1, &rate[13], dt, &dN[13]);
                     reulermultinom(2, R2, &rate[15], dt, &dN[15]);
                     reulermultinom(2, R3, &rate[17], dt, &dN[17]);
                     S1 += dN[0] - dN[1] - dN[2] + dN[14];
                     S2 += dN[2] - dN[3] - dN[4]  + dN[16];
                     S3 += dN[4] - dN[5] - dN[6] + dN[18];
                     I1 += dN[1]          - dN[7] - dN[8];
                     I2 += dN[3] + dN[8]  - dN[9] - dN[10];
                     I3 += dN[5] + dN[10] - dN[11] - dN[12];
                     R1 += dN[7]           - dN[13] - dN[14];
                     R2 += dN[9]  + dN[13] - dN[15] - dN[16];
                     R3 += dN[11] + dN[15] - dN[17] - dN[18];
                     H1 += dN[1];
                     H2 += dN[3];
                     H3 += dN[5];
                     ")



# ------------ deterministic skeleton-----------------------------
sir.skel <- "
double rate[19];
double term[19];
double Beta1;
double Beta2;
double Beta3;

Beta1 = beta1*(1 + beta11 * cos(M_2PI/52*t + phi)); //seasonal forcing
Beta2 = beta2*(1 + beta11 * cos(M_2PI/52*t + phi)); //seasonal forcing
Beta3 = beta3*(1 + beta11 * cos(M_2PI/52*t + phi)); //seasonal forcing

rate[0] = alpha*N;
rate[1] = Beta1*(I1+I2+I3)/N;
rate[2] = delta1;

rate[3] = Beta2*(I1+I2+I3)/N;
rate[4] = delta2;

rate[5] = Beta3*(I1+I2+I3)/N;
rate[6] = mu;

rate[7] = gamma;
rate[8] = delta1;

rate[9] = gamma;
rate[10] = delta2;

rate[11] = gamma;
rate[12] = mu;

rate[13] = delta1;
rate[14] = omega;  

rate[15] = delta2;  
rate[16] = omega;  

rate[17] = mu;  
rate[18] = omega;  


// compute the several terms
term[0] = rate[0];

term[1] = rate[1] * S1;
term[2] = rate[2] * S1;

term[3] = rate[3] * S2;
term[4] = rate[4] * S2;

term[5] = rate[5] * S3;
term[6] = rate[6] * S3;

term[7] = rate[7] * I1;
term[8] = rate[8] * I1;

term[9] = rate[9] * I2;
term[10] = rate[10] * I2;

term[11] = rate[11] * I3;
term[12] = rate[12] * I3;

term[13] = rate[13] * R1;
term[14] = rate[14] * R1;

term[15] = rate[15] * R2;
term[16] = rate[16] * R2;

term[17] = rate[17] * R3;
term[18] = rate[18] * R3;


DS1 = term[0] - term[1] - term[2] + term[14];
DI1 = term[1]          - term[7] - term[8];
DR1 = term[7]          - term[13] - term[14];
DH1 = term[1];

DS2 = term[2] - term[3] - term[4]  + term[16];
DI2 = term[3] + term[8]  - term[9] - term[10];
DR2 = term[9]  + term[13] - term[15] - term[16];
DH2 = term[3];

DS3 = term[4] - term[5] - term[6] + term[18];
DI3 = term[5] + term[10] - term[11] - term[12];
DR3 = term[11] + term[15] - term[17] - term[18];
DH3 = term[5];

" 

# read in the data
# add at t=0 a row of NAs to not have problems with the accumulator variable since
# t0 is much less than t[1]
setwd("~/Study/STATS489/PAL_check/rotavirus/pomp-astic/pomp_st+st+/pomp_st+st+_data/mle_gamma_data")
read.table("rotavirus.txt") %>%
  rbind(data.frame(time=0,cases1=NA,cases2=NA,cases3=NA)) %>%
  arrange(time) -> dat


# define parameters (without betas)
params_fixed <- c(gamma=1, delta1=1/(5*52),delta2=1/(55*52), alpha=1/(78.86912*52), 
                  mu=1/(18.86912*52), N=82372825, omega=1/(1*52))
first_data <- c(y1=dat$cases1[2], y2=dat$cases2[2], y3=dat$cases3[2])


# initializer
init <- function(params, t0, ...) {
  x0 <- c(S1=0,I1=0,R1=0,H1=0,S2=0,I2=0,R2=0,H2=0,S3=0,I3=0,R3=0,H3=0)
  y <- params[c("y1","y2","y3")]
  x0["I1"] <- y[1]/((params["gamma"]+params["delta1"]))
  x0["I2"] <- (y[2]+params["delta1"]*x0["I1"])/((params["delta2"]+params["gamma"]))
  x0["I3"] <- (y[3]+params["delta2"]*x0["I2"])/((params["mu"]+params["gamma"]))
  x0["S1"] <- (params["alpha"]*params["N"]-(params["gamma"]+params["delta1"])*x0["I1"]+
                 params["omega"]*(params["N"]*params["alpha"]/params["delta1"]-x0["I1"]))/(params["delta1"]+params["omega"])
  I_bar    <-  x0["I1"]+x0["I2"]+x0["I3"]
  x0["S2"] <- (params["delta1"]*x0["S1"]-(params["delta2"]+params["gamma"])*x0["I2"]+params["delta1"]*x0["I1"]+
                 params["omega"]*(params["N"]*params["alpha"]/params["delta2"]-x0["I2"]))/(params["delta2"]+params["omega"])
  x0["S3"] <- (params["delta2"]*x0["S2"]-(params["gamma"]+params["mu"])*x0["I3"]+params["delta2"]*x0["I2"]+
                 params["omega"]*(params["N"]*params["alpha"]/params["mu"]-x0["I3"]))/(params["omega"]+params["mu"])
  x0["R1"] <- (params["N"]*params["alpha"]/params["delta1"]-x0["S1"]-x0["I1"])
  x0["R2"] <- (params["N"]*params["alpha"]/params["delta2"]-x0["S2"]-x0["I2"])
  x0["R3"] <- (params["N"]*params["alpha"]/params["mu"]-x0["S3"]-x0["I3"])
  round(x0) 
}

## ----rinit-------------------------------------------------
rinit_raw <- Csnippet("
  I1 = nearbyint(y1/(gamma+delta1));
  I2 = nearbyint((y2+delta1*I1)/((delta2+gamma)));
  I3 = nearbyint((y3+delta2*I2)/((mu+gamma)));
  S1 = nearbyint((alpha*N-(gamma+delta1)*I1+omega*(N*alpha/delta1-I1))/(delta1+omega));
  S2 = nearbyint((delta1*S1-(delta2+gamma)*I2+delta1*I1+omega*(N*alpha/delta2-I2))/(delta2+omega));
  S3 = nearbyint((delta2*S2-(gamma+mu)*I3+delta2*I2+omega*(N*alpha/mu-I3))/(omega+mu));
  R1 = nearbyint((N*alpha/delta1-S1-I1));
  R2 = nearbyint((N*alpha/delta2-S2-I2));
  R3 = nearbyint((N*alpha/mu-S3-I3));
")

rinit <- Csnippet("
    I1=2871;
    I2=639;
    I3=174;
    S1=5.09484e+06;
    S2=5.73856e+07;
    S3=1.96976e+07;
    R1=124410;
    R2=57072;
    R3=9578;
    H1 = 0;
    H2 = 0;
    H3 = 0;
")

#help parameters with different data ie the mean data
mean_data <- c(y1=mean(dat$cases1[-1]), y2=mean(dat$cases2[-1]), y3=mean(dat$cases3[-1])) 
help_param <- c(params_fixed,mean_data)
# analytic guess for the betas
beta_ana <-  function(params){
  beta_ana <- c(beta1=0, beta2=0, beta3=0)
  I_bar <- init(params)["I1"]+init(params)["I2"]+init(params)["I3"]
  beta_ana["beta1"] <- ((params["gamma"]+params["delta1"])*init(params)["I1"]*params["N"])/(init(params)["S1"]*I_bar)
  beta_ana["beta2"] <- ((params["delta2"]+params["gamma"])*init(params)["I2"]-params["delta1"]*init(params)["I1"])*params["N"]/(init(params)["S2"]*I_bar)
  beta_ana["beta3"] <- ((params["mu"]+params["gamma"])*init(params)["I3"]-params["delta2"]*init(params)["I2"])*params["N"]/(init(params)["S3"]*I_bar)
  return(beta_ana)
}

params <- c(beta_ana(help_param), beta11=0.15, phi=0.1, params_fixed,first_data,od=0.3, sigma=0.05)
params_stocks <- params
toEst<- Csnippet("
                 Tbeta1  = log(beta1);
                 Tbeta2  = log(beta2);
                 Tbeta3  = log(beta3);
                 Tbeta11 = logit(beta11);
                 Tsigma = log(sigma);
                 Tphi    = logit(phi/(M_2PI));
                 Tod = log(od);")

fromEst <-Csnippet("
                   beta1  = exp(Tbeta1);
                   beta2  = exp(Tbeta2);
                   beta3  = exp(Tbeta3);
                   sigma = exp(Tsigma);
                   beta11 = expit(Tbeta11);
                   phi    = M_2PI*expit(Tphi);
                   od = exp(Tod);")
```

```{r}
rproc <- Csnippet("
    double gamma = 1.0;
    double d_1=1/(5.0*52.0);           // d1 = 0.003846154
    double d_2=1/(55.0*52.0);          // d2 = 0.0003496503
    double N = 82372825;
    double alpha = 1/(78.86912*52.0);  // alpha = 0.0002438314
    double delta = 1 - 1/(18.86912*52.0);  // delta = 1-0.001019166 = 0.9989808
    double omega = 1/(1.0*52.0);         // omega = 0.01923077
    
    double dW = rgammawn(sigma, dt);
    int I = I_1 + I_2 + I_3;
    int trans_S1[3], trans_S2[3], trans_S3[2], trans_I1[3], trans_I2[3], trans_I3[2], trans_R1[3], trans_R2[3], trans_R3[2];
    
    double prob_S1[3],prob_I1[3],prob_R1[3],prob_S2[3],prob_I2[3],prob_R2[3],prob_S3[2],prob_I3[2],prob_R3[2];
    
    double kappa = (1 + rho*cos(2*3.141593*t/52 + phi));
    double Beta_1 = beta1*kappa; //seasonal forcing
    double Beta_2 = beta2*kappa; //seasonal forcing
    double Beta_3 = beta3*kappa; //seasonal forcing
    
    // Define rate
    prob_S1[0] = 1-exp(-Beta_1*I/N*dW);
    prob_S1[1] = 1-exp(-dt*d_1);
    prob_S1[2] = exp(-dt*d_1) + exp(-Beta_1*I/N*dW) - 1;
    
    prob_I1[0] = 1-exp(-dt*gamma);
    prob_I1[1] = 1-exp(-dt*d_1);
    prob_I1[2] = exp(-dt*gamma)+exp(-dt*d_1) - 1;
    
    prob_R1[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R1[1] = 1 - exp(-dt*d_1);
    prob_R1[2] = exp(-dt*omega) + exp(-dt*d_1) - 1;
    
    prob_S2[0] = 1-exp(-Beta_2*I/N*dW);
    prob_S2[1] = 1-exp(-dt*d_2);
    prob_S2[2] = exp(-dt*d_2) + exp(-Beta_2*I/N*dW) - 1;
    
    prob_I2[0] = 1-exp(-dt*gamma);
    prob_I2[1] = 1-exp(-dt*d_2);
    prob_I2[2] = exp(-dt*gamma)+exp(-dt*d_2) - 1;
    
    prob_R2[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R2[1] = 1 - exp(-dt*d_1);
    prob_R2[2] = exp(-dt*omega) + exp(-dt*d_1) - 1;
    
    // For Age Group (3): Die first before transition;
    
    double S3mD = rbinom(S_3, delta);
    double I3mD = rbinom(I_3, delta);
    double R3mD = rbinom(R_3, delta);
    
    prob_S3[0] = 1-exp(-Beta_3*I/N*dW);
    prob_S3[1] = exp(-Beta_3*I/N*dW);
    
    prob_I3[0] = 1 - exp(-dt*gamma);
    prob_I3[1] = exp(-dt*gamma);
    
    prob_R3[0] = 1 - exp(-dt*omega);
    prob_R3[1] = exp(-dt*omega);
    
    // Transition
    // B: S->I
    // C: I->R
    // F: Aging: (1)->(2)->(3)
    // E: R->S
    // D: Death
    //// Note: Here S_1, S_2... are all old value from (t-1)
    rmultinom(S_1, &prob_S1, 3, &trans_S1); // B, F, S-B-F
    rmultinom(I_1, &prob_I1, 3, &trans_I1); // C, F, I-C-F
    rmultinom(R_1, &prob_R1, 3, &trans_R1); // E, F, R-E-F
    
    rmultinom(S_2, &prob_S2, 3, &trans_S2); // B, F, S-B-F
    rmultinom(I_2, &prob_I2, 3, &trans_I2); // C, F, I-C-F
    rmultinom(R_2, &prob_R2, 3, &trans_R2); // E, F, R-E-F
    
    rmultinom(S3mD, &prob_S3, 2, &trans_S3); // B, (S-D)-B
    rmultinom(I3mD, &prob_I3, 2, &trans_I3); // C, (I-D)-C
    rmultinom(R3mD, &prob_R3, 2, &trans_R3); // E, (R-D)-E
    
    S_1 = trans_S1[2] + trans_R1[0] + rpois(alpha*N*dt); // Include Birth
    I_1 = trans_I1[2] + trans_S1[0];
    R_1 = trans_R1[2] + trans_I1[0];
    
    S_2 = trans_S2[2] + trans_R2[0] + trans_S1[1]; // Include Aging
    I_2 = trans_I2[2] + trans_S2[0] + trans_I1[1];
    R_2 = trans_R2[2] + trans_I2[0] + trans_R1[1];
    
    S_3 = trans_S3[1] + trans_R3[0] + trans_S2[1]; // Include Aging
    I_3 = trans_I3[1] + trans_S3[0] + trans_I2[1];
    R_3 = trans_R3[1] + trans_I3[0] + trans_R2[1];
    
    //Accumvar
    H_1 += trans_S1[0];
    H_2 += trans_S2[0];
    H_3 += trans_S3[0];
    
    
")

## ----rinit-------------------------------------------------
rinit <- Csnippet("
    I_1=2871;
    I_2=639;
    I_3=174;
    S_1=5.09484e+06;
    S_2=5.73856e+07;
    S_3=1.96976e+07;
    R_1=124410;
    R_2=57072;
    R_3=9578;
    H_1 = 0;
    H_2 = 0;
    H_3 = 0;
")


## ----rmeasure-------------------------------------------------
rmeas <- Csnippet("
  if(t<209){
    cases1 = rbinom(H_1, 0.06205271); // this is observed cases
    cases2 = rbinom(H_2, 0.06762432);
    cases3 = rbinom(H_3, 0.06988662);
  }
  else{
    cases1 = rbinom(H_1, 0.08791755); // this is observed cases
    cases2 = rbinom(H_2, 0.09408622);
    cases3 = rbinom(H_3, 0.09649926);
  }
")

dmeas <- Csnippet("
  if(t < 209){
    lik = dbinom(cases1, H_1, 0.06205271, 1) + dbinom(cases2, H_2, 0.06762432, 1) + dbinom(cases3, H_3, 0.06988662, 1);
  }
  else{
    lik = dbinom(cases1, H_1, 0.08791755, 1) + dbinom(cases2, H_2, 0.09408622, 1) + dbinom(cases3, H_3, 0.09649926, 1);
  }
")

sim1 <- simulate(t0=0, 
                 times = 1:416, 
                 paramnames = c("beta1","beta2","beta3","phi","rho","sigma"),
                 params = c(beta1 = 11.48, beta2 = 0.25, beta3 = 0.35, 
                            phi = 0.14, rho = 0.16, sigma=66.89),
                 rinit = rinit,
                 rprocess = discrete_time(rproc, delta.t=1/10),
                 rmeasure = rmeas,
                 statenames=c("S_1","I_1","R_1",
                              "S_2","I_2","R_2",
                              "S_3","I_3","R_3",
                              "H_1","H_2","H_3"),
                 accumvars=c("H_1","H_2","H_3"),
                 obsnames=c("cases1","cases2","cases3"))

(sim_data <- as.data.frame(sim1))

ggplot(data=sim_data) + 
 geom_line(aes(x=time, y=cases1),color='green') +
 geom_line(aes(x=time, y=cases2), color='red') +
 geom_line(aes(x=time, y=cases3), color='blue') +
  ylab('Y_mine')+xlab('date')

load("~/Study/STATS489/PAL_check/rotavirus/real_rotavirus_metadata.Rdata")
realdat <- data.frame(time = c(1:416), realdat)
ggplot(data=realdat) + 
 geom_line(aes(x=time, y=cases1),color='green') +
 geom_line(aes(x=time, y=cases2), color='red') +
 geom_line(aes(x=time, y=cases3), color='blue') +
  ylab('Y_real')+xlab('date')
```

```{r}
rproc <- Csnippet("
    double gamma = 1.0;
    double d_1=1/(5.0*52.0);           // d1 = 0.003846154
    double d_2=1/(55.0*52.0);          // d2 = 0.0003496503
    double N = 82372825;
    double alpha = 1/(78.86912*52.0);  // alpha = 0.0002438314
    double delta = 1 - 1/(18.86912*52.0);  // delta = 0.9989808
    double omega = 1/(1.0*52.0);         // omega = 0.01923077
    
    int I = I_1 + I_2 + I_3;
    int trans_S1[3], trans_S2[3], trans_S3[2], trans_I1[3], trans_I2[3], trans_I3[2], trans_R1[3], trans_R2[3], trans_R3[2];
    
    double prob_S1[3],prob_I1[3],prob_R1[3],prob_S2[3],prob_I2[3],prob_R2[3],prob_S3[2],prob_I3[2],prob_R3[2];
    
    double kappa = (1 + rho*cos(2*3.141593*t/52 + phi));
    double Beta_1 = beta1*kappa; //seasonal forcing
    double Beta_2 = beta2*kappa; //seasonal forcing
    double Beta_3 = beta3*kappa; //seasonal forcing
    
    // Define rate
    prob_S1[0] = 1-exp(-Beta_1*I/N);
    prob_S1[1] = 1-exp(-dt*d_1);
    prob_S1[2] = exp(-dt*d_1) + exp(-Beta_1*I/N) - 1;
    
    prob_I1[0] = 1-exp(-dt*gamma);
    prob_I1[1] = 1-exp(-dt*d_1);
    prob_I1[2] = exp(-dt*gamma)+exp(-dt*d_1) - 1;
    
    prob_R1[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R1[1] = 1 - exp(-dt*d_1);
    prob_R1[2] = exp(-dt*omega) + exp(-dt*d_1) - 1;
    
    prob_S2[0] = 1-exp(-Beta_2*I/N);
    prob_S2[1] = 1-exp(-dt*d_2);
    prob_S2[2] = exp(-dt*d_2) + exp(-Beta_2*I/N) - 1;
    
    prob_I2[0] = 1-exp(-dt*gamma);
    prob_I2[1] = 1-exp(-dt*d_2);
    prob_I2[2] = exp(-dt*gamma)+exp(-dt*d_2) - 1;
    
    prob_R2[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R2[1] = 1 - exp(-dt*d_1);
    prob_R2[2] = exp(-dt*omega) + exp(-dt*d_1) - 1;
    
    // For Age Group (3): Die first before transition;
    
    double S3mD = rbinom(S_3, delta);
    double I3mD = rbinom(I_3, delta);
    double R3mD = rbinom(R_3, delta);
    
    prob_S3[0] = 1-exp(-Beta_3*I/N);
    prob_S3[1] = exp(-Beta_3*I/N);
    
    prob_I3[0] = 1 - exp(-dt*gamma);
    prob_I3[1] = exp(-dt*gamma);
    
    prob_R3[0] = 1 - exp(-dt*omega);
    prob_R3[1] = exp(-dt*omega);
    
    // Transition
    // B: S->I
    // C: I->R
    // F: Aging: (1)->(2)->(3)
    // E: R->S
    // D: Death
    //// Note: Here S_1, S_2... are all old value from (t-1)
    rmultinom(S_1, &prob_S1, 3, &trans_S1); // B, F, S-B-F
    rmultinom(I_1, &prob_I1, 3, &trans_I1); // C, F, I-C-F
    rmultinom(R_1, &prob_R1, 3, &trans_R1); // E, F, R-E-F
    
    rmultinom(S_2, &prob_S2, 3, &trans_S2); // B, F, S-B-F
    rmultinom(I_2, &prob_I2, 3, &trans_I2); // C, F, I-C-F
    rmultinom(R_2, &prob_R2, 3, &trans_R2); // E, F, R-E-F
    
    rmultinom(S3mD, &prob_S3, 2, &trans_S3); // B, (S-D)-B
    rmultinom(I3mD, &prob_I3, 2, &trans_I3); // C, (I-D)-C
    rmultinom(R3mD, &prob_R3, 2, &trans_R3); // E, (R-D)-E
    
    S_1 = trans_S1[2] + trans_R1[0] + rpois(alpha*N*dt); // Include Birth
    I_1 = trans_I1[2] + trans_S1[0];
    R_1 = trans_R1[2] + trans_I1[0];
    
    S_2 = trans_S2[2] + trans_R2[0] + trans_S1[1]; // Include Aging
    I_2 = trans_I2[2] + trans_S2[0] + trans_I1[1];
    R_2 = trans_R2[2] + trans_I2[0] + trans_R1[1];
    
    S_3 = trans_S3[1] + trans_R3[0] + trans_S2[1]; // Include Aging
    I_3 = trans_I3[1] + trans_S3[0] + trans_I2[1];
    R_3 = trans_R3[1] + trans_I3[0] + trans_R2[1];
    
    //Accumvar
    H_1 += trans_S1[0];
    H_2 += trans_S2[0];
    H_3 += trans_S3[0];
    
    
")

## ----rinit-------------------------------------------------
rinit <- Csnippet("
    I_1=452;
    I_2=68;
    I_3=41;
    S_1=5.20208e+06;
    S_2=5.74359e+07;
    S_3=1.97052e+07;
    R_1=19586;
    R_2=7320;
    R_3=2151;
    H_1 = 0;
    H_2 = 0;
    H_3 = 0;
")


## ----rmeasure-------------------------------------------------
rmeas <- Csnippet("
  if(t<209){
    cases1 = rbinom(H_1, 0.06652121); // this is observed cases
    cases2 = rbinom(H_2, 0.06652121);
    cases3 = rbinom(H_3, 0.06652121);
  }
  else{
    cases1 = rbinom(H_1, 0.09283434); // this is observed cases
    cases2 = rbinom(H_2, 0.09283434);
    cases3 = rbinom(H_3, 0.09283434);
  }
")

dmeas <- Csnippet("
  if(t < 209){
    lik = dbinom(cases1, H_1, 0.06652121, 1) + dbinom(cases2, H_2, 0.06652121, 1) + dbinom(cases3, H_3, 0.06652121, 1);
  }
  else{
    lik = dbinom(cases1, H_1, 0.09283434, 1) + dbinom(cases2, H_2, 0.09283434, 1) + dbinom(cases3, H_3, 0.09283434, 1);
  }
")

sim1 <- simulate(t0=0, 
                 times = 1:416, 
                 paramnames = c("beta1","beta2","beta3","phi","rho"),
                 params = c(beta1 = 12.15, beta2 = 0.22, beta3 = 0.34, 
                            phi = 0.017, rho = 0.022),
                 rinit = rinit,
                 rprocess = discrete_time(rproc, delta.t=1/4),
                 rmeasure = rmeas,
                 statenames=c("S_1","I_1","R_1",
                              "S_2","I_2","R_2",
                              "S_3","I_3","R_3",
                              "H_1","H_2","H_3"),
                 accumvars=c("H_1","H_2","H_3"),
                 obsnames=c("cases1","cases2","cases3"))

(sim_data <- as.data.frame(sim1))

ggplot(data=sim_data) + 
 geom_line(aes(x=time, y=S_1),color='green') +
 geom_line(aes(x=time, y=I_1), color='red') +
 geom_line(aes(x=time, y=R_1), color='blue') +
  ylab('X')+xlab('date')

ggplot(data=sim_data) + 
 geom_line(aes(x=time, y=cases1),color='green') +
 geom_line(aes(x=time, y=cases2), color='red') +
 geom_line(aes(x=time, y=cases3), color='blue') +
  ylab('Y_mine')+xlab('date')

load("~/Study/STATS489/PAL_check/rotavirus/real_rotavirus_metadata.Rdata")
realdat <- data.frame(time = c(1:416), realdat)
ggplot(data=realdat) + 
 geom_line(aes(x=time, y=cases1),color='green') +
 geom_line(aes(x=time, y=cases2), color='red') +
 geom_line(aes(x=time, y=cases3), color='blue') +
  ylab('Y_real')+xlab('date')
```

#### Pfilter

##### model

```{r}
rproc <- Csnippet("
    double gamma = 1.0;
    double d_1=1/(5.0*52.0);           // d1 = 0.003846154
    double d_2=1/(55.0*52.0);          // d2 = 0.0003496503
    double N = 82372825;
    double alpha = 1/(78.86912*52.0);  // alpha = 0.0002438314
    double delta = 1 - 1/(18.86912*52.0);  // delta = 0.9989808
    double omega = 1/(1.0*52.0);         // omega = 0.01923077
    
    int I = I_1 + I_2 + I_3;
    int trans_S1[3], trans_S2[3], trans_S3[2], trans_I1[3], trans_I2[3], trans_I3[2], trans_R1[3], trans_R2[3], trans_R3[2];
    
    double prob_S1[3],prob_I1[3],prob_R1[3],prob_S2[3],prob_I2[3],prob_R2[3],prob_S3[2],prob_I3[2],prob_R3[2];
    
    double kappa = (1 + rho*cos(2*3.141593*t/52 + phi));
    double Beta_1 = beta1*kappa; //seasonal forcing
    double Beta_2 = beta2*kappa; //seasonal forcing
    double Beta_3 = beta3*kappa; //seasonal forcing
    
    // Define rate
    prob_S1[0] = 1-exp(-Beta_1*I/N*dt);
    prob_S1[1] = 1-exp(-dt*d_1);
    prob_S1[2] = exp(-dt*d_1) + exp(-Beta_1*I/N*dt) - 1;
    
    prob_I1[0] = 1-exp(-dt*gamma);
    prob_I1[1] = 1-exp(-dt*d_1);
    prob_I1[2] = exp(-dt*gamma)+exp(-dt*d_1) - 1;
    
    prob_R1[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R1[1] = 1 - exp(-dt*d_1);
    prob_R1[2] = exp(-dt*omega) + exp(-dt*d_1) - 1;
    
    prob_S2[0] = 1-exp(-Beta_2*I/N*dt);
    prob_S2[1] = 1-exp(-dt*d_2);
    prob_S2[2] = exp(-dt*d_2) + exp(-Beta_2*I/N*dt) - 1;
    
    prob_I2[0] = 1-exp(-dt*gamma);
    prob_I2[1] = 1-exp(-dt*d_2);
    prob_I2[2] = exp(-dt*gamma)+exp(-dt*d_2) - 1;
    
    prob_R2[0] = 1 - exp(-dt*omega);  // E_1,t this goes back to S_1,(t+1)
    prob_R2[1] = 1 - exp(-dt*d_1);
    prob_R2[2] = exp(-dt*omega) + exp(-dt*d_1) - 1;
    
    // For Age Group (3): Die first before transition;
    
    double S3mD = rbinom(S_3, delta);
    double I3mD = rbinom(I_3, delta);
    double R3mD = rbinom(R_3, delta);
    
    prob_S3[0] = 1-exp(-Beta_3*I/N*dt);
    prob_S3[1] = exp(-Beta_3*I/N*dt);
    
    prob_I3[0] = 1 - exp(-dt*gamma);
    prob_I3[1] = exp(-dt*gamma);
    
    prob_R3[0] = 1 - exp(-dt*omega);
    prob_R3[1] = exp(-dt*omega);
    
    // Transition
    // B: S->I
    // C: I->R
    // F: Aging: (1)->(2)->(3)
    // E: R->S
    // D: Death
    //// Note: Here S_1, S_2... are all old value from (t-1)
    rmultinom(S_1, &prob_S1, 3, &trans_S1); // B, F, S-B-F
    rmultinom(I_1, &prob_I1, 3, &trans_I1); // C, F, I-C-F
    rmultinom(R_1, &prob_R1, 3, &trans_R1); // E, F, R-E-F
    
    rmultinom(S_2, &prob_S2, 3, &trans_S2); // B, F, S-B-F
    rmultinom(I_2, &prob_I2, 3, &trans_I2); // C, F, I-C-F
    rmultinom(R_2, &prob_R2, 3, &trans_R2); // E, F, R-E-F
    
    rmultinom(S3mD, &prob_S3, 2, &trans_S3); // B, (S-D)-B
    rmultinom(I3mD, &prob_I3, 2, &trans_I3); // C, (I-D)-C
    rmultinom(R3mD, &prob_R3, 2, &trans_R3); // E, (R-D)-E
    
    S_1 = trans_S1[2] + trans_R1[0] + rpois(alpha*N*dt); // Include Birth
    I_1 = trans_I1[2] + trans_S1[0];
    R_1 = trans_R1[2] + trans_I1[0];
    
    S_2 = trans_S2[2] + trans_R2[0] + trans_S1[1]; // Include Aging
    I_2 = trans_I2[2] + trans_S2[0] + trans_I1[1];
    R_2 = trans_R2[2] + trans_I2[0] + trans_R1[1];
    
    S_3 = trans_S3[1] + trans_R3[0] + trans_S2[1]; // Include Aging
    I_3 = trans_I3[1] + trans_S3[0] + trans_I2[1];
    R_3 = trans_R3[1] + trans_I3[0] + trans_R2[1];
    
    //Accumvar
    H_1 += trans_S1[0];
    H_2 += trans_S2[0];
    H_3 += trans_S3[0];
")

## ----rinit-------------------------------------------------
rinit <- Csnippet("
    I_1=452;
    I_2=68;
    I_3=41;
    S_1=5.20208e+06;
    S_2=5.74359e+07;
    S_3=1.97052e+07;
    R_1=19586;
    R_2=7320;
    R_3=2151;
    H_1 = 0;
    H_2 = 0;
    H_3 = 0;
")


## ----rmeasure-------------------------------------------------
rmeas <- Csnippet("
  if(t<209){
    cases1 = rbinom(H_1, 0.06652121); // this is observed cases
    cases2 = rbinom(H_2, 0.06652121);
    cases3 = rbinom(H_3, 0.06652121);
  }
  else{
    cases1 = rbinom(H_1, 0.09283434); // this is observed cases
    cases2 = rbinom(H_2, 0.09283434);
    cases3 = rbinom(H_3, 0.09283434);
  }
")

dmeas <- Csnippet("
  if(t < 209){
    lik = dbinom(cases1, H_1, 0.06652121, 1) + dbinom(cases2, H_2, 0.06652121, 1) + dbinom(cases3, H_3, 0.06652121, 1);
  }
  else{
    lik = dbinom(cases1, H_1, 0.09283434, 1) + dbinom(cases2, H_2, 0.09283434, 1) + dbinom(cases3, H_3, 0.09283434, 1);
  }
")
```

##### pfilter

```{r}
dat <- data.frame(realdat, time = c(1:(52*8)))

dat |>
  pomp(t0=0,
    time="time",
    rprocess=discrete_time(rproc,delta.t=1/4), ## Obs time every week, but delta.t transition is actually everyday
    rinit=rinit,
    dmeasure=dmeas,
    rmeasure=rmeas,
    accumvars=c("H_1","H_2","H_3"),
    statenames=c("S_1","S_2","S_3","I_1","I_2","I_3","R_1","R_2","R_3","H_1","H_2","H_3"),
    paramnames=c("beta1","beta2","beta3","phi","rho")
  ) -> m1

theta <- c(beta1 = 12.15, beta2 = 0.22, beta3 = 0.42, phi = 0.1, rho = 0.15)

plan(multicore)
foreach(i=1:4, .combine=c,
  .options.future=list(seed=998468235L)
) %dopar% {
  pfilter(m1,Np=10000,params=theta)
} -> pfs

logmeanexp(logLik(pfs),se=TRUE)
```



#### To Be Calculated rinit

```{r}
## ----rinit-------------------------------------------------
rinit <- Csnippet("
  double y1 = 454.0;
  double y2 = 66.0;
  double y3 = 41.0;
  double N = 82372825.0;
  double gamma = 1.0;
  double d_1=1/(5*52.0);
  double d_2=1/(55*52.0);
  double alpha = 1/(78.86912*52.0);
  double delta = 1/(18.86912*52.0);
  double omega = 1/(1*52.0);
  
  I_1 = nearbyint(y1/(gamma+d_1));
  I_2 = nearbyint((y2+d_1*I_1)/((d_2+gamma)));
  I_3 = nearbyint((y3+d_2*I_2)/((delta+gamma)));
  S_1 = nearbyint((alpha*N-(gamma+d_1)*I_1+omega*(N*alpha/d_1-I_1))/(d_1+omega));
  S_2 = nearbyint((d_1*S_1-(d_2+gamma)*I_2+d_1*I_1+omega*(N*alpha/d_2-I_2))/(d_2+omega));
  S_3 = nearbyint((d_2*S_2-(gamma+delta)*I_3+d_2*I_2+omega*(N*alpha/delta-I_3))/(omega+delta));
  R_1 = nearbyint((N*alpha/d_1-S_1-I_1));
  R_2 = nearbyint((N*alpha/d_2-S_2-I_2));
  R_3 = nearbyint((N*alpha/delta-S_3-I_3));
")
```
